import type {Ability,Character,Skill} from '../types';
import {effectBonus,derivedAbilityMod} from './effects';
import {featDefinition,featHasSaveProficiency,featSkillExpertise,featSkillProficiency} from './feats';
export const ABILITIES:Ability[]=['str','dex','con','int','wis','cha'];
export const SKILLS:Record<Skill,{ability:Ability;name:string}>={acrobatics:{ability:'dex',name:'Acrobatics'},animalHandling:{ability:'wis',name:'Animal Handling'},arcana:{ability:'int',name:'Arcana'},athletics:{ability:'str',name:'Athletics'},deception:{ability:'cha',name:'Deception'},history:{ability:'int',name:'History'},insight:{ability:'wis',name:'Insight'},intimidation:{ability:'cha',name:'Intimidation'},investigation:{ability:'int',name:'Investigation'},medicine:{ability:'wis',name:'Medicine'},nature:{ability:'int',name:'Nature'},perception:{ability:'wis',name:'Perception'},performance:{ability:'cha',name:'Performance'},persuasion:{ability:'cha',name:'Persuasion'},religion:{ability:'int',name:'Religion'},sleightOfHand:{ability:'dex',name:'Sleight of Hand'},stealth:{ability:'dex',name:'Stealth'},survival:{ability:'wis',name:'Survival'}};
export function abilityMod(score:number){return Math.floor((score-10)/2)}
export function proficiencyBonus(level:number){return Math.ceil(level/4)+1}
export function skillBonus(c:Character,skill:Skill){const s=c.skillStates[skill];const proficient=s.proficient||featSkillProficiency(c,skill);const expertise=s.expertise||featSkillExpertise(c,skill);const base=derivedAbilityMod(c,SKILLS[skill].ability);return base+(proficient?c.proficiencyBonus:0)+(expertise?c.proficiencyBonus:0)+(s.bonusOverride??0)+effectBonus(c,'skill',undefined,skill)}
export function saveBonus(c:Character,a:Ability){return derivedAbilityMod(c,a)+((c.savingThrowProficiency.includes(a)||featHasSaveProficiency(c,a))?c.proficiencyBonus:0)+effectBonus(c,'savingThrows',a)}
export function initiative(c:Character){return derivedAbilityMod(c,'dex')+effectBonus(c,'initiative')}
export function passivePerception(c:Character){return 10+skillBonus(c,'perception')+effectBonus(c,'passivePerception')}
export function passiveInvestigation(c:Character){return 10+skillBonus(c,'investigation')+effectBonus(c,'passiveInvestigation')}
export function speed(c:Character){let value=c.speed??30;const armor=c.items.find(i=>i.equipped&&i.kind==='armor')?.armor;const armored=!!armor;const shield=c.items.some(i=>i.equipped&&i.kind==='shield');for(const cl of c.classes){if(cl.id==='monk'&&!armored&&!shield&&cl.level>=2)value+=cl.level>=18?30:cl.level>=14?25:cl.level>=10?20:cl.level>=6?15:10;if(cl.id==='barbarian'&&(!armor||armor.category!=='heavy')&&cl.level>=5)value+=10}return value+effectBonus(c,'speed')}
export function maxDexForArmor(c:Character){const armor=c.items.find(i=>i.equipped&&i.kind==='armor')?.armor;if(!armor||!armor.dexBonus)return 0;const explicit=armor.dexCap;if(explicit!==undefined)return explicit;const base=armor.category==='medium'?2:armor.category==='heavy'?0:99;const mediumMaster=(c.feats??[]).some(name=>(featDefinition(name)?.id??name)==='medium-armor-master');return armor.category==='medium'&&mediumMaster?3:base}
export function armorClass(c:Character){const armor=c.items.find(i=>i.equipped&&i.kind==='armor')?.armor;const shield=c.items.find(i=>i.equipped&&i.kind==='shield')?.shield;const dex=derivedAbilityMod(c,'dex');if(armor){let ac=armor.baseAC+(armor.dexBonus?Math.min(dex,maxDexForArmor(c)):0)+armor.magicBonus;if(shield)ac+=shield.acBonus+shield.magicBonus;return ac+effectBonus(c,'ac')}let ac=10+dex;const primary=c.classes[0]?.id;if(primary==='barbarian')ac+=derivedAbilityMod(c,'con');else if(primary==='monk'&&!shield)ac+=derivedAbilityMod(c,'wis');else if(primary==='sorcerer'&&c.classes[0]?.subclassId==='draconic')ac+=3;if(shield&&primary!=='monk')ac+=shield.acBonus+shield.magicBonus;return ac+effectBonus(c,'ac')}
export function totalLevel(c:Character){return c.classes.reduce((n,x)=>n+x.level,0)}
