import type {Ability,Character,Skill} from '../types';
export const ABILITIES:Ability[]=['str','dex','con','int','wis','cha'];
export const SKILLS:Record<Skill,{ability:Ability;name:string}>={acrobatics:{ability:'dex',name:'Acrobatics'},animalHandling:{ability:'wis',name:'Animal Handling'},arcana:{ability:'int',name:'Arcana'},athletics:{ability:'str',name:'Athletics'},deception:{ability:'cha',name:'Deception'},history:{ability:'int',name:'History'},insight:{ability:'wis',name:'Insight'},intimidation:{ability:'cha',name:'Intimidation'},investigation:{ability:'int',name:'Investigation'},medicine:{ability:'wis',name:'Medicine'},nature:{ability:'int',name:'Nature'},perception:{ability:'wis',name:'Perception'},performance:{ability:'cha',name:'Performance'},persuasion:{ability:'cha',name:'Persuasion'},religion:{ability:'int',name:'Religion'},sleightOfHand:{ability:'dex',name:'Sleight of Hand'},stealth:{ability:'dex',name:'Stealth'},survival:{ability:'wis',name:'Survival'}};
export function abilityMod(score:number){return Math.floor((score-10)/2)}
export function proficiencyBonus(level:number){return Math.ceil(level/4)+1}
export function skillBonus(c:Character,skill:Skill){const s=c.skillStates[skill];const base=abilityMod(c.abilityScores[SKILLS[skill].ability]);return base+(s.proficient?c.proficiencyBonus:0)+(s.expertise?c.proficiencyBonus:0)+(s.bonusOverride??0)}
export function saveBonus(c:Character,a:Ability){return abilityMod(c.abilityScores[a])+(c.savingThrowProficiency.includes(a)?c.proficiencyBonus:0)}
export function initiative(c:Character){return abilityMod(c.abilityScores.dex)}
export function passivePerception(c:Character){return 10+skillBonus(c,'perception')}
export function maxDexForArmor(c:Character){const armor=c.items.find(i=>i.equipped&&i.kind==='armor')?.armor;if(!armor||!armor.dexBonus)return 0;return armor.dexCap??99}
export function armorClass(c:Character){const armor=c.items.find(i=>i.equipped&&i.kind==='armor')?.armor;const shield=c.items.find(i=>i.equipped&&i.kind==='shield')?.shield;const dex=abilityMod(c.abilityScores.dex);let ac=10;if(armor){const dexPart=armor.dexBonus?Math.min(dex,maxDexForArmor(c)):0;ac=armor.baseAC+dexPart+armor.magicBonus}else ac+=dex;if(shield)ac+=shield.acBonus+shield.magicBonus;if(c.fightingStyles?.includes('defense')&&!!armor)ac+=1;return ac}
export function totalLevel(c:Character){return c.classes.reduce((n,x)=>n+x.level,0)}
