import type {Character,Die,RestType} from '../types';
import {derivedAbilityMod,derivedMaxHP} from './effects';
import {classResources} from './resources';
function availablePoolIndex(c:Character,die?:Die){return c.hitDice.pools.findIndex(p=>p.current>0&&(!die||p.die===die))}
export function totalHitDice(c:Character){return c.hitDice.pools.reduce((n,p)=>n+p.max,0)}
export function currentHitDice(c:Character){return c.hitDice.pools.reduce((n,p)=>n+p.current,0)}
export function recoverHitDice(c:Character){const next=structuredClone(c);const target=Math.max(1,Math.floor(totalHitDice(next)/2));let remaining=Math.max(0,target-currentHitDice(next));for(const pool of next.hitDice.pools){if(remaining<=0)break;const gain=Math.min(remaining,pool.max-pool.current);pool.current+=gain;remaining-=gain}return next}
function recoverResources(next:Character,type:RestType){const derived=classResources(next);const stored=new Map(next.resources.map(r=>[r.id,r]));const recovered=derived.filter(r=>r.unlimited||r.recharge==='short'||(type==='long'&&r.recharge==='long')).map(r=>({...r,current:r.unlimited?0:r.max}));for(const r of recovered)stored.set(r.id,r);next.resources=[...stored.values()];next.resources.forEach(r=>{if(r.unlimited)return;if(r.recharge==='short'||(type==='long'&&r.recharge==='long'))r.current=r.max});next.items.forEach(i=>{const charges=i.charges;if(charges&&(charges.recharge==='short'||(type==='long'&&charges.recharge==='long')))charges.current=charges.max})}
export function recoverRestResources(c:Character,type:RestType):Character{const next=structuredClone(c);recoverResources(next,type);if(type==='short'){Object.values(next.spellcasting).forEach(s=>{if(s.pactSlots)s.pactSlots.used=0});return next}if(next.sharedSpellSlots)next.sharedSpellSlots=Object.fromEntries(Object.entries(next.sharedSpellSlots).map(([level,slot])=>[level,{...slot,used:0}]));Object.values(next.spellcasting).forEach(s=>{Object.values(s.slots).forEach(x=>{x.used=0});if(s.pactSlots)s.pactSlots.used=0});return next}
export function spendHitDice(c:Character,count:number,hpRecovered:number):Character{const requested=Math.trunc(count);const healing=Math.trunc(hpRecovered);if(requested<1||healing<0||currentHitDice(c)<requested)return c;const next=structuredClone(c);let remaining=requested;for(const pool of next.hitDice.pools){if(remaining<=0)break;const spend=Math.min(pool.current,remaining);pool.current-=spend;remaining-=spend}if(remaining>0)return c;next.currentHP=Math.min(derivedMaxHP(next),next.currentHP+healing);if(next.currentHP>0)next.deathSaves={successes:0,failures:0};return next}
export function applyRest(c:Character,type:RestType):Character{if(type==='short')return recoverRestResources(c,'short');const next=structuredClone(c);next.currentHP=derivedMaxHP(next);next.tempHP=0;next.deathSaves={successes:0,failures:0};next.hitDice=recoverHitDice(next).hitDice;return recoverRestResources(next,'long')}
export function spendHitDie(c:Character,die?:Die):Character{const maxHP=derivedMaxHP(c);if(currentHitDice(c)<=0||c.currentHP>=maxHP)return c;const index=availablePoolIndex(c,die);if(index<0)return c;const pool=c.hitDice.pools[index];const roll=1+Math.floor(Math.random()*pool.die);const healing=Math.max(0,roll+derivedAbilityMod(c,'con'));return spendHitDice(c,1,healing)}
