import type {Character,Spell,SpellState} from '../types';
import {CLASSES} from '../catalog';
import {subclassAlwaysPreparedSpellIds} from '../content/subclass-spell-access';
import {derivedAbilityMod} from './effects';
const PACT_SLOTS:[number,number][]=[[1,1],[2,2],[3,2],[4,2],[5,2],[6,2],[7,2],[8,2],[9,2],[10,2],[11,3],[12,3],[13,3],[14,3],[15,3],[16,3],[17,4],[18,4],[19,4],[20,4]];
const PACT_SLOT_LEVEL=[0,1,1,2,2,3,3,4,4,5,5,5,5,5,5,5,5,5,5,5,5];
const KNOWN_SPELLS:Record<string,number[]>={bard:[4,5,6,7,8,9,10,11,12,14,15,15,16,18,19,19,20,22,22,22],sorcerer:[4,5,6,7,8,9,10,11,12,13,15,15,15,18,18,18,19,19,20,22],warlock:[2,3,4,5,6,7,8,9,10,10,11,11,12,12,13,13,14,14,15,15]};
const FULL_CASTER=['bard','cleric','druid','sorcerer','wizard'];
export function emptySpellState():SpellState{return {known:[],prepared:[],alwaysPrepared:[],spellbook:[],slots:{}}}
export function spellcastingClass(c:Character,classId:string){return c.classes.find(x=>x.id===classId)}
export function eligibleClassSpells(spells:Spell[],classId:string,enabledSources:string[]){return spells.filter(s=>s.classes.includes(classId)&&enabledSources.includes(s.source??'phb2014'))}
export function subclassAlwaysPrepared(c:Character,classId:string):string[]{const cl=spellcastingClass(c,classId);if(!cl)return [];return subclassAlwaysPreparedSpellIds(cl)}
export function hydrateSubclassAlwaysPrepared(c:Character,classId:string):Character{const cl=spellcastingClass(c,classId);if(!cl)return c;const state=c.spellcasting[classId]??emptySpellState();const always=[...new Set([...state.alwaysPrepared,...subclassAlwaysPreparedSpellIds(cl)])];return {...c,spellcasting:{...c.spellcasting,[classId]:{...state,alwaysPrepared:always}}}}
export function availablePrepared(state:SpellState){return [...new Set([...state.alwaysPrepared,...state.prepared])]}
export function canPrepare(state:SpellState,spellId:string,preparedLimit:number){if(state.alwaysPrepared.includes(spellId))return true;if(state.prepared.includes(spellId))return true;return state.prepared.length<preparedLimit}
export function setPrepared(state:SpellState,spellId:string,prepared:boolean,limit:number):SpellState{const always=state.alwaysPrepared.includes(spellId);const next=new Set(state.prepared);if(always)return state;if(prepared&&next.size<limit)next.add(spellId);if(!prepared)next.delete(spellId);return {...state,prepared:[...next]}}
export function maxPreparedSpells(c:Character,classId:string){const cl=c.classes.find(x=>x.id===classId);const def=CLASSES.find(x=>x.id===classId);if(!cl?.spellcastingAbility||!def)return 0;const m=Math.max(0,derivedAbilityMod(c,cl.spellcastingAbility));if(def.spellcasting==='spellbook')return Math.max(1,m+cl.level);if(def.spellcasting==='prepared'){if(classId==='paladin'||classId==='ranger'||classId==='artificer')return Math.max(1,m+Math.floor(cl.level/2));return Math.max(1,m+cl.level)}return 0}
export function maxKnownSpells(c:Character,classId:string){const cl=c.classes.find(x=>x.id===classId);const table=KNOWN_SPELLS[classId];if(!cl||!table)return 0;return table[Math.max(1,Math.min(20,cl.level))-1]}
export function canKnowSpell(c:Character,classId:string,spellId:string){const state=c.spellcasting[classId]??emptySpellState();return state.known.includes(spellId)||state.known.length<maxKnownSpells(c,classId)}
export function spellcastingProgression(c:Character,classId:string){const cl=c.classes.find(x=>x.id===classId);if(!cl)return {fullCasterLevels:0,halfCasterLevels:0,thirdCasterLevels:0,pactLevels:0};const subclass=cl.subclassId;if((classId==='fighter'&&subclass==='eldritch-knight')||(classId==='rogue'&&subclass==='arcane-trickster'))return {fullCasterLevels:0,halfCasterLevels:0,thirdCasterLevels:cl.level,pactLevels:0};if(classId==='paladin'||classId==='ranger'||classId==='artificer')return {fullCasterLevels:0,halfCasterLevels:cl.level,thirdCasterLevels:0,pactLevels:0};if(FULL_CASTER.includes(classId))return {fullCasterLevels:cl.level,halfCasterLevels:0,thirdCasterLevels:0,pactLevels:0};if(classId==='warlock')return {fullCasterLevels:0,halfCasterLevels:0,thirdCasterLevels:0,pactLevels:cl.level};return {fullCasterLevels:0,halfCasterLevels:0,thirdCasterLevels:0,pactLevels:0}}
export function multiclassCasterLevel(c:Character){let full=0,half=0,third=0;for(const cl of c.classes){const p=spellcastingProgression(c,cl.id);full+=p.fullCasterLevels;half+=cl.id==='artificer'?Math.ceil(p.halfCasterLevels/2):Math.floor(p.halfCasterLevels/2);third+=Math.floor(p.thirdCasterLevels/3)}return full+half+third}
export function pactMagicSlots(c:Character,classId='warlock'){const cl=c.classes.find(x=>x.id===classId);if(!cl||classId!=='warlock')return null;const [,max]=PACT_SLOTS[Math.max(1,Math.min(20,cl.level))-1];const level=PACT_SLOT_LEVEL[Math.max(1,Math.min(20,cl.level))];return {max,level}}
export function beginConcentration(c:Character,classId:string,spell:Spell):Character{if(!spell.concentration)return c;return {...c,concentration:{spellId:spell.id,classId}}}
export function endConcentration(c:Character):Character{if(!c.concentration)return c;const {concentration:_,...rest}=c;return rest}
export function concentrationSaveDC(damage:number){return Math.max(10,Math.floor(damage/2))}
