/* D&D Companion v2 — UI only. All rules come from DnDEngineV2. */
(() => {
  'use strict';
  const E=window.DnDEngineV2,D=window.DnDDataV2;
  let section='sheet';
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const signed=n=>Number(n)>0?`+${n}`:String(n);
  const label=s=>String(s).replace(/([A-Z])/g,' $1').replace(/[-_]/g,' ').replace(/^./,c=>c.toUpperCase());
  function render(){const c=E.state,s=E.summary(c);$('#app').innerHTML=`<div class="app-shell">
    <header class="hero"><div class="hero-mark">✦</div><div><div class="eyebrow">D&D COMPANION · 5E 2014</div><h1>${esc(c.identity.name||'Unnamed Adventurer')}</h1><p>${classLine(c)}${c.identity.alignment?` · ${esc(c.identity.alignment)}`:''}</p></div><button class="icon-button" data-action="edit">⚙</button></header>
    <main>${section==='sheet'?sheet(c,s):section==='abilities'?abilities(c,s):section==='inventory'?inventory(c,s):section==='spells'?spells(c):rules(c)}</main>
    <nav class="bottom-nav">${nav('sheet','◈','Sheet')}${nav('abilities','✦','Abilities')}${nav('inventory','◇','Inventory')}${nav('spells','✧','Spells')}${nav('rules','☷','Rules')}</nav>
  </div>`;bind();}
  function classLine(c){return (c.classes||[]).map(x=>`${label(D.CLASSES[x.classId]?.name||x.classId)} ${x.level}${x.subclass?` · ${D.SUBCLASSES.find(s=>s.id===x.subclass&&s.classId===x.classId)?.name||x.subclass}`:''}`).join(' / ')||'Level 1';}
  function nav(id,icon,text){return `<button class="nav-item ${section===id?'active':''}" data-nav="${id}"><span>${icon}</span><small>${text}</small></button>`}
  function sheet(c,s){return `<section class="grid two">
    <article class="card stat-card accent"><div class="stat-label">HIT POINTS</div><div class="big-value">${c.resources.hp.current}<span> / ${s.hpMaximum}</span></div><div class="meter"><i style="width:${Math.max(0,Math.min(100,c.resources.hp.current/s.hpMaximum*100))}%"></i></div><div class="stepper"><button data-hp="-1">−</button><button data-hp="1">+</button></div></article>
    <article class="card stat-card"><div class="stat-label">ARMOR CLASS</div><div class="big-value">${s.ac}</div><div class="muted">Initiative ${signed(s.initiative)} · Speed ${s.speed} ft</div></article>
  </section>
  <section class="grid six abilities-mini">${D.ABILITIES.map(a=>`<button class="ability-mini" data-ability="${a}"><span>${a.slice(0,3).toUpperCase()}</span><b>${signed(s.abilities[a].modifier)}</b><small>${s.abilities[a].score}</small></button>`).join('')}</section>
  <section class="grid three"><button class="card menu-card" data-nav="abilities"><b>Abilities & Skills</b><span>Skills, saves, features</span></button><button class="card menu-card" data-nav="inventory"><b>Inventory</b><span>${c.items.length} items · ${s.carriedWeight}/${s.carryingCapacity} lb</span></button><button class="card menu-card" data-nav="spells"><b>Spellbook</b><span>${c.spells.length} spells${s.spellDC?` · DC ${s.spellDC}`:''}</span></button></section>
  <section class="card"><div class="section-title"><h2>Resources</h2><button class="text-button" data-action="rest">Rest</button></div><div class="resource-grid"><div><span>Hit Dice</span><b>${Object.values(s.hitDice).reduce((n,x)=>n+x.current,0)} / ${Object.values(s.hitDice).reduce((n,x)=>n+x.maximum,0)}</b></div><div><span>Inspiration</span><b>${c.resources.inspiration?'Ready':'—'}</b></div><div><span>Spell Slots</span><b>${Object.values(s.spellSlots).reduce((n,x)=>n+x,0)||'—'}</b></div></div></section>`}
  function abilities(c,s){return `<section class="page-head"><div><div class="eyebrow">CHARACTER</div><h2>Abilities & Features</h2></div><button class="button" data-action="edit">Edit</button></section><section class="grid two">${D.ABILITIES.map(a=>`<article class="card ability-row"><div><b>${label(a)}</b><span>${s.abilities[a].score}</span></div><strong>${signed(s.abilities[a].modifier)}</strong></article>`).join('')}</section><article class="card"><div class="section-title"><h2>Saving Throws</h2></div><div class="list">${D.ABILITIES.map(a=>`<div><span>${label(a)}</span><b>${signed(E.saveThrow(c,a))}</b></div>`).join('')}</div></article><article class="card"><div class="section-title"><h2>Skills</h2></div><div class="skill-grid">${Object.keys(D.SKILLS).map(k=>`<div><span>${label(k)}</span><b>${signed(E.skill(c,k))}</b></div>`).join('')}</div></article><article class="card"><div class="section-title"><h2>Features</h2><span class="pill">${s.features.length}</span></div><div class="list">${s.features.map(f=>`<div><span>${esc(f.name)}</span><small>Lv ${f.level} · ${esc(D.CLASSES[f.classId]?.name||'')}</small></div>`).join('')||'<div class="muted">No class features recorded yet.</div>'}</div></article>`}
  function inventory(c,s){return `<section class="page-head"><div><div class="eyebrow">EQUIPMENT</div><h2>Inventory</h2></div><button class="button" data-action="add-item">+ Add item</button></section><div class="inventory-summary"><span>Carrying <b>${s.carriedWeight} / ${s.carryingCapacity} lb</b></span><span>${c.items.filter(i=>i.equipment?.equipped).length} equipped</span></div><section class="inventory-list">${c.items.map((i,idx)=>`<article class="card item-row"><div class="item-main"><div class="item-icon">${i.mechanics?.type==='weapon'?'⚔':i.mechanics?.type==='armor'?'♜':i.mechanics?.type==='shield'?'◉':'◇'}</div><div><b>${esc(i.name||'Unnamed item')}</b><small>${esc(i.description||i.inventorySection||'Miscellaneous')} · ${Number(i.weight)||0} lb × ${Number(i.quantity)||1}</small>${i.mechanics?.type==='weapon'&&E.attack(c,i)?`<small>Attack ${signed(E.attack(c,i).bonus)} · ${E.attack(c,i).damage.map(d=>`${d.dice?.count||''}${d.dice?.die||''} ${d.type}`).join(' + ')}</small>`:''}</div></div><div class="item-actions"><button data-equip="${idx}">${i.equipment?.equipped?'Unequip':'Equip'}</button><button class="danger" data-remove="${idx}">×</button></div></article>`).join('')||'<article class="card empty">Your pack is empty.</article>'}</section>`}
  function spells(c){return `<section class="page-head"><div><div class="eyebrow">MAGIC</div><h2>Spellbook</h2></div><button class="button" data-action="add-spell">+ Add spell</button></section><article class="card spell-summary"><div><span>Spellcasting</span><b>${E.spellAbility(c)?label(E.spellAbility(c)):'—'}</b></div><div><span>Attack</span><b>${E.spellAttack(c)==null?'—':signed(E.spellAttack(c))}</b></div><div><span>Save DC</span><b>${E.spellDC(c)==null?'—':E.spellDC(c)}</b></div></article><section class="list-card">${c.spells.map((sp,i)=>`<article class="card spell-row"><div><b>${esc(sp.name||'Unnamed spell')}</b><small>Level ${sp.level??0} · ${esc(sp.school||'Unknown')}</small></div><button data-remove-spell="${i}">×</button></article>`).join('')||'<article class="card empty">No spells added.</article>'}</section>`}
  function rules(c){return `<section class="page-head"><div><div class="eyebrow">RULES ENGINE</div><h2>Sources & Options</h2></div></section><article class="card"><p class="muted">The companion calculates the character from structured rules data. Player's Handbook is always available; Xanathar and Tasha options can be enabled or disabled per character.</p>${Object.values(D.SOURCES).map(src=>`<label class="toggle-row"><span><b>${esc(src.name)}</b><small>${src.optional?'Optional content':'Core rules'}</small></span><input type="checkbox" data-source="${src.id}" ${src.id==='phb2014'||c.rules.sources[src.id]?'checked':''} ${src.id==='phb2014'?'disabled':''}></label>`).join('')}</article><article class="card"><div class="section-title"><h2>Available subclasses</h2></div><div class="option-grid">${(c.classes||[]).map(cl=>`<div><b>${esc(D.CLASSES[cl.classId]?.name||cl.classId)}</b>${D.SUBCLASSES.filter(s=>s.classId===cl.classId&&E.summary(c).sources.find(x=>x.id===s.source)?.enabled).map(s=>`<button class="option-chip ${cl.subclass===s.id?'selected':''}" data-subclass="${cl.classId}:${s.id}">${esc(s.name)}<small>${s.source==='phb2014'?'PHB':s.source==='xanathar'?'Xanathar':'Tasha'}</small></button>`).join('')}</div>`).join('')}</div></article>`}
  function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{section=b.dataset.nav;render()});document.querySelectorAll('[data-hp]').forEach(b=>b.onclick=()=>{E.state.resources.hp.current=Math.max(0,Math.min(E.summary().hpMaximum,E.state.resources.hp.current+Number(b.dataset.hp)));E.save();render()});document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{const i=E.state.items[Number(b.dataset.equip)];if(!i)return;i.equipment=i.equipment||{};i.equipment.equipped=!i.equipment.equipped;E.save();render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{E.state.items.splice(Number(b.dataset.remove),1);E.save();render()});document.querySelectorAll('[data-remove-spell]').forEach(b=>b.onclick=()=>{E.state.spells.splice(Number(b.dataset.removeSpell),1);E.save();render()});document.querySelectorAll('[data-source]').forEach(b=>b.onchange=()=>{E.state.rules.sources[b.dataset.source]=b.checked;E.save();render()});document.querySelectorAll('[data-subclass]').forEach(b=>b.onclick=()=>{const [cid,sid]=b.dataset.subclass.split(':');const cl=E.state.classes.find(x=>x.classId===cid);if(cl){cl.subclass=sid;cl.source=D.SUBCLASSES.find(x=>x.classId===cid&&x.id===sid)?.source||'phb2014';E.save();render()}});document.querySelectorAll('[data-action="edit"]').forEach(b=>b.onclick=openEditor);document.querySelectorAll('[data-action="add-item"]').forEach(b=>b.onclick=addItem);document.querySelectorAll('[data-action="add-spell"]').forEach(b=>b.onclick=addSpell);document.querySelectorAll('[data-action="rest"]').forEach(b=>b.onclick=rest);document.querySelectorAll('[data-ability]').forEach(b=>b.onclick=()=>alert(`${label(b.dataset.ability)}: ${E.summary().abilities[b.dataset.ability].score} (${signed(E.summary().abilities[b.dataset.ability].modifier)})`));}
  function openEditor(){const c=E.state;const name=prompt('Character name',c.identity.name||'');if(name!==null)c.identity.name=name;const alignment=prompt('Alignment',c.identity.alignment||'');if(alignment!==null)c.identity.alignment=alignment;const cls=prompt('Class (barbarian, bard, cleric, druid, fighter, monk, paladin, ranger, rogue, sorcerer, warlock, wizard, artificer)',c.classes[0]?.classId||'fighter');if(cls&&D.CLASSES[cls])c.classes[0].classId=cls;const level=prompt('Level',String(c.classes[0]?.level||1));if(level!==null)c.classes[0].level=Math.max(1,Math.min(20,Number(level)||1));E.save();render();}
  function addItem(){const name=prompt('Item name');if(!name)return;const type=prompt('Type: weapon, armor, shield, other','other');const item={id:`item-${Date.now()}`,name,description:'',quantity:1,weight:0,inventorySection:type==='weapon'||type==='armor'||type==='shield'?'equipment':'miscellaneous',equipment:{type,equipped:false},mechanics:{type}};if(type==='weapon'){item.mechanics.attack={type:'melee',ability:null,proficient:true,bonus:0};item.mechanics.damage=[{dice:{count:1,die:'d8'},type:'slashing',ability:null,modifier:0}];}if(type==='armor')Object.assign(item.mechanics,{category:'light',armorClass:11,dexterity:{maximum:null},strengthRequirement:0});if(type==='shield')item.mechanics.armorBonus=2;E.state.items.push(item);E.save();render();}
  function addSpell(){const name=prompt('Spell name');if(!name)return;const level=prompt('Spell level 0-9','1');E.state.spells.push({id:`spell-${Date.now()}`,name,level:Number(level)||0,school:''});E.save();render();}
  function rest(){const long=confirm('Long rest? Cancel = short rest.');if(long){E.state.resources.hp.current=E.summary().hpMaximum;E.state.resources.deathSaves={successes:0,failures:0};Object.keys(E.state.resources.hitDice||{}).forEach(k=>E.state.resources.hitDice[k].current=E.state.resources.hitDice[k].maximum);}else{Object.keys(E.state.resources.hitDice||{}).forEach(k=>E.state.resources.hitDice[k].current=Math.min(E.state.resources.hitDice[k].maximum,E.state.resources.hitDice[k].current));}E.save();render();}
  window.addEventListener('dnd:character-changed',()=>{});window.DnDAppV2={render};render();
})();