import {useMemo,useState} from 'react';
import {CLASSES,SPECIES} from '../domain/catalog';
import {SPECIES_DATA} from '../domain/content/species';
import {ALL_SUBCLASSES} from '../domain/content/subclass-registry';
import {CONTENT_SOURCES} from '../domain/content/sources';
import {CLASS_SOURCES} from '../domain/content/class-sources';
import {OPTIONAL_CLASS_FEATURES} from '../domain/content/optional-class-features';
import {BACKGROUNDS} from '../domain/content/backgrounds';
import {ABILITIES,CLASS_SKILL_COUNT,CLASS_SKILL_OPTIONS,createBlankCharacter,setClass,assignSubclass,STANDARD_ARRAY} from '../domain/character-builder';
import {applySpecies,mod} from '../domain/rules';
import type {Ability,Character,Skill} from '../domain/types';
export function Builder({onCreate}:{onCreate:(c:Character)=>void}){
 const [c,setC]=useState<Character>(()=>createBlankCharacter());const [step,setStep]=useState(1);const [scores,setScores]=useState<Record<Ability,number>>({str:15,dex:14,con:13,int:12,wis:10,cha:8});const cls=c.classes[0]?.id??'';const speciesDef=SPECIES_DATA.find(s=>s.name===c.species);const sources=c.contentSources??['phb2014','homebrew'];const enabled=new Set(sources);const classSource=CLASS_SOURCES[cls];const sourceMissing=!!classSource&&!enabled.has(classSource);const subclasses=useMemo(()=> (ALL_SUBCLASSES[cls]??[]).filter(s=>enabled.has(s.source)),[cls,sources.join('|')]);const optional=sources.includes('tasha2020')?(OPTIONAL_CLASS_FEATURES[cls]??[]):[];const skillOptions=CLASS_SKILL_OPTIONS[cls]??[];const background=BACKGROUNDS.find(b=>b.id===c.background);const backgroundSkills=new Set(background?.skills??[]);const selectedClass=(Object.keys(c.skillStates) as Skill[]).filter(s=>c.skillStates[s].proficient&&!backgroundSkills.has(s));const usedScores=new Set(Object.values(scores));const abilityChoices=c.speciesAbilityChoices??[];const skillChoices=c.speciesSkillChoices??[];const abilityChoiceNeeded=speciesDef?.abilityChoiceCount??0;const skillChoiceNeeded=speciesDef?.skillProficiencyChoices??0;
 const chooseSpecies=(name:string)=>setC(x=>({...x,species:name,subspecies:undefined,speciesAbilityChoices:[],speciesSkillChoices:[],feats:x.feats?.filter(f=>!f.startsWith('Variant Human'))}));
 const chooseClass=(id:string)=>{setC(setClass({...c,abilityScores:scores},id));setStep(2)};
 const toggleSpeciesAbility=(a:Ability)=>setC(x=>{const def=SPECIES_DATA.find(s=>s.name===x.species);if(!def)return x;const current=x.speciesAbilityChoices??[];const has=current.includes(a);if(has)return {...x,speciesAbilityChoices:current.filter(v=>v!==a)};if(current.length>=(def.abilityChoiceCount??0))return x;return {...x,speciesAbilityChoices:[...current,a]}});
 const toggleSpeciesSkill=(s:Skill)=>setC(x=>{const def=SPECIES_DATA.find(v=>v.name===x.species);if(!def)return x;const current=x.speciesSkillChoices??[];if(current.includes(s))return {...x,speciesSkillChoices:current.filter(v=>v!==s)};if(current.length>=(def.skillProficiencyChoices??0))return x;return {...x,speciesSkillChoices:[...current,s]}});
 const toggleSource=(id:string)=>setC(x=>{if(id==='phb2014'||id==='homebrew')return x;const next=new Set(x.contentSources??['phb2014','homebrew']);next.has(id)?next.delete(id):next.add(id);return {...x,contentSources:[...next]}});
 const chooseSubclass=(id:string)=>{setC(x=>assignSubclass(x,id));setStep(4)};const toggleOptional=(id:string)=>setC(x=>{const next=new Set(x.optionalFeatures??[]);next.has(id)?next.delete(id):next.add(id);return {...x,optionalFeatures:[...next]}});const setScore=(a:Ability,value:number)=>setScores(x=>{const other=Object.entries(x).find(([key,v])=>key!==a&&v===value)?.[0];return other?{...x,[a]:value,[other]:x[a]}:{...x,[a]:value}});
 const toggleSkill=(s:Skill)=>setC(x=>{if(backgroundSkills.has(s))return x;const on=x.skillStates[s].proficient;if(on)return {...x,skillStates:{...x.skillStates,[s]:{proficient:false,expertise:false}}};const count=(Object.keys(x.skillStates) as Skill[]).filter(k=>x.skillStates[k].proficient&&!backgroundSkills.has(k)).length;if(count>=CLASS_SKILL_COUNT[cls])return x;return {...x,skillStates:{...x.skillStates,[s]:{proficient:true,expertise:false}}}});
 const chooseBackground=(id:string)=>setC(x=>{const next=BACKGROUNDS.find(b=>b.id===id);const skills={...x.skillStates};const old=BACKGROUNDS.find(b=>b.id===x.background);(old?.skills??[]).forEach(s=>{skills[s]={proficient:false,expertise:false}});next?.skills.forEach(s=>{skills[s]={proficient:true,expertise:false}});return {...x,background:id,backgroundData:next?{name:next.name,skillProficiencies:next.skillProficiencies,toolProficiencies:next.toolProficiencies,languages:next.languages,feature:next.feature}:undefined,skillStates:skills}});
 const finish=()=>{const subId=speciesDef?.subraces.find(s=>s.name===c.subspecies)?.id;const withSpecies=applySpecies({...c,abilityScores:scores},SPECIES_DATA.find(s=>s.name===c.species)?.id??'',subId);const conMod=mod(withSpecies.abilityScores.con);const die=CLASSES.find(x=>x.id===cls)?.hitDie??8;const hp=Math.max(1,die+conMod);onCreate({...withSpecies,proficiencyBonus:2,maxHP:hp,currentHP:hp})};
 const speciesChoicesValid=abilityChoices.length===abilityChoiceNeeded&&skillChoices.length===skillChoiceNeeded;
 return <section className="card builder"><div className="row"><div><h2>Create Character</h2><p className="muted">5e 2014 builder. Sources, species, background, class and skill choices are explicit.</p></div><b>Step {step} / 6</b></div>
 {step===1&&<><h3>Species</h3><div className="choice-grid">{SPECIES.map(s=><button className={c.species===s?'choice selected':'choice'} key={s} onClick={()=>chooseSpecies(s)}>{s}</button>)}</div>{speciesDef?.subraces.length?<><h3>Subrace</h3><div className="choice-grid">{speciesDef.subraces.map(s=><button className={c.subspecies===s.name?'choice selected':'choice'} key={s.id} onClick={()=>setC(x=>({...x,subspecies:s.name}))}>{s.name}</button>)}</div></>:null}{abilityChoiceNeeded>0&&<><h3>Species ability choices</h3><p className="muted">Choose {abilityChoiceNeeded} different ability scores for +{speciesDef?.abilityChoiceBonus??1}. Fixed bonuses are applied separately.</p><div className="choice-grid">{ABILITIES.map(a=><button className={abilityChoices.includes(a)?'choice selected':'choice'} key={a} onClick={()=>toggleSpeciesAbility(a)}>{a.toUpperCase()}<small>{abilityChoices.includes(a)?'Selected':'Choose'}</small></button>)}</div></>}{skillChoiceNeeded>0&&<><h3>Species skill choices</h3><p className="muted">Choose {skillChoiceNeeded} skill{skillChoiceNeeded>1?'s':''}.</p><div className="choice-grid">{Object.keys(c.skillStates).map(s=><button className={skillChoices.includes(s as Skill)?'choice selected':'choice'} key={s} onClick={()=>toggleSpeciesSkill(s as Skill)}>{s}</button>)}</div></>}<h3>Class</h3><div className="choice-grid">{CLASSES.map(x=><button className={c.classes[0]?.id===x.id?'choice selected':'choice'} key={x.id} onClick={()=>chooseClass(x.id)}>{x.name}<small>d{x.hitDie} · {x.spellcasting}{CLASS_SOURCES[x.id]&&CLASS_SOURCES[x.id]!=='phb2014'?` · ${CLASS_SOURCES[x.id]}`:''}</small></button>)}</div><p className="muted">Species choices required: {speciesChoicesValid?'complete':'not complete'}.</p></>}
 {step===2&&<><h3>Content Sources</h3><p className="muted">PHB 2014 is required. Xanathar and Tasha are optional; Homebrew is always available but clearly marked.</p>{sourceMissing&&<p className="warning">{CLASSES.find(x=>x.id===cls)?.name} requires {classSource} content. Enable that source to continue.</p>}<div className="choice-grid">{CONTENT_SOURCES.map(s=><button disabled={s.required} className={sources.includes(s.id)?'choice selected':'choice'} key={s.id} onClick={()=>toggleSource(s.id)}>{s.name}<small>{s.required?'Required':s.id===classSource?'Required for this class':'Optional'}</small></button>)}</div><button disabled={sourceMissing} onClick={()=>setStep(3)}>Continue</button></>}
 {step===3&&<><h3>Subclass</h3><div className="choice-grid">{subclasses.length?subclasses.map(s=><button className={c.classes[0]?.subclassId===s.id?'choice selected':'choice'} key={s.id} onClick={()=>chooseSubclass(s.id)}>{s.name}<small>{s.source}</small></button>):<p className="muted">No enabled subclass is available.</p>}</div><button onClick={()=>setStep(4)}>Skip subclass for now</button></>}
 {step===4&&<><h3>Optional Class Features</h3>{optional.length?optional.map(f=><button className={(c.optionalFeatures??[]).includes(f.id)?'choice selected':'choice'} key={f.id} onClick={()=>toggleOptional(f.id)}>{f.name}<small>{f.replaces?`Replaces ${f.replaces}`:'Optional'}</small></button>):<p className="muted">No Tasha optional class features are enabled for this class.</p>}<button onClick={()=>setStep(5)}>Continue</button></>}
 {step===5&&<><h3>Ability Scores</h3><p className="muted">Assign the standard array exactly once: 15, 14, 13, 12, 10, 8. Species bonuses are applied after assignment.</p><div className="ability-builder">{ABILITIES.map(a=><label key={a}>{a.toUpperCase()}<select value={scores[a]} onChange={e=>setScore(a,Number(e.target.value))}>{STANDARD_ARRAY.map(v=><option key={v} value={v} disabled={usedScores.has(v)&&scores[a]!==v}>{v}</option>)}</select><small>modifier {mod(scores[a])>=0?'+':''}{mod(scores[a])}</small></label>)}</div><h3>Background</h3><div className="choice-grid">{BACKGROUNDS.map(b=><button className={c.background===b.id?'choice selected':'choice'} key={b.id} onClick={()=>chooseBackground(b.id)}>{b.name}<small>{b.skillProficiencies.join(' · ')} · {b.feature}</small></button>)}</div><button onClick={()=>setStep(6)}>Continue</button></>}
 {step===6&&<><h3>Skill Proficiencies</h3><p className="muted">Background and species skills are already selected. Choose {CLASS_SKILL_COUNT[cls]??0} additional class skill proficiencies.</p><div className="choice-grid">{skillOptions.map(s=><button disabled={backgroundSkills.has(s)||skillChoices.includes(s)} className={c.skillStates[s].proficient?'choice selected':'choice'} key={s} onClick={()=>toggleSkill(s)}>{s}{backgroundSkills.has(s)?<small>Background</small>:skillChoices.includes(s)?<small>Species</small>:null}</button>)}</div><div className="row"><span>{selectedClass.length} / {CLASS_SKILL_COUNT[cls]??0} class skills selected</span><button disabled={selectedClass.length!==CLASS_SKILL_COUNT[cls]||!background||!speciesChoicesValid} onClick={finish}>Create Character</button></div></>}
 </section>
}
