import {useState} from 'react';
import type {Character,Feature,FeatureSource} from '../domain/types';
import {CLASS_PROGRESSION} from '../domain/content/class-progression';
import {OPTIONAL_CLASS_FEATURES} from '../domain/content/optional-class-features';
import {PALADIN_SUBCLASS_FEATURES} from '../domain/content/paladin-subclass-features';
import {FEATURE_DESCRIPTIONS} from '../domain/content/feature-descriptions';
import {SPECIES_BY_ID} from '../domain/content/species';
import {enabledContentSources} from '../domain/content-sources';

const FIGHTING_STYLE_DESCRIPTIONS:Record<string,string>={archery:'+2 to attack rolls with ranged weapons.',defense:'While wearing armor, gain +1 AC.',dueling:'When wielding a melee weapon in one hand and no other weapons, gain +2 to damage rolls with it.','great-weapon-fighting':'Reroll a 1 or 2 on a damage die for a two-handed or versatile melee weapon and use the new roll.',protection:'Use your reaction to impose disadvantage on an attack against a nearby target other than you while wielding a shield.','two-weapon-fighting':'Add your ability modifier to the damage of the second attack when fighting with two weapons.','blind-fighting':'Blindsight to 10 feet.',interception:'Use your reaction to reduce nearby ally damage by 1d10 + proficiency bonus, minimum 0, while wielding a shield or suitable weapon.','thrown-weapon-fighting':'Draw thrown weapons as part of the attack and gain +2 damage on ranged attacks with them.','unarmed-fighting':'Unarmed strikes deal 1d6 + Strength, or 1d8 without weapons/shield; grappled creatures can take 1d4 at the start of your turn.','superior-technique':'Learn one Battle Master maneuver and gain one d6 superiority die, recovered on a short or long rest.','druidic-warrior':'Learn two druid cantrips; they count as ranger spells and use Wisdom.'};
const descriptionFor=(feature:Feature)=>feature.description??FEATURE_DESCRIPTIONS[feature.id]??FEATURE_DESCRIPTIONS[`${feature.id.split(':')[0]}:${feature.id.split(':')[1]}`];
const sourceLabels:Record<FeatureSource,string>={class:'Class',subclass:'Subclass',species:'Species / Race',feat:'Feats',item:'Items',background:'Background',optional:'Optional Features'};
const sourceOrder:FeatureSource[]=['species','background','class','subclass','feat','item','optional'];

export function FeaturesPanel({c,onResource}:{c:Character;onResource?:(resourceId:string)=>void}){
 const [selected,setSelected]=useState<Feature|null>(null);const enabled=new Set(enabledContentSources(c.contentSources));const chosen=new Set(c.optionalFeatures??[]);const species=SPECIES_BY_ID[c.species.toLowerCase()];
 const speciesFeatures:Feature[]=species?[...species.traits,...(c.subspecies?species.subraces.find(s=>s.id===c.subspecies)?.traits??[]):[]];
 const optional=c.classes.flatMap(cl=>(OPTIONAL_CLASS_FEATURES[cl.id]??[]).filter(f=>chosen.has(f.id)&&f.level<=cl.level&&enabled.has(f.sourceBook??'tasha2020')));const storedNonClass=c.features.filter(f=>f.source!=='class'&&f.source!=='species');const progression=c.classes.flatMap(cl=>(CLASS_PROGRESSION[cl.id]??[]).filter(f=>f.level<=cl.level));const subclass=c.classes.flatMap(cl=>cl.subclassId?(PALADIN_SUBCLASS_FEATURES[cl.subclassId]??[]).filter(f=>f.level<=cl.level&&enabled.has(f.sourceBook??'phb2014')):[]);const itemFeatures:Feature[]=c.items.filter(i=>(i.mechanicalEffects?.length||i.effects?.length)&&i.equipped).map(i=>({id:`item:${i.id}`,name:i.name,source:'item',level:0,description:i.description??(i.effects??[]).join(' · '),effects:i.mechanicalEffects}));
 const fightingStyle=c.fightingStyles?.[0];const fightingClass=c.classes.find(cl=>['fighter','paladin','ranger'].includes(cl.id)&&cl.level>=2);const fightingFeature=fightingStyle&&fightingClass?{id:`class:${fightingClass.id}:fighting-style:${fightingStyle}`,name:`Fighting Style — ${fightingStyle.replace(/(^|-)([a-z])/g,(_,a,b)=>`${a?' ':''}${b.toUpperCase()}`)}`,source:'class' as const,level:2,description:FIGHTING_STYLE_DESCRIPTIONS[fightingStyle.toLowerCase()]}:undefined;
 const features:Feature[]=[...speciesFeatures,...storedNonClass,...progression,...subclass,...optional,...itemFeatures,...(fightingFeature?[fightingFeature]:[])].map(f=>({...f,description:descriptionFor(f),...(f.id==='breath-weapon'?{resourceId:'breath-weapon'}:{})}));const unique=[...new Map(features.map(f=>[f.id,f])).values()].sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name));const groups=sourceOrder.map(source=>({source,items:unique.filter(f=>f.source===source)})).filter(g=>g.items.length);
 return <section className="card"><div className="row"><div><h2>Features & Traits</h2><p className="muted">Features are grouped by origin so class, subclass, species, feats, background and item effects stay distinct.</p></div><span className="muted">{unique.length} active</span></div>{groups.map(group=><div key={group.source}><h3>{sourceLabels[group.source]} <small>{group.items.length}</small></h3>{group.items.map(f=><button className="feature feature-button" key={f.id} onClick={()=>setSelected(f)}><div className="row"><b>{f.name}</b><small>{f.level?`Level ${f.level} · `:''}{sourceLabels[f.source]}{f.optional?' · Optional':''}</small></div><small>{f.description?'Description available':f.effects?.length?`${f.effects.length} mechanical effect${f.effects.length===1?'':'s'}`:f.resourceId?'Uses a resource':'Description missing'}</small></button>)}</div>)}{c.feats?.length&&!groups.some(g=>g.source==='feat')&&<p className="muted">No feat entries are currently active.</p>}{selected&&<FeatureModal feature={selected} close={()=>setSelected(null)} onResource={onResource}/>}</section>
}
function FeatureModal({feature,close,onResource}:{feature:Feature;close:()=>void;onResource?:(resourceId:string)=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="row"><div><span className="eyebrow">{sourceLabels[feature.source]}{feature.level?` · Level ${feature.level}`:''}</span><h2>{feature.name}</h2></div><button onClick={close}>×</button></div><p className="feature-description">{feature.description??'The rule summary for this feature is not yet populated in the canonical content catalog.'}</p>{feature.activation&&<p><b>Activation:</b> {feature.activation}</p>}{feature.effects?.length?<><h3>Mechanical effects</h3>{feature.effects.map(e=><div className="effect-line" key={e.id}><b>{e.target}</b><span>{e.value>=0?'+':''}{e.value}{e.ability?` ${e.ability.toUpperCase()}`:''}{e.skill?` · ${e.skill}`:''}</span></div>)}</>:null}{feature.resourceId&&<p><b>Resource:</b> <button onClick={()=>onResource?.(feature.resourceId!)}>{feature.resourceId}</button></p>}</div></div>}
