import type {Character,RechargeType,Resource} from '../domain/types';
import {classResources} from '../domain/rules/resources';
const rechargeLabel=(r:RechargeType)=>r==='short'?'Short Rest':r==='long'?'Long Rest':'Manual';
export function ResourcesPanel({c,update}:{c:Character;update:(fn:(x:Character)=>Character)=>void}){
 const derived=classResources(c);const stored=new Map(c.resources.map(r=>[r.id,r]));const classResourceIds=new Set(derived.map(r=>r.id));
 const classTracked=derived.map(r=>stored.get(r.id)??r);const custom=c.resources.filter(r=>!classResourceIds.has(r.id));
 const itemResources=c.items.filter(i=>i.charges).map(i=>({id:`item:${i.id}`,name:i.name,current:i.charges!.current,max:i.charges!.max,recharge:i.charges!.recharge as RechargeType,sourceId:i.id,description:i.description}));
 const resources=[...classTracked,...custom,...itemResources];
 return <section className="card"><div className="row"><div><h2>Resources</h2><p className="muted">Limited uses from class, subclass, species, feats, spells and items. Recharge is explicit.</p></div><span className="muted">{resources.length} tracked</span></div>{resources.length===0&&<p className="muted">No limited resources configured.</p>}{resources.map(r=><ResourceRow key={r.id} resource={r} update={update} item={r.id.startsWith('item:')} derived={classResourceIds.has(r.id)}/>)}</section>
}
function ResourceRow({resource:r,update,item,derived}:{resource:Resource;update:(fn:(x:Character)=>Character)=>void;item:boolean;derived:boolean}){const change=(delta:number)=>update(x=>{if(item)return {...x,items:x.items.map(i=>i.id===r.id.slice(5)&&i.charges?{...i,charges:{...i.charges,current:Math.max(0,Math.min(i.charges.max,i.charges.current+delta))}}:i)};if(r.unlimited)return x;const current=x.resources.find(y=>y.id===r.id)?.current??r.current;const next=Math.max(0,Math.min(r.max,current+delta));if(x.resources.some(y=>y.id===r.id))return {...x,resources:x.resources.map(y=>y.id===r.id?{...y,current:next}:y)};return {...x,resources:[...x.resources,{...r,current:next}]}});const restore=()=>update(x=>{if(item)return {...x,items:x.items.map(i=>i.id===r.id.slice(5)&&i.charges?{...i,charges:{...i.charges,current:i.charges.max}}:i)};if(r.unlimited)return x;if(x.resources.some(y=>y.id===r.id))return {...x,resources:x.resources.map(y=>y.id===r.id?{...y,current:y.max}:y)};return {...x,resources:[...x.resources,{...r,current:r.max}]}});return <article className="resource resource-row"><div className="row"><div><b>{r.name}</b><small>{r.unlimited?'Unlimited':`${derived?'Class resource · ':''}${rechargeLabel(r.recharge)}`}{r.description?` · ${r.description}`:''}</small></div><strong>{r.unlimited?'∞':`${r.current}/${r.max}`}</strong></div>{!r.unlimited&&<div className="hp-actions"><button disabled={r.current<=0} onClick={()=>change(-1)}>−</button><button disabled={r.current>=r.max} onClick={()=>change(1)}>+</button><button onClick={restore}>Restore</button></div>}</article>}
