import type {Character,RechargeType,Resource} from '../domain/types';
import {classResources} from '../domain/rules/resources';
const rechargeLabel=(r:RechargeType)=>r==='short'?'Short Rest':r==='long'?'Long Rest':'Manual';
const sourceLabel=(sourceId:string|undefined,item=false)=>{if(item)return 'Item';if(!sourceId)return 'Custom';if(sourceId.startsWith('shared:'))return 'Shared';if(sourceId.startsWith('species:'))return 'Species / Race';if(sourceId.startsWith('subclass:'))return 'Subclass';if(sourceId.startsWith('feat:'))return 'Feat';if(sourceId.startsWith('background:'))return 'Background';if(sourceId.startsWith('class:')||sourceId==='class'||['artificer','barbarian','bard','cleric','druid','fighter','monk','paladin','ranger','rogue','sorcerer','warlock','wizard'].includes(sourceId))return 'Class';return 'Custom';};
export function ResourcesPanel({c,update}:{c:Character;update:(fn:(x:Character)=>Character)=>void}){
 const derived=classResources(c);const stored=[...c.resources];
 const classTracked=derived.map(r=>{const exact=stored.find(s=>s.id===r.id);if(exact)return exact;return stored.find(s=>s.name===r.name&&s.recharge===r.recharge&&s.max===r.max)??r;});
 const classIdentity=new Set(derived.map(r=>`${r.name}|${r.recharge}|${r.max}`));
 const custom=stored.filter(r=>!derived.some(d=>d.id===r.id)&&!classIdentity.has(`${r.name}|${r.recharge}|${r.max}`));
 const itemResources=c.items.filter(i=>i.charges).map(i=>({id:`item:${i.id}`,name:i.name,current:i.charges!.current,max:i.charges!.max,recharge:i.charges!.recharge as RechargeType,sourceId:i.id,description:i.description}));
 const resources=[...classTracked,...custom,...itemResources];
 const groups=['Species / Race','Class','Subclass','Feat','Background','Item','Shared','Custom'] as const;
 const grouped=groups.map(source=>({source,items:resources.filter(r=>sourceLabel(r.sourceId,r.id.startsWith('item:'))===source)})).filter(g=>g.items.length);
 return <section className="card"><div className="row"><div><h2>Resources</h2><p className="muted">Limited uses are grouped by origin. Recharge is explicit and item charges remain tied to the item.</p></div><span className="muted">{resources.length} tracked</span></div>{grouped.map(group=><div key={group.source}><h3>{group.source} <small>{group.items.length}</small></h3>{group.items.map(r=><ResourceRow key={r.id} resource={r} update={update} item={r.id.startsWith('item:')} />)}</div>)}{resources.length===0&&<p className="muted">No limited resources configured.</p>}</section>
}
function ResourceRow({resource:r,update,item}:{resource:Resource;update:(fn:(x:Character)=>Character)=>void;item:boolean}){const change=(delta:number)=>update(x=>{if(item)return {...x,items:x.items.map(i=>i.id===r.id.slice(5)&&i.charges?{...i,charges:{...i.charges,current:Math.max(0,Math.min(i.charges.max,i.charges.current+delta))}}:i)};if(r.unlimited)return x;const current=x.resources.find(y=>y.id===r.id)?.current??r.current;const next=Math.max(0,Math.min(r.max,current+delta));if(x.resources.some(y=>y.id===r.id))return {...x,resources:x.resources.map(y=>y.id===r.id?{...y,current:next}:y)};const legacy=x.resources.find(y=>y.name===r.name&&y.recharge===r.recharge&&y.max===r.max);if(legacy)return {...x,resources:x.resources.map(y=>y.id===legacy.id?{...r,current:next}:y)};return {...x,resources:[...x.resources,{...r,current:next}]}});const restore=()=>update(x=>{if(item)return {...x,items:x.items.map(i=>i.id===r.id.slice(5)&&i.charges?{...i,charges:{...i.charges,current:i.charges.max}}:i)};if(r.unlimited)return x;if(x.resources.some(y=>y.id===r.id))return {...x,resources:x.resources.map(y=>y.id===r.id?{...y,current:y.max}:y)};const legacy=x.resources.find(y=>y.name===r.name&&y.recharge===r.recharge&&y.max===r.max);if(legacy)return {...x,resources:x.resources.map(y=>y.id===legacy.id?{...r,current:r.max}:y)};return {...x,resources:[...x.resources,{...r,current:r.max}]}});return <article className="resource resource-row"><div className="row"><div><b>{r.name}</b><small>{r.unlimited?'Unlimited':`${sourceLabel(r.sourceId,item)} · ${rechargeLabel(r.recharge)}`}{r.description?` · ${r.description}`:''}</small></div><strong>{r.unlimited?'∞':`${r.current}/${r.max}`}</strong></div>{!r.unlimited&&<div className="hp-actions"><button disabled={r.current<=0} onClick={()=>change(-1)}>−</button><button disabled={r.current>=r.max} onClick={()=>change(1)}>+</button><button onClick={restore}>Restore</button></div>}</article>}
