import {useMemo,useState} from 'react';
import type {Character,Spell} from '../domain/types';
import {CLASSES} from '../domain/catalog';
import {setPrepared} from '../domain/rules/spellcasting';
import {maxPreparedSpells,spellAttackBonus,spellSaveDC} from '../domain/rules';
export function SpellsPanel({c,update,spells}:{c:Character;update:(fn:(x:Character)=>Character)=>void;spells:Spell[]}){
 const classId=c.classes[0]?.id??'';const def=CLASSES.find(x=>x.id===classId);const sc=c.spellcasting[classId]??{known:[],prepared:[],alwaysPrepared:[],spellbook:[],slots:{}};const model=def?.spellcasting??'none';
 const [tab,setTab]=useState<'prepared'|'known'|'spellbook'|'list'>(model==='spellbook'?'spellbook':model==='known'||model==='pact'?'known':'prepared');const [details,setDetails]=useState<Spell|null>(null);
 const limit=maxPreparedSpells(c,classId);const grouped=useMemo(()=>spells.reduce<Record<number,Spell[]>>((g,s)=>{(g[s.level]??=[]).push(s);return g},{}),[spells]);
 const togglePrepared=(id:string)=>update(x=>{const state=x.spellcasting[classId]??{known:[],prepared:[],alwaysPrepared:[],spellbook:[],slots:{}};return {...x,spellcasting:{...x.spellcasting,[classId]:setPrepared(state,id,!state.prepared.includes(id),maxPreparedSpells(x,classId))}}});
 const toggleList=(id:string)=>update(x=>{const state=x.spellcasting[classId]??{known:[],prepared:[],alwaysPrepared:[],spellbook:[],slots:{}};const key=model==='spellbook'?'spellbook':model==='known'||model==='pact'?'known':'prepared';if(key==='prepared')return {...x,spellcasting:{...x.spellcasting,[classId]:setPrepared(state,id,!state.prepared.includes(id),maxPreparedSpells(x,classId))}};const next=new Set(state[key]);next.has(id)?next.delete(id):next.add(id);return {...x,spellcasting:{...x.spellcasting,[classId]:{...state,[key]:[...next]}}}});
 const toggleSlot=(level:number,delta:number)=>update(x=>{const state=x.spellcasting[classId]??sc;const slot=state.slots[level];if(!slot)return x;return {...x,spellcasting:{...x.spellcasting,[classId]:{...state,slots:{...state.slots,[level]:{...slot,used:Math.max(0,Math.min(slot.max,slot.used+delta))}}}}}});
 const togglePact=(delta:number)=>update(x=>{const state=x.spellcasting[classId]??sc;const p=state.pactSlots;if(!p)return x;return {...x,spellcasting:{...x.spellcasting,[classId]:{...state,pactSlots:{...p,used:Math.max(0,Math.min(p.max,p.used+delta))}}}}});
 const spell=(id:string)=>spells.find(s=>s.id===id);const ownedIds=model==='spellbook'?sc.spellbook:model==='known'||model==='pact'?sc.known:sc.prepared;
 return <section className="card"><div className="row"><div><h2>Spells</h2><p className="muted">{c.classes[0]?.name??'Class'} · Save DC {spellSaveDC(c,classId)??'—'} · Attack {spellAttackBonus(c,classId)===null?'—':`+${spellAttackBonus(c,classId)}`}</p></div><div className="tabs">{(model==='prepared'||model==='spellbook')&&<button className={tab==='prepared'?'active':''} onClick={()=>setTab('prepared')}>Prepared</button>}{model==='known'&&<button className={tab==='known'?'active':''} onClick={()=>setTab('known')}>Known</button>}{model==='pact'&&<button className={tab==='known'?'active':''} onClick={()=>setTab('known')}>Known</button>}{model==='spellbook'&&<button className={tab==='spellbook'?'active':''} onClick={()=>setTab('spellbook')}>Spellbook</button>}<button className={tab==='list'?'active':''} onClick={()=>setTab('list')}>Class Spell List</button></div></div>
 <SlotTracker slots={sc.slots} pactSlots={sc.pactSlots} onSlot={toggleSlot} onPact={togglePact}/>
 {tab==='prepared'?<><h3>Always Prepared</h3>{sc.alwaysPrepared.map(id=><SpellRow key={id} spell={spell(id)} locked onInfo={setDetails}/>)}<h3>Prepared by You <small>{sc.prepared.length}/{limit}</small></h3>{sc.prepared.map(id=><SpellRow key={id} spell={spell(id)} active onClick={()=>togglePrepared(id)} onInfo={setDetails}/>)}</>:tab==='known'||tab==='spellbook'?<><h3>{model==='spellbook'?'Spellbook':'Known'} <small>{ownedIds.length}</small></h3>{ownedIds.length?ownedIds.map(id=><SpellRow key={id} spell={spell(id)} active onClick={()=>toggleList(id)} onInfo={setDetails}/>):<p className="muted">No spells yet. Add them from the class spell list.</p>}</>:Object.keys(grouped).sort((a,b)=>Number(a)-Number(b)).map(level=><div key={level}><h3>{level==='0'?'Cantrips':`Level ${level}`}</h3>{grouped[Number(level)].map(s=><SpellRow key={s.id} spell={s} active={ownedIds.includes(s.id)} onClick={()=>toggleList(s.id)} onInfo={setDetails}/>)}</div>)}{details&&<SpellModal spell={details} close={()=>setDetails(null)}/>}</section>
}
function SlotTracker({slots,pactSlots,onSlot,onPact}:{slots:Record<number,{max:number;used:number}>;pactSlots?:{max:number;used:number;level:number};onSlot:(level:number,delta:number)=>void;onPact:(delta:number)=>void}){const levels=Object.keys(slots).map(Number).sort((a,b)=>a-b);if(!levels.length&&!pactSlots)return null;return <div className="slot-tracker"><div className="row"><h3>Spell Slots</h3><span className="muted">Click −/+ to spend or restore</span></div>{levels.map(level=>{const s=slots[level];return <div className="resource" key={level}><div className="row"><b>Level {level}</b><span>{Math.max(0,s.max-s.used)}/{s.max}</span></div><div className="hp-actions"><button disabled={s.used>=s.max} onClick={()=>onSlot(level,1)}>−</button><button disabled={s.used<=0} onClick={()=>onSlot(level,-1)}>+</button></div></div>})}{pactSlots&&<div className="resource"><div className="row"><b>Pact Slots · Level {pactSlots.level}</b><span>{Math.max(0,pactSlots.max-pactSlots.used)}/{pactSlots.max}</span></div><div className="hp-actions"><button disabled={pactSlots.used>=pactSlots.max} onClick={()=>onPact(1)}>−</button><button disabled={pactSlots.used<=0} onClick={()=>onPact(-1)}>+</button></div></div>}</div>}
function SpellRow({spell,onClick,active,locked,onInfo}:{spell?:Spell;onClick?:()=>void;active?:boolean;locked?:boolean;onInfo:(spell:Spell)=>void}){if(!spell)return <p className="muted">Spell data unavailable.</p>;return <div className={`spell ${active?'selected':''}`}><button className="spell-main" onClick={()=>onInfo(spell)}><span><b>{spell.name}</b><small>{spell.school} · Level {spell.level}{spell.ritual?' · Ritual':''}{spell.concentration?' · Concentration':''}{spell.source?` · ${spell.source}`:''}</small></span></button>{locked?<i>Always prepared</i>:<button className="spell-action" onClick={onClick}>{active?'Remove':'Prepare'}</button>}</div>}
function SpellModal({spell,close}:{spell:Spell;close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="row"><div><span className="eyebrow">Level {spell.level} · {spell.school}</span><h2>{spell.name}</h2></div><button onClick={close}>×</button></div><div className="spell-meta"><span><b>Casting</b>{spell.castingTime??'—'}</span><span><b>Range</b>{spell.range??'—'}</span><span><b>Duration</b>{spell.duration??(spell.concentration?'Concentration':'—')}</span><span><b>Components</b>{spell.components?.join(', ')??'—'}</span></div><p className="feature-description">{spell.description??'Spell description not yet populated in the content catalog.'}</p>{spell.higherLevels&&<><h3>At Higher Levels</h3><p className="feature-description">{spell.higherLevels}</p></>}<p className="muted">Classes: {spell.classes.join(', ')}</p></div></div>}
