import type {BackgroundData,Skill} from '../types';
type B=BackgroundData&{id:string;skills:Skill[]};
export const BACKGROUNDS:B[]=[
{id:'acolyte',name:'Acolyte',skills:['insight','religion'],skillProficiencies:['Insight','Religion'],toolProficiencies:[],languages:['2 languages'],feature:'Shelter of the Faithful',description:'Fellow believers provide basic support and sanctuary, and you can secure religious assistance through your faith community.'},
{id:'charlatan',name:'Charlatan',skills:['deception','sleightOfHand'],skillProficiencies:['Deception','Sleight of Hand'],toolProficiencies:['Disguise kit','Forgery kit'],languages:[],feature:'False Identity',description:'You have a second identity with documentation, established acquaintances, and a disguise that supports the identity.'},
{id:'criminal',name:'Criminal',skills:['deception','stealth'],skillProficiencies:['Deception','Stealth'],toolProficiencies:["Thieves' tools","Gaming set"],languages:[],feature:'Criminal Contact',description:'You have a reliable contact who acts as your liaison to the criminal network.'},
{id:'entertainer',name:'Entertainer',skills:['acrobatics','performance'],skillProficiencies:['Acrobatics','Performance'],toolProficiencies:['Disguise kit','One musical instrument'],languages:[],feature:'By Popular Demand',description:'You can find a place to perform and receive food and lodging in exchange for performances.'},
{id:'folk-hero',name:'Folk Hero',skills:['animalHandling','survival'],skillProficiencies:['Animal Handling','Survival'],toolProficiencies:["Artisan's tools","Vehicles (land)"],languages:[],feature:'Rustic Hospitality',description:'Common folk support you and can provide shelter, food, and basic assistance.'},
{id:'guild-artisan',name:'Guild Artisan',skills:['insight','persuasion'],skillProficiencies:['Insight','Persuasion'],toolProficiencies:["Artisan's tools"],languages:['1 language'],feature:'Guild Membership',description:'You belong to an artisans’ guild and can call on guild support and contacts.'},
{id:'hermit',name:'Hermit',skills:['medicine','religion'],skillProficiencies:['Medicine','Religion'],toolProficiencies:['Herbalism kit'],languages:['1 language'],feature:'Discovery',description:'You possess an important discovery or revelation; its nature is determined by the character and DM.'},
{id:'noble',name:'Noble',skills:['history','persuasion'],skillProficiencies:['History','Persuasion'],toolProficiencies:['Gaming set'],languages:['1 language'],feature:'Position of Privilege',description:'You are welcome in high society, can secure audiences with nobles, and receive basic social deference.'},
{id:'outlander',name:'Outlander',skills:['athletics','survival'],skillProficiencies:['Athletics','Survival'],toolProficiencies:['One musical instrument'],languages:['1 language'],feature:'Wanderer',description:'You have an excellent memory for maps and geography and can find food and fresh water for yourself and up to five others each day when the land provides it.'},
{id:'sage',name:'Sage',skills:['arcana','history'],skillProficiencies:['Arcana','History'],toolProficiencies:[],languages:['2 languages'],feature:'Researcher',description:'When you do not know information, you usually know where and from whom it can be obtained.'},
{id:'sailor',name:'Sailor',skills:['athletics','perception'],skillProficiencies:['Athletics','Perception'],toolProficiencies:["Navigator's tools","Vehicles (water)"],languages:[],feature:'Ship’s Passage',description:'You can secure free passage on sailing ships for yourself and companions when you render a service for the crew.'},
{id:'soldier',name:'Soldier',skills:['athletics','intimidation'],skillProficiencies:['Athletics','Intimidation'],toolProficiencies:['Gaming set','Vehicles (land)'],languages:[],feature:'Military Rank',description:'You hold a military rank and can invoke it to influence soldiers and obtain basic assistance where appropriate.'},
{id:'urchin',name:'Urchin',skills:['sleightOfHand','stealth'],skillProficiencies:['Sleight of Hand','Stealth'],toolProficiencies:['Disguise kit',"Thieves' tools"],languages:[],feature:'City Secrets',description:'You know secret urban routes and shortcuts, allowing you to travel through cities roughly twice as fast.'}
];
