/**
 * Rule-bearing descriptions for class features.  Content is kept separate from
 * the progression table so progression and mechanics cannot drift independently.
 * Source: Player's Handbook (2014), Italian edition supplied with the project.
 */
export const CLASS_FEATURE_DETAILS:Record<string,{description:string;activation?:'action'|'bonus-action'|'reaction'|'passive'|'special';}>={
 'paladin:divine-sense':{activation:'action',description:'Come azione, puoi aprire i tuoi sensi alla presenza del bene e del male. Fino alla fine del tuo prossimo turno, conosci la posizione di qualsiasi celestiale, immondo o non morto entro 18 metri da te che non sia dietro copertura totale, e conosci il tipo di creatura, ma non la sua identità. Con lo stesso senso rilevi anche la presenza di qualsiasi luogo o oggetto consacrato o dissacrato entro 18 metri. Puoi usare questo privilegio un numero di volte pari a 1 + il tuo modificatore di Carisma (minimo una volta) e recuperi tutti gli utilizzi al termine di un riposo lungo.'},
 'paladin:lay-on-hands':{activation:'action',description:'Possiedi una riserva di potere curativo che si ripristina al termine di un riposo lungo. La riserva contiene un numero di punti ferita pari a 5 volte il tuo livello da paladino. Come azione, puoi toccare una creatura e spendere punti dalla riserva per ripristinare un numero di punti ferita fino all’ammontare rimasto. In alternativa, puoi spendere 5 punti per neutralizzare un veleno o curare una malattia che affligge il bersaglio; puoi neutralizzare più veleni o malattie con una singola Imposizione delle Mani spendendo 5 punti per ciascuno. Questo privilegio non ha effetto su non morti e costrutti.'},
 'paladin:fighting-style':{activation:'passive',description:'Al 2° livello scegli uno stile di combattimento tra le opzioni disponibili per il paladino. Non puoi scegliere di nuovo uno stile già posseduto, anche se in seguito ottieni nuovamente un’opzione di stile di combattimento.'},
 'paladin:spellcasting':{activation:'special',description:'Al 2° livello ottieni la capacità di lanciare incantesimi da paladino. Carisma è la tua caratteristica da incantatore. La CD del tiro salvezza dei tuoi incantesimi è 8 + bonus di competenza + modificatore di Carisma; il modificatore di attacco con incantesimo è bonus di competenza + modificatore di Carisma. Prepari la lista secondo le regole del paladino e puoi usare un simbolo sacro come focus da incantatore.'},
 'paladin:divine-smite':{activation:'special',description:'Quando colpisci una creatura con un attacco con un’arma da mischia, puoi spendere uno slot incantesimo per infliggere danni radiosi extra. I danni sono 2d8 per uno slot di 1° livello, più 1d8 per ogni livello dello slot superiore al 1°, fino a un massimo di 5d8. I danni extra aumentano di 1d8 se il bersaglio è un non morto o un immondo.'},
 'paladin:divine-health':{activation:'passive',description:'La magia divina che fluisce attraverso di te ti rende immune alle malattie.'},
 'paladin:sacred-oath':{activation:'special',description:'Al 3° livello pronunci un giuramento sacro. Scegli un Giuramento Sacro; esso ti conferisce privilegi al 3°, 7°, 15° e 20° livello, oltre a incantesimi di giuramento e opzioni di Incanalare Divinità.'},
 'paladin:extra-attack':{activation:'passive',description:'A partire dal 5° livello, puoi attaccare due volte, anziché una, ogni volta che effettui l’azione Attacco durante il tuo turno.'},
 'paladin:aura-of-protection':{activation:'passive',description:'Quando tu o una creatura amica entro 3 metri da te effettuate un tiro salvezza, la creatura ottiene un bonus al tiro pari al tuo modificatore di Carisma (minimo +1). Devi essere cosciente per conferire questo bonus. Al 18° livello la gittata dell’aura aumenta a 9 metri.'},
 'paladin:aura-of-courage':{activation:'passive',description:'Tu e le creature amiche entro 3 metri da te non potete essere spaventati finché sei cosciente. Al 18° livello la gittata dell’aura aumenta a 9 metri.'},
 'paladin:improved-divine-smite':{activation:'passive',description:'Ogni volta che colpisci una creatura con un’arma da mischia, il bersaglio subisce 1d8 danni radiosi extra. Se usi Punizione Divina con quell’attacco, questi danni si aggiungono ai danni extra della Punizione Divina.'},
 'paladin:cleansing-touch':{activation:'action',description:'Come azione, puoi terminare un incantesimo su te stesso o su una creatura consenziente che stai toccando. Puoi usare questo privilegio un numero di volte pari al tuo modificatore di Carisma (minimo una volta) e recuperi tutti gli utilizzi al termine di un riposo lungo.'},
 'paladin:aura-range':{activation:'passive',description:'A partire dal 18° livello, la gittata delle tue Aure aumenta da 3 metri a 9 metri.'}
};
