/**
 * Rule-bearing descriptions for class features.
 * Source: Player's Handbook (2014) and Tasha's Cauldron of Everything,
 * using the Italian source PDFs supplied with the project.
 */
export const CLASS_FEATURE_DETAILS:Record<string,{description:string;activation?:'action'|'bonus-action'|'reaction'|'passive'|'special';}>={
 'paladin:divine-sense':{activation:'action',description:'Come azione, puoi aprire i tuoi sensi alla presenza del bene e del male. Fino alla fine del tuo prossimo turno, conosci la posizione di qualsiasi celestiale, immondo o non morto entro 18 metri da te che non sia dietro copertura totale, e conosci il tipo di creatura, ma non la sua identità. Con lo stesso senso rilevi anche la presenza di qualsiasi luogo o oggetto consacrato o dissacrato entro 18 metri. Puoi usare questo privilegio un numero di volte pari a 1 + il tuo modificatore di Carisma (minimo una volta) e recuperi tutti gli utilizzi al termine di un riposo lungo.'},
 'paladin:lay-on-hands':{activation:'action',description:'Possiedi una riserva di potere curativo che si ripristina al termine di un riposo lungo. La riserva contiene un numero di punti ferita pari a 5 volte il tuo livello da paladino. Come azione, puoi toccare una creatura e spendere punti dalla riserva per ripristinare un numero di punti ferita fino all’ammontare rimasto. In alternativa, puoi spendere 5 punti per neutralizzare un veleno o curare una malattia che affligge il bersaglio; puoi neutralizzare più veleni o malattie con una singola Imposizione delle Mani spendendo 5 punti per ciascuno. Questo privilegio non ha effetto su non morti e costrutti.'},
 'paladin:fighting-style':{activation:'passive',description:'Al 2° livello scegli uno stile di combattimento tra le opzioni disponibili per il paladino. Non puoi scegliere di nuovo uno stile già posseduto, anche se in seguito ottieni nuovamente un’opzione di stile di combattimento.'},
 'paladin:spellcasting':{activation:'special',description:'Al 2° livello ottieni la capacità di lanciare incantesimi da paladino. Carisma è la tua caratteristica da incantatore. La CD del tiro salvezza dei tuoi incantesimi è 8 + bonus di competenza + modificatore di Carisma; il modificatore di attacco con incantesimo è bonus di competenza + modificatore di Carisma. Prepari la lista secondo le regole del paladino e puoi usare un simbolo sacro come focus da incantatore.'},
 'paladin:divine-smite':{activation:'special',description:'Quando colpisci una creatura con un attacco con un’arma da mischia, puoi spendere uno slot incantesimo per infliggere danni radiosi extra. I danni sono 2d8 per uno slot di 1° livello, più 1d8 per ogni livello dello slot superiore al 1°, fino a un massimo di 5d8. I danni extra aumentano di 1d8 se il bersaglio è un non morto o un immondo.'},
 'paladin:divine-health':{activation:'passive',description:'La magia divina che fluisce attraverso di te ti rende immune alle malattie.'},
 'paladin:sacred-oath':{activation:'special',description:'Al 3° livello pronunci un giuramento sacro. Scegli un Giuramento Sacro; esso ti conferisce privilegi al 3°, 7°, 15° e 20° livello, oltre a incantesimi di giuramento e opzioni di Incanalare Divinità.'},
 'paladin:extra-attack':{activation:'passive',description:'A partire dal 5° livello, puoi attaccare due volte, anziché una, ogni volta che effettui l’azione Attacco durante il tuo turno.'},
 'paladin:aura-of-protection':{activation:'passive',description:'Quando tu o una creatura amica entro 3 metri da te effettuate un tiro salvezza, la creatura ottiene un bonus al tiro pari al tuo modificatore di Carisma (minimo +1). Devi essere cosciente per conferire questo bonus. Al 18° livello la gittata dell’aura aumenta a 9 metri.'},
 'paladin:aura-of-courage':{activation:'passive',description:'Tu e le creature amiche entro 3 metri da te non potete essere spaventati finché sei cosciente. Al 18° livello la gittata dell’aura aumenta a 9 metri.'},
 'paladin:improved-divine-smite':{activation:'passive',description:'Ogni volta che colpisci una creatura con un’arma da mischia, il bersaglio subisce 1d8 danni radiosi extra.'},
 'paladin:cleansing-touch':{activation:'action',description:'Come azione, puoi terminare un incantesimo su te stesso o su una creatura consenziente che stai toccando. Puoi usare questo privilegio un numero di volte pari al tuo modificatore di Carisma (minimo una volta) e recuperi tutti gli utilizzi al termine di un riposo lungo.'},
 'paladin:aura-range':{activation:'passive',description:'A partire dal 18° livello, la gittata delle tue Aure aumenta da 3 metri a 9 metri.'},
 'artificer:magical-tinkering':{activation:'action',description:'Con gli arnesi da scasso o gli strumenti da artigiano in mano, con un’azione tocchi un oggetto Minuscolo non magico e gli conferisci una proprietà magica: luce intensa entro 1,5 metri e fioca per altri 1,5 metri; un messaggio registrato udibile fino a 3 metri quando viene toccato; un odore o suono non verbale continuo percepibile fino a 3 metri; oppure un effetto visivo statico, inclusi testo fino a 25 parole. La proprietà dura indefinitamente finché non la interrompi. Puoi avere un numero di oggetti infusi pari al tuo modificatore di Intelligenza (minimo 1) e ogni oggetto può avere una sola proprietà.'},
 'artificer:spellcasting':{activation:'special',description:'L’artefice lancia incantesimi attraverso i propri strumenti e oggetti. Intelligenza è la caratteristica da incantatore; gli strumenti da artigiano o gli arnesi da scasso possono fungere da focus secondo le regole del privilegio.'},
 'artificer:infuse-item':{activation:'special',description:'Al termine di un riposo lungo puoi toccare oggetti non magici e infonderli con una delle infusioni che conosci, rispettando il limite di oggetti indicato dalla progressione dell’artefice. Un’infusione può trovarsi in un solo oggetto alla volta e un oggetto non può contenere più di un’infusione. L’infusione termina se superi il limite o sostituisci la conoscenza dell’infusione; alla morte dell’artefice svanisce dopo un numero di giorni pari al modificatore di Intelligenza, minimo 1.'},
 'artificer:artificer-specialist':{activation:'special',description:'Al 3° livello scegli una Specializzazione da Artefice: Alchimista, Armaiolo, Artigliere o Fabbro da Battaglia. La specializzazione conferisce privilegi al 3°, 5°, 9° e 15° livello.'},
 'artificer:right-tool-for-the-job':{activation:'special',description:'Con gli arnesi da scasso o gli strumenti da artigiano puoi creare magicamente, in uno spazio libero entro 1,5 metri, un set di strumenti da artigiano. La creazione richiede 1 ora di lavoro ininterrotto e gli strumenti non sono magici; svaniscono quando usi nuovamente il privilegio.'},
 'artificer:tool-expertise':{activation:'passive',description:'Il tuo bonus di competenza viene raddoppiato per ogni prova di caratteristica che effettui usando la competenza con uno strumento.'},
 'artificer:flash-of-genius':{activation:'reaction',description:'Quando tu o un’altra creatura entro 9 metri effettuate una prova di caratteristica o un tiro salvezza, puoi usare la tua reazione per aggiungere il tuo modificatore di Intelligenza al tiro. Puoi usare questo privilegio un numero di volte pari al tuo modificatore di Intelligenza (minimo una volta) e recuperi tutti gli utilizzi al termine di un riposo lungo.'},
 'artificer:magic-item-adept':{activation:'passive',description:'Diventi più abile nel creare e usare oggetti magici: puoi sintonizzarti con un massimo di quattro oggetti magici contemporaneamente e puoi ignorare metà del tempo e del costo in oro per creare un oggetto magico comune o non comune.'},
 'artificer:spell-storing-item':{activation:'action',description:'Puoi custodire un incantesimo di 1° o 2° livello dalla tua lista da artefice in un oggetto che tocchi. L’incantesimo deve avere un tempo di lancio di 1 azione e bersagliare una singola creatura. Una creatura che tiene l’oggetto può usare un’azione per produrre l’effetto dell’incantesimo usando il modificatore da incantatore dell’artefice. L’effetto rimane finché viene usato il numero di volte previsto dal privilegio o finché usi nuovamente il privilegio su un altro oggetto.'},
 'artificer:magic-item-savant':{activation:'passive',description:'Puoi sintonizzarti con un massimo di cinque oggetti magici contemporaneamente e ignori i requisiti di classe, razza, incantesimo e livello per sintonizzarti o usare un oggetto magico.'},
 'artificer:magic-item-master':{activation:'passive',description:'Puoi sintonizzarti con un massimo di sei oggetti magici contemporaneamente.'},
 'artificer:soul-of-artifice':{activation:'reaction',description:'Ottieni un bonus di +1 a tutti i tiri salvezza per ogni oggetto magico con cui sei in sintonia. Se vieni ridotto a 0 punti ferita ma sei ancora in vita, puoi usare la reazione per terminare una delle tue infusioni e scendere invece a 1 punto ferita.'},
};
