import type {Feature} from '../types';
const f=(classId:string,level:number,id:string,name:string):Feature=>({id:`${classId}:${id}`,name,source:'class',level});
export const CLASS_FEATURES:Record<string,Feature[]>={
barbarian:[f('barbarian',1,'rage','Rage'),f('barbarian',1,'unarmored-defense','Unarmored Defense'),f('barbarian',2,'reckless-attack','Reckless Attack'),f('barbarian',2,'danger-sense','Danger Sense'),f('barbarian',3,'primal-path','Primal Path'),f('barbarian',4,'asi','Ability Score Improvement'),f('barbarian',5,'extra-attack','Extra Attack'),f('barbarian',5,'fast-movement','Fast Movement'),f('barbarian',7,'feral-instinct','Feral Instinct'),f('barbarian',9,'brutal-critical','Brutal Critical'),f('barbarian',11,'relentless-rage','Relentless Rage'),f('barbarian',15,'persistent-rage','Persistent Rage'),f('barbarian',18,'indomitable-might','Indomitable Might'),f('barbarian',20,'primal-champion','Primal Champion')],
bard:[f('bard',1,'spellcasting','Spellcasting'),f('bard',1,'bardic-inspiration','Bardic Inspiration'),f('bard',2,'jack-of-all-trades','Jack of All Trades'),f('bard',2,'song-of-rest','Song of Rest'),f('bard',3,'bard-college','Bard College'),f('bard',3,'expertise','Expertise'),f('bard',5,'font-of-inspiration','Font of Inspiration'),f('bard',6,'countercharm','Countercharm'),f('bard',10,'magical-secrets','Magical Secrets'),f('bard',20,'superior-inspiration','Superior Inspiration')],
cleric:[f('cleric',1,'spellcasting','Spellcasting'),f('cleric',1,'divine-domain','Divine Domain'),f('cleric',2,'channel-divinity','Channel Divinity'),f('cleric',5,'destroy-undead','Destroy Undead'),f('cleric',10,'divine-intervention','Divine Intervention'),f('cleric',20,'divine-intervention-improvement','Divine Intervention Improvement')],
druid:[f('druid',1,'druidic','Druidic'),f('druid',1,'spellcasting','Spellcasting'),f('druid',2,'wild-shape','Wild Shape'),f('druid',2,'druid-circle','Druid Circle'),f('druid',18,'beast-spells','Beast Spells'),f('druid',20,'archdruid','Archdruid')],
fighter:[f('fighter',1,'fighting-style','Fighting Style'),f('fighter',1,'second-wind','Second Wind'),f('fighter',2,'action-surge','Action Surge'),f('fighter',3,'martial-archetype','Martial Archetype'),f('fighter',5,'extra-attack','Extra Attack'),f('fighter',9,'indomitable','Indomitable'),f('fighter',20,'extra-attack-3','Extra Attack (3)')],
monk:[f('monk',1,'unarmored-defense','Unarmored Defense'),f('monk',1,'martial-arts','Martial Arts'),f('monk',2,'ki','Ki'),f('monk',2,'unarmored-movement','Unarmored Movement'),f('monk',3,'monastic-tradition','Monastic Tradition'),f('monk',3,'deflect-missiles','Deflect Missiles'),f('monk',5,'extra-attack','Extra Attack'),f('monk',5,'stunning-strike','Stunning Strike'),f('monk',7,'evasion','Evasion'),f('monk',7,'stillness-of-mind','Stillness of Mind'),f('monk',14,'diamond-soul','Diamond Soul'),f('monk',18,'empty-body','Empty Body'),f('monk',20,'perfect-self','Perfect Self')],
paladin:[f('paladin',1,'divine-sense','Divine Sense'),f('paladin',1,'lay-on-hands','Lay on Hands'),f('paladin',2,'fighting-style','Fighting Style'),f('paladin',2,'spellcasting','Spellcasting'),f('paladin',2,'divine-smite','Divine Smite'),f('paladin',3,'sacred-oath','Sacred Oath'),f('paladin',3,'divine-health','Divine Health'),f('paladin',5,'extra-attack','Extra Attack'),f('paladin',6,'aura-of-protection','Aura of Protection'),f('paladin',10,'aura-of-courage','Aura of Courage'),f('paladin',11,'improved-divine-smite','Improved Divine Smite'),f('paladin',14,'cleansing-touch','Cleansing Touch')],
ranger:[f('ranger',1,'favored-enemy','Favored Enemy'),f('ranger',1,'natural-explorer','Natural Explorer'),f('ranger',2,'fighting-style','Fighting Style'),f('ranger',2,'spellcasting','Spellcasting'),f('ranger',3,'ranger-archetype','Ranger Archetype'),f('ranger',3,'primeval-awareness','Primeval Awareness'),f('ranger',5,'extra-attack','Extra Attack'),f('ranger',8,'land-stride','Land’s Stride'),f('ranger',10,'hide-in-plain-sight','Hide in Plain Sight'),f('ranger',14,'vanish','Vanish'),f('ranger',18,'feral-senses','Feral Senses'),f('ranger',20,'foe-slayer','Foe Slayer')],
rogue:[f('rogue',1,'expertise','Expertise'),f('rogue',1,'sneak-attack','Sneak Attack'),f('rogue',1,'thieves-cant','Thieves’ Cant'),f('rogue',2,'cunning-action','Cunning Action'),f('rogue',3,'roguish-archetype','Roguish Archetype'),f('rogue',5,'uncanny-dodge','Uncanny Dodge'),f('rogue',7,'evasion','Evasion'),f('rogue',11,'reliable-talent','Reliable Talent'),f('rogue',15,'slippery-mind','Slippery Mind'),f('rogue',18,'elusive','Elusive'),f('rogue',20,'stroke-of-luck','Stroke of Luck')],
sorcerer:[f('sorcerer',1,'spellcasting','Spellcasting'),f('sorcerer',1,'sorcerous-origin','Sorcerous Origin'),f('sorcerer',2,'font-of-magic','Font of Magic'),f('sorcerer',3,'metamagic','Metamagic'),f('sorcerer',20,'sorcerous-restoration','Sorcerous Restoration')],
warlock:[f('warlock',1,'otherworldly-patron','Otherworldly Patron'),f('warlock',1,'pact-magic','Pact Magic'),f('warlock',2,'eldritch-invocations','Eldritch Invocations'),f('warlock',3,'pact-boon','Pact Boon'),f('warlock',11,'mystic-arcanum','Mystic Arcanum'),f('warlock',20,'eldritch-master','Eldritch Master')],
wizard:[f('wizard',1,'spellcasting','Spellcasting'),f('wizard',1,'arcane-recovery','Arcane Recovery'),f('wizard',2,'arcane-tradition','Arcane Tradition'),f('wizard',18,'spell-mastery','Spell Mastery'),f('wizard',20,'signature-spells','Signature Spells')],
artificer:[f('artificer',1,'magical-tinkering','Magical Tinkering'),f('artificer',1,'spellcasting','Spellcasting'),f('artificer',2,'infuse-item','Infuse Item'),f('artificer',3,'artificer-specialist','Artificer Specialist'),f('artificer',3,'right-tool-for-the-job','The Right Tool for the Job'),f('artificer',6,'tool-expertise','Tool Expertise'),f('artificer',7,'flash-of-genius','Flash of Genius'),f('artificer',10,'magic-item-adept','Magic Item Adept'),f('artificer',11,'spell-storing-item','Spell-Storing Item'),f('artificer',14,'magic-item-savant','Magic Item Savant'),f('artificer',18,'magic-item-master','Magic Item Master'),f('artificer',20,'soul-of-artifice','Soul of Artifice')]
};
