import type { Feature } from '../types';
import { CLASS_FEATURE_DETAILS } from './class-feature-details';

const f = (classId:string, level:number, id:string, name:string):Feature => {
  const d = CLASS_FEATURE_DETAILS[`${classId}:${id}`];
  return { id:`${classId}:${id}`, name, source:'class', level, description:d?.description, activation:d?.activation };
};
const asi = (classId:string, level:number) => f(classId, level, `asi-${level}`, `Ability Score Improvement (${level})`);

/** PHB 2014 class progression. Subclass-specific privileges are resolved separately. */
export const CLASS_FEATURES:Record<string,Feature[]>={
barbarian:[f('barbarian',1,'rage','Rage'),f('barbarian',1,'unarmored-defense','Unarmored Defense'),f('barbarian',2,'reckless-attack','Reckless Attack'),f('barbarian',2,'danger-sense','Danger Sense'),f('barbarian',3,'primal-path','Primal Path'),asi('barbarian',4),f('barbarian',5,'extra-attack','Extra Attack'),f('barbarian',5,'fast-movement','Fast Movement'),f('barbarian',7,'feral-instinct','Feral Instinct'),asi('barbarian',8),f('barbarian',9,'brutal-critical','Brutal Critical'),f('barbarian',11,'relentless-rage','Relentless Rage'),asi('barbarian',12),f('barbarian',13,'brutal-critical-2','Brutal Critical'),f('barbarian',15,'persistent-rage','Persistent Rage'),asi('barbarian',16),f('barbarian',17,'brutal-critical-3','Brutal Critical'),f('barbarian',18,'indomitable-might','Indomitable Might'),asi('barbarian',19),f('barbarian',20,'primal-champion','Primal Champion')],
bard:[f('bard',1,'spellcasting','Spellcasting'),f('bard',1,'bardic-inspiration','Bardic Inspiration'),f('bard',2,'jack-of-all-trades','Jack of All Trades'),f('bard',2,'song-of-rest','Song of Rest'),f('bard',3,'bard-college','Bard College'),f('bard',3,'expertise','Expertise'),asi('bard',4),f('bard',5,'font-of-inspiration','Font of Inspiration'),f('bard',6,'countercharm','Countercharm'),asi('bard',8),f('bard',10,'magical-secrets','Magical Secrets'),f('bard',10,'expertise-2','Expertise'),f('bard',13,'song-of-rest-3','Song of Rest'),f('bard',14,'magical-secrets-2','Magical Secrets'),asi('bard',12),asi('bard',16),f('bard',17,'song-of-rest-4','Song of Rest'),f('bard',18,'magical-secrets-3','Magical Secrets'),asi('bard',19),f('bard',20,'superior-inspiration','Superior Inspiration')],
cleric:[f('cleric',1,'spellcasting','Spellcasting'),f('cleric',1,'divine-domain','Divine Domain'),f('cleric',2,'channel-divinity','Channel Divinity'),asi('cleric',4),f('cleric',5,'destroy-undead','Destroy Undead'),f('cleric',6,'channel-divinity-2','Channel Divinity'),asi('cleric',8),f('cleric',8,'destroy-undead-2','Destroy Undead'),f('cleric',10,'divine-intervention','Divine Intervention'),f('cleric',11,'destroy-undead-3','Destroy Undead'),asi('cleric',12),f('cleric',14,'destroy-undead-4','Destroy Undead'),asi('cleric',16),f('cleric',17,'destroy-undead-5','Destroy Undead'),f('cleric',18,'channel-divinity-3','Channel Divinity'),asi('cleric',19),f('cleric',20,'divine-intervention-improvement','Improved Divine Intervention')],
druid:[f('druid',1,'druidic','Druidic'),f('druid',1,'spellcasting','Spellcasting'),f('druid',2,'wild-shape','Wild Shape'),f('druid',2,'druid-circle','Druid Circle'),asi('druid',4),asi('druid',8),asi('druid',12),asi('druid',16),f('druid',18,'timeless-body','Timeless Body'),f('druid',18,'beast-spells','Beast Spells'),asi('druid',19),f('druid',20,'archdruid','Archdruid')],
fighter:[f('fighter',1,'fighting-style','Fighting Style'),f('fighter',1,'second-wind','Second Wind'),f('fighter',2,'action-surge','Action Surge'),f('fighter',3,'martial-archetype','Martial Archetype'),asi('fighter',4),f('fighter',5,'extra-attack','Extra Attack'),asi('fighter',6),f('fighter',9,'indomitable','Indomitable'),f('fighter',11,'extra-attack-2','Extra Attack'),asi('fighter',12),f('fighter',13,'indomitable-2','Indomitable'),asi('fighter',14),asi('fighter',16),f('fighter',17,'action-surge-2','Action Surge'),f('fighter',17,'indomitable-3','Indomitable'),asi('fighter',19),f('fighter',20,'extra-attack-3','Extra Attack')],
monk:[f('monk',1,'unarmored-defense','Unarmored Defense'),f('monk',1,'martial-arts','Martial Arts'),f('monk',2,'ki','Ki'),f('monk',2,'unarmored-movement','Unarmored Movement'),f('monk',3,'monastic-tradition','Monastic Tradition'),asi('monk',4),f('monk',5,'extra-attack','Extra Attack'),f('monk',5,'stunning-strike','Stunning Strike'),f('monk',6,'ki-empowered-strikes','Ki-Empowered Strikes'),asi('monk',8),f('monk',10,'purity-of-body','Purity of Body'),asi('monk',12),f('monk',13,'tongue-of-sun-and-moon','Tongue of the Sun and Moon'),asi('monk',14),f('monk',14,'diamond-soul','Diamond Soul'),f('monk',15,'timeless-body','Timeless Body'),asi('monk',16),f('monk',18,'empty-body','Empty Body'),asi('monk',19),f('monk',20,'perfect-self','Perfect Self')],
paladin:[f('paladin',1,'divine-sense','Divine Sense'),f('paladin',1,'lay-on-hands','Lay on Hands'),f('paladin',2,'fighting-style','Fighting Style'),f('paladin',2,'spellcasting','Spellcasting'),f('paladin',2,'divine-smite','Divine Smite'),f('paladin',3,'divine-health','Divine Health'),f('paladin',3,'sacred-oath','Sacred Oath'),asi('paladin',4),f('paladin',5,'extra-attack','Extra Attack'),f('paladin',6,'aura-of-protection','Aura of Protection'),f('paladin',10,'aura-of-courage','Aura of Courage'),asi('paladin',8),f('paladin',11,'improved-divine-smite','Improved Divine Smite'),asi('paladin',12),f('paladin',14,'cleansing-touch','Cleansing Touch'),asi('paladin',16),f('paladin',18,'aura-range','Aura Range'),asi('paladin',19),f('paladin',20,'sacred-oath-capstone','Sacred Oath Capstone')],
ranger:[f('ranger',1,'favored-enemy','Favored Enemy'),f('ranger',1,'natural-explorer','Natural Explorer'),f('ranger',2,'fighting-style','Fighting Style'),f('ranger',2,'spellcasting','Spellcasting'),f('ranger',3,'ranger-archetype','Ranger Archetype'),asi('ranger',4),f('ranger',5,'extra-attack','Extra Attack'),f('ranger',8,'land-stride','Land Stride'),asi('ranger',8),f('ranger',10,'hide-in-plain-sight','Hide in Plain Sight'),asi('ranger',12),f('ranger',14,'vanish','Vanish'),asi('ranger',16),f('ranger',18,'feral-senses','Feral Senses'),asi('ranger',19),f('ranger',20,'foe-slayer','Foe Slayer')],
rogue:[f('rogue',1,'expertise','Expertise'),f('rogue',1,'sneak-attack','Sneak Attack'),f('rogue',1,'thieves-cant','Thieves’ Cant'),f('rogue',2,'cunning-action','Cunning Action'),f('rogue',3,'roguish-archetype','Roguish Archetype'),asi('rogue',4),f('rogue',5,'uncanny-dodge','Uncanny Dodge'),f('rogue',6,'expertise-2','Expertise'),asi('rogue',8),f('rogue',9,'archetype-feature','Roguish Archetype Feature'),f('rogue',11,'reliable-talent','Reliable Talent'),asi('rogue',10),f('rogue',13,'archetype-feature-13','Roguish Archetype Feature'),asi('rogue',12),f('rogue',14,'blindsense','Blindsense'),f('rogue',15,'slippery-mind','Slippery Mind'),asi('rogue',16),f('rogue',17,'archetype-feature-17','Roguish Archetype Feature'),asi('rogue',19),f('rogue',18,'elusive','Elusive'),f('rogue',20,'stroke-of-luck','Stroke of Luck')],
sorcerer:[f('sorcerer',1,'spellcasting','Spellcasting'),f('sorcerer',1,'sorcerous-origin','Sorcerous Origin'),f('sorcerer',2,'font-of-magic','Font of Magic'),f('sorcerer',3,'metamagic','Metamagic'),asi('sorcerer',4),f('sorcerer',5,'metamagic-2','Metamagic'),asi('sorcerer',8),f('sorcerer',10,'metamagic-3','Metamagic'),asi('sorcerer',12),asi('sorcerer',16),asi('sorcerer',19),f('sorcerer',20,'sorcerous-restoration','Sorcerous Restoration')],
warlock:[f('warlock',1,'otherworldly-patron','Otherworldly Patron'),f('warlock',1,'pact-magic','Pact Magic'),f('warlock',2,'eldritch-invocations','Eldritch Invocations'),f('warlock',3,'pact-boon','Pact Boon'),asi('warlock',4),asi('warlock',8),f('warlock',9,'mystic-arcanum-5','Mystic Arcanum (5th level)'),asi('warlock',12),f('warlock',11,'mystic-arcanum-6','Mystic Arcanum (6th level)'),f('warlock',13,'mystic-arcanum-7','Mystic Arcanum (7th level)'),asi('warlock',16),f('warlock',15,'mystic-arcanum-8','Mystic Arcanum (8th level)'),asi('warlock',19),f('warlock',20,'eldritch-master','Eldritch Master')],
wizard:[f('wizard',1,'spellcasting','Spellcasting'),f('wizard',1,'arcane-recovery','Arcane Recovery'),f('wizard',2,'arcane-tradition','Arcane Tradition'),asi('wizard',4),f('wizard',5,'spell-mastery-prep','Spellcasting Progression'),asi('wizard',8),asi('wizard',12),f('wizard',18,'spell-mastery','Spell Mastery'),asi('wizard',16),f('wizard',20,'signature-spells','Signature Spells'),asi('wizard',19)],
artificer:[f('artificer',1,'magical-tinkering','Magical Tinkering'),f('artificer',1,'spellcasting','Spellcasting'),f('artificer',2,'infuse-item','Infuse Item'),f('artificer',3,'artificer-specialist','Artificer Specialist'),f('artificer',3,'right-tool-for-the-job','The Right Tool for the Job'),asi('artificer',4),f('artificer',5,'artificer-specialist-5','Artificer Specialist Feature'),f('artificer',6,'tool-expertise','Tool Expertise'),f('artificer',7,'flash-of-genius','Flash of Genius'),asi('artificer',8),f('artificer',9,'artificer-specialist-9','Artificer Specialist Feature'),f('artificer',10,'magic-item-adept','Magic Item Adept'),f('artificer',11,'spell-storing-item','Spell-Storing Item'),asi('artificer',12),f('artificer',14,'magic-item-savant','Magic Item Savant'),f('artificer',15,'artificer-specialist-15','Artificer Specialist Feature'),asi('artificer',16),f('artificer',18,'magic-item-master','Magic Item Master'),asi('artificer',19),f('artificer',20,'soul-of-artifice','Soul of Artifice')]
};