import type {Feature} from '../types';
import type {SubclassFeature} from './subclassFeatures';

const f=(id:string,name:string,subclassId:string,level:number,description:string):SubclassFeature=>({id,name,subclassId,level,source:'subclass',description});

/** Bulk canonical milestone catalog for Xanathar's and Tasha's subclasses. */
export const EXPANSION_SUBCLASS_FEATURES:SubclassFeature[]=[
// Barbarian — Xanathar
f('barbarian.ancestral-guardian.ancestral-protectors','Ancestral Protectors','barbarian.ancestral-guardian',3,'While raging, the first creature you hit on your turn has disadvantage on attacks against creatures other than you, and those creatures gain resistance to its damage as specified.'),
f('barbarian.ancestral-guardian.spirit-shield','Spirit Shield','barbarian.ancestral-guardian',6,'While raging, you can use your reaction to reduce damage dealt to another creature within 30 feet.'),
f('barbarian.ancestral-guardian.consult-spirits','Consult the Spirits','barbarian.ancestral-guardian',10,'You can cast augury or clairvoyance as specified by the feature.'),
f('barbarian.ancestral-guardian.vengful-ancestors','Vengeful Ancestors','barbarian.ancestral-guardian',14,'Spirit Shield can redirect prevented damage back to the attacker.'),
f('barbarian.storm-herald.storm-aura','Storm Aura','barbarian.storm-herald',3,'While raging, you emanate an aura whose effect depends on the chosen environment.'),
f('barbarian.storm-herald.storm-soul','Storm Soul','barbarian.storm-herald',6,'You gain a permanent environmental benefit and a benefit while raging based on your storm environment.'),
f('barbarian.storm-herald.shielding-storm','Shielding Storm','barbarian.storm-herald',10,'Creatures of your choice in your Storm Aura gain the resistance granted by your Storm Soul.'),
f('barbarian.storm-herald.raging-storm','Raging Storm','barbarian.storm-herald',14,'Your storm environment gains its listed high-level effect.'),
f('barbarian.zealot.fanatic-focus','Divine Fury','barbarian.zealot',3,'While raging, the first creature you hit on each of your turns takes extra radiant or necrotic damage.'),
f('barbarian.zealot.warrior-of-the-gods','Warrior of the Gods','barbarian.zealot',3,'Spells that restore you to life require no material components when cast on you, subject to the feature.'),
f('barbarian.zealot.zealous-presence','Zealous Presence','barbarian.zealot',10,'As a bonus action, you can grant creatures of your choice advantage on attack rolls and saving throws until your next turn.'),
f('barbarian.zealot.rage-beyond-death','Rage Beyond Death','barbarian.zealot',14,'While raging, dropping to 0 hit points does not knock you unconscious, subject to the feature limits.'),
// Barbarian — Tasha
f('barbarian.beast.form-of-the-beast','Form of the Beast','barbarian.beast',3,'When you rage, you manifest a natural weapon of your choice from the forms provided.'),
f('barbarian.beast.bestial-soul','Bestial Soul','barbarian.beast',6,'Your natural weapons count as magical and you gain climbing, swimming, or jumping adaptations.'),
f('barbarian.beast.infectious-fury','Infectious Fury','barbarian.beast',10,'When you damage a creature with your natural weapons, you can force a saving throw that can cause psychic damage or an attack against another creature.'),
f('barbarian.beast.call-the-hunt','Call the Hunt','barbarian.beast',14,'You can grant allies extra damage while raging after using the feature, gaining benefits based on the number of creatures affected.'),
f('barbarian.wild-magic.wild-magic-rage','Magic Awareness','barbarian.wild-magic',3,'You can sense the presence of magic within a limited range as a bonus action.'),
f('barbarian.wild-magic.wild-surge','Wild Surge','barbarian.wild-magic',3,'Entering a rage can trigger a random magical effect from the Wild Surge table.'),
f('barbarian.wild-magic.unstable-backlash','Bolstering Magic','barbarian.wild-magic',6,'You can empower yourself or another creature with a limited bonus to attack rolls, ability checks, or spell slot recovery.'),
f('barbarian.wild-magic.unstable-backlash-10','Unstable Backlash','barbarian.wild-magic',10,'When you take damage or fail a saving throw while raging, you can use your reaction to trigger another Wild Surge effect.'),
f('barbarian.wild-magic.controlled-surge','Controlled Surge','barbarian.wild-magic',14,'You can roll twice on the Wild Surge table and choose which effect occurs.'),
// Bard — Xanathar/Tasha
f('bard.whispers.psychic-blades','Psychic Blades','bard.whispers',3,'You can expend Bardic Inspiration when you hit with a weapon attack to deal extra psychic damage.'),
f('bard.whispers.words-of-terror','Words of Terror','bard.whispers',3,'You can frighten a humanoid by speaking privately for a minute.'),
f('bard.whispers.mantle-of-whispers','Mantle of Whispers','bard.whispers',6,'When a humanoid dies near you, you can capture its shadow and assume its appearance for a limited time.'),
f('bard.whispers.shadow-lore','Shadow Lore','bard.whispers',14,'You can weave a magical whisper that charms a creature and influences its behavior.'),
f('bard.glamour.mantle-of-inspiration','Mantle of Inspiration','bard.glamour',3,'You can expend Bardic Inspiration to grant temporary hit points and allow affected creatures to move without provoking opportunity attacks.'),
f('bard.glamour.enthalling-performance','Enthralling Performance','bard.glamour',3,'You can charm humanoids that watch and listen to your performance.'),
f('bard.glamour.mantle-of-majesty','Mantle of Majesty','bard.glamour',6,'You can cast command as a bonus action and gain a supernatural appearance for the duration.'),
f('bard.glamour.unbreakable-majesty','Unbreakable Majesty','bard.glamour',14,'You can assume a majestic presence that can impose disadvantage on attacks against you and charm or frighten creatures as specified.'),
f('bard.swords.bonus-proficiencies','Bonus Proficiencies','bard.swords',3,'You gain proficiency with medium armor and the selected weapon proficiencies specified by the college.'),
f('bard.swords.fighting-style','Fighting Style','bard.swords',3,'You adopt one Fighting Style available to the College of Swords.'),
f('bard.swords.blade-flourish','Blade Flourish','bard.swords',3,'When you use an Attack action, you can spend Bardic Inspiration to add a flourish to a weapon attack.'),
f('bard.swords.extra-attack','Extra Attack','bard.swords',6,'You can attack twice whenever you take the Attack action.'),
f('bard.swords.master-flourish','Master’s Flourish','bard.swords',14,'When you use Blade Flourish, you can roll a d6 instead of expending Bardic Inspiration.'),
f('bard.eloquence.silver-tongue','Silver Tongue','bard.eloquence',3,'Whenever you make a Charisma (Persuasion) or Charisma (Deception) check, a d20 roll of 9 or lower counts as 10.'),
f('bard.eloquence.unsettling-words','Unsettling Words','bard.eloquence',3,'You can expend Bardic Inspiration as a bonus action to subtract the die from a creature’s next saving throw before your next turn.'),
f('bard.eloquence.universal-speech','Universal Speech','bard.eloquence',6,'You can cause a number of creatures to understand you regardless of language for a limited duration.'),
f('bard.eloquence.infectious-inspiration','Infectious Inspiration','bard.eloquence',14,'When a creature succeeds using your Bardic Inspiration, you can inspire another creature as specified.'),
f('bard.creation.mote-of-potential','Mote of Potential','bard.creation',3,'Bardic Inspiration creates a mote that adds an additional effect when the die is used.'),
f('bard.creation.performance-of-creation','Performance of Creation','bard.creation',3,'You can magically create a nonmagical item of limited value and duration through performance.'),
f('bard.creation.animating-performance','Animating Performance','bard.creation',6,'You can animate a Large or smaller nonmagical item into a Dancing Item.'),
f('bard.creation.creative-crescendo','Creative Crescendo','bard.creation',14,'You can create more than one item with Performance of Creation and increase its value and duration as specified.'),
// Cleric — Xanathar/Tasha
f('cleric.forge.blessing-of-the-forge','Blessing of the Forge','cleric.forge',1,'At the end of a long rest, you can touch a nonmagical item and give it a temporary magical bonus as specified.'),
f('cleric.forge.channel-divinity-artisans-blessing','Channel Divinity: Artisan’s Blessing','cleric.forge',2,'You can use Channel Divinity to conduct a ritual that creates a metal object of limited value.'),
f('cleric.forge.soul-of-the-forge','Soul of the Forge','cleric.forge',6,'You gain resistance to fire damage and a bonus to AC while wearing heavy armor.'),
f('cleric.forge.divine-strike','Divine Strike','cleric.forge',8,'Once on each of your turns, a weapon hit deals extra fire damage.'),
f('cleric.forge.saint-of-forge-and-fire','Saint of Forge and Fire','cleric.forge',17,'You gain resistance to fire damage and, while wearing heavy armor, can gain resistance to nonmagical bludgeoning, piercing, and slashing damage.'),
f('cleric.grave.circle-of-mortality','Circle of Mortality','cleric.grave',1,'You learn spare the dying and maximize healing dice when restoring hit points to a creature at 0 hit points.'),
f('cleric.grave.path-to-the-grave','Channel Divinity: Path to the Grave','cleric.grave',2,'You can use Channel Divinity to make a creature vulnerable to the next damaging hit.'),
f('cleric.grave.sentinel-at-deaths-door','Sentinel at Death’s Door','cleric.grave',6,'You can use your reaction to turn a critical hit against a creature within range into a normal hit.'),
f('cleric.grave.potent-spellcasting','Potent Spellcasting','cleric.grave',8,'You add your Wisdom modifier to the damage of your cleric cantrips.'),
f('cleric.grave.keeper-of-souls','Keeper of Souls','cleric.grave',17,'When an enemy dies nearby, you can heal yourself or an ally as specified.'),
f('cleric.twilight.eyes-of-night','Eyes of Night','cleric.twilight',1,'You gain superior darkvision and can share it with allies for a limited duration.'),
f('cleric.twilight.twilight-sanctuary','Twilight Sanctuary','cleric.twilight',2,'You can create a sphere of twilight that grants temporary hit points or ends charm and frightened effects each round.'),
f('cleric.twilight.steps-of-night','Steps of Night','cleric.twilight',6,'You can gain a flying speed in dim light or darkness for a limited duration.'),
f('cleric.twilight.divine-strike','Divine Strike','cleric.twilight',8,'Once on each of your turns, a weapon hit deals extra radiant damage.'),
f('cleric.twilight.twilight-shroud','Twilight Shroud','cleric.twilight',17,'Creatures benefiting from Twilight Sanctuary gain half cover.'),
// Druid — Xanathar/Tasha
f('druid.dreams.balm-of-the-summer-court','Balm of the Summer Court','druid.dreams',2,'You can use a pool of magical dice to restore hit points and grant temporary hit points.'),
f('druid.dreams.hearth-of-moonlight-and-shadow','Hearth of Moonlight and Shadow','druid.dreams',6,'A rest in your conjured shelter grants a bonus to Stealth and Perception and protects against divination.'),
f('druid.dreams.hidden-paths','Hidden Paths','druid.dreams',10,'You can teleport yourself or an ally as a bonus action.'),
f('druid.dreams.walking-through-dreams','Walker in Dreams','druid.dreams',14,'You can cast dream, scrying, or teleportation circle without expending a spell slot as specified.'),
f('druid.shepherd.speech-of-the-woods','Speech of the Woods','druid.shepherd',2,'You gain the ability to communicate with beasts and learn Sylvan.'),
f('druid.shepherd.spirit-totem','Spirit Totem','druid.shepherd',2,'You can summon a spirit aura that grants one of three beneficial effects.'),
f('druid.shepherd.mighty-summoner','Mighty Summoner','druid.shepherd',6,'Creatures summoned or created by your spells gain extra hit points and their attacks count as magical.'),
f('druid.shepherd.guardian-spirit','Guardian Spirit','druid.shepherd',10,'Summoned creatures regain hit points while within your Spirit Totem aura.'),
f('druid.shepherd.faithful-summons','Faithful Summons','druid.shepherd',14,'When reduced to 0 hit points or incapacitated, you can automatically summon beasts as specified.'),
f('druid.wildfire.summon-wildfire-spirit','Summon Wildfire Spirit','druid.wildfire',2,'You can expend Wild Shape to summon a Wildfire Spirit with teleportation and fire abilities.'),
f('druid.wildfire.enhanced-bond','Enhanced Bond','druid.wildfire',6,'Your fire damage spells and healing spells gain a bonus while your Wildfire Spirit is present.'),
f('druid.wildfire.cauterizing-flames','Cauterizing Flames','druid.wildfire',10,'A creature can trigger a flame mote when it dies near you, healing or damaging a nearby creature when the mote is used.'),
f('druid.wildfire.blazing-revival','Blazing Revival','druid.wildfire',14,'When you drop to 0 hit points, your Wildfire Spirit can trigger an emergency healing and fire effect.'),
f('druid.spores.halo-of-spores','Halo of Spores','druid.spores',2,'You can use your reaction to deal necrotic damage to a creature entering or starting its turn near you.'),
f('druid.spores.symbiotic-entity','Symbiotic Entity','druid.spores',2,'You can expend Wild Shape to awaken spores, gaining temporary hit points and enhanced Halo of Spores and melee attacks.'),
f('druid.spores.fungal-infestation','Fungal Infestation','druid.spores',6,'When a Small or Medium beast or humanoid dies near you, you can animate it as a zombie.'),
f('druid.spores.spreading-spores','Spreading Spores','druid.spores',10,'You can place a cloud of spores in an area that deals necrotic damage to creatures entering or starting there.'),
f('druid.spores.fungal-body','Fungal Body','druid.spores',14,'You gain immunity to blinded, deafened, frightened, poisoned, and critical-hit effects as specified by the feature.'),
f('druid.stars.star-map','Star Map','druid.stars',2,'You gain a Star Map focus and learn guiding bolt, with additional uses of the spell as specified.'),
f('druid.stars.starry-form','Starry Form','druid.stars',2,'You can expend Wild Shape to assume a starry form with one of three constellations.'),
f('druid.stars.cosmic-omen','Cosmic Omen','druid.stars',6,'After a long rest, you receive an omen that lets you use a reaction to add or subtract a d6 from a nearby creature’s roll.'),
f('druid.stars.twinkling-constellations','Twinkling Constellations','druid.stars',10,'Your Starry Form constellations improve and you can change constellation form as specified.'),
f('druid.stars.full-of-stars','Full of Stars','druid.stars',14,'While in Starry Form, you become partially incorporeal and gain resistance to bludgeoning, piercing, and slashing damage.'),
// Fighter — Xanathar/Tasha
f('fighter.arcane-archer.arcane-archer-lore','Arcane Archer Lore','fighter.arcane-archer',3,'You learn Arcana or Nature and gain proficiency with a tool as specified.'),
f('fighter.arcane-archer.arcane-shot','Arcane Shot','fighter.arcane-archer',3,'You learn magical arrow options and can use one when you hit with a shortbow or longbow attack.'),
f('fighter.arcane-archer.magic-arrow','Magic Arrow','fighter.arcane-archer',7,'Your nonmagical arrows become magical when fired from a shortbow or longbow.'),
f('fighter.arcane-archer.curving-shot','Curving Shot','fighter.arcane-archer',7,'When you miss with a magical arrow, you can redirect it toward another target using a bonus action.'),
f('fighter.arcane-archer.eldritch-shot','Magic Arrow Improvement','fighter.arcane-archer',10,'Your Arcane Shot options improve as specified by the subclass.'),
f('fighter.arcane-archer.arcane-shot-10','Ever-Ready Shot','fighter.arcane-archer',15,'You regain one expended use of Arcane Shot whenever you finish a short or long rest.'),
f('fighter.cavalier.born-to-the-saddle','Born to the Saddle','fighter.cavalier',3,'You gain benefits when mounted and can dismount without spending additional movement as specified.'),
f('fighter.cavalier.unwavering-mark','Unwavering Mark','fighter.cavalier',3,'You can mark creatures you hit, gaining benefits when they attack targets other than you.'),
f('fighter.cavalier.warding-maneuver','Warding Maneuver','fighter.cavalier',7,'You can use a reaction to roll a die and increase an ally’s AC or reduce damage from a hit.'),
f('fighter.cavalier.hold-the-line','Hold the Line','fighter.cavalier',10,'Creatures provoke opportunity attacks when they move within your reach, and hits reduce their speed to 0.'),
f('fighter.cavalier.ferocious-charger','Ferocious Charger','fighter.cavalier',15,'When you move at least 10 feet before hitting with a melee attack, you can knock the target prone.'),
f('fighter.cavalier.vigilant-defender','Vigilant Defender','fighter.cavalier',18,'You gain an additional reaction each round for opportunity attacks, subject to the feature.'),
f('fighter.samurai.fighting-spirit','Fighting Spirit','fighter.samurai',3,'As a bonus action, you can gain advantage on weapon attacks and temporary hit points.'),
f('fighter.samurai.elegant-courtier','Elegant Courtier','fighter.samurai',7,'You gain proficiency in Wisdom saving throws and a bonus to Persuasion checks.'),
f('fighter.samurai.tireless-spirit','Tireless Spirit','fighter.samurai',10,'When you roll initiative with no uses of Fighting Spirit remaining, you regain one use.'),
f('fighter.samurai.rapid-strike','Rapid Strike','fighter.samurai',15,'You can trade advantage on one attack for an additional weapon attack on the same turn.'),
f('fighter.samurai.strength-before-death','Strength Before Death','fighter.samurai',18,'When reduced to 0 hit points, you can take an additional turn before falling unconscious, with the feature’s limits.'),
f('fighter.psi-warrior.psionic-power','Psionic Power','fighter.psi-warrior',3,'You gain a pool of Psionic Energy dice used for Psionic Strike, Protective Field, and Telekinetic Movement.'),
f('fighter.psi-warrior.telekinetic-adept','Telekinetic Adept','fighter.psi-warrior',7,'Your Psionic Energy abilities improve and you gain Psi-Powered Leap.'),
f('fighter.psi-warrior.guardian-adept','Guarded Mind','fighter.psi-warrior',10,'You can end charm or frightened effects by spending Psionic Energy.'),
f('fighter.psi-warrior.bulwark-of-force','Bulwark of Force','fighter.psi-warrior',15,'You can use Psionic Energy to grant allies half cover.'),
f('fighter.psi-warrior.telekinetic-master','Telekinetic Master','fighter.psi-warrior',18,'You can cast telekinesis and maintain it with a bonus action, gaining additional uses of Psionic Energy.'),
f('fighter.rune-knight.rune-carver','Bonus Proficiencies','fighter.rune-knight',3,'You gain proficiency with smith’s tools and learn Giant.'),
f('fighter.rune-knight.runes','Rune Carver','fighter.rune-knight',3,'You learn magical runes that can be inscribed on equipment and each provides passive and activated benefits.'),
f('fighter.rune-knight.giant-might','Giant’s Might','fighter.rune-knight',3,'You can become Large, gain advantage on Strength checks and saves, and deal extra damage for a limited duration.'),
f('fighter.rune-knight.runic-shield','Runic Shield','fighter.rune-knight',7,'You can use a reaction to force an attacker to reroll an attack against a creature within range.'),
f('fighter.rune-knight.great-stature','Great Stature','fighter.rune-knight',10,'Your height and size can increase and Giant’s Might damage improves.'),
f('fighter.rune-knight.master-of-runes','Master of Runes','fighter.rune-knight',15,'You can invoke each known rune twice between rests instead of once.'),
f('fighter.rune-knight.rune-magic','Runic Juggernaut','fighter.rune-knight',18,'Giant’s Might improves, increasing size and damage and granting additional benefits.'),
// Wizard — Tasha
f('wizard.bladesinging.bladesong','Bladesong','wizard.bladesinging',2,'You can invoke a magical song that improves AC, concentration, speed, and Dexterity (Acrobatics) checks.'),
f('wizard.bladesinging.extra-attack','Extra Attack','wizard.bladesinging',6,'You can attack twice, and can replace one attack with a cantrip.'),
f('wizard.bladesinging.song-of-defense','Song of Defense','wizard.bladesinging',10,'You can expend a spell slot as a reaction to reduce damage taken.'),
f('wizard.bladesinging.song-of-victory','Song of Victory','wizard.bladesinging',14,'You add your Intelligence modifier to the damage of your melee weapon attacks while Bladesong is active.'),
f('wizard.order-of-scribes.awakened-spellbook','Awakened Spellbook','wizard.order-of-scribes',2,'Your spellbook gains magical awareness, can be used as a focus, and lets you change a spell’s damage type under specified conditions.'),
f('wizard.order-of-scribes.manifest-mind','Manifest Mind','wizard.order-of-scribes',6,'You can manifest a spectral mind from your spellbook to see, communicate, and cast spells through it.'),
f('wizard.order-of-scribes.master-scrivener','Master Scrivener','wizard.order-of-scribes',10,'You can create a magical scroll and can copy spells more quickly as specified.'),
f('wizard.order-of-scribes.one-with-the-word','One with the Word','wizard.order-of-scribes',14,'You can avoid being reduced to 0 hit points by sacrificing spells from your spellbook, subject to the feature.'),
// Artificer — Tasha remaining specializations
f('artificer.alchemist.experimental-elixir','Experimental Elixir','artificer.alchemist',3,'You can create an experimental elixir after a long rest and can create additional elixirs by expending spell slots.'),
f('artificer.alchemist.alchemical-savant','Alchemical Savant','artificer.alchemist',5,'You add your Intelligence modifier to one damage or healing roll of qualifying spells cast with alchemist’s supplies.'),
f('artificer.alchemist.restorative-reagents','Restorative Reagents','artificer.alchemist',9,'You gain temporary hit points when using certain elixirs and can restore hit points or remove conditions with them.'),
f('artificer.alchemist.chemical-mastery','Chemical Mastery','artificer.alchemist',15,'You gain resistance to acid and poison damage and can cast greater restoration and heal once per long rest.'),
f('artificer.artillerist.eldritch-cannon','Eldritch Cannon','artificer.artillerist',3,'You can create a magical cannon that has a Flamethrower, Force Ballista, or Protector mode.'),
f('artificer.artillerist.arcane-firearm','Arcane Firearm','artificer.artillerist',5,'You can use a wand, staff, or rod as an arcane firearm and add a d8 to one damage roll of qualifying spells.'),
f('artificer.artillerist.explosive-cannon','Explosive Cannon','artificer.artillerist',9,'Your Eldritch Cannon damage increases and you can detonate it for additional damage.'),
f('artificer.artillerist.positioning-system','Fortified Position','artificer.artillerist',15,'You can create two Eldritch Cannons and grant half cover to creatures near them.'),
f('artificer.battle-smith.battle-ready','Battle Ready','artificer.battle-smith',3,'You gain martial weapon proficiency and can use Intelligence instead of Strength or Dexterity for magical weapon attacks.'),
f('artificer.battle-smith.steel-defender','Steel Defender','artificer.battle-smith',3,'You create a Steel Defender that acts with your initiative and uses the feature’s reaction and attack rules.'),
f('artificer.battle-smith.extra-attack','Extra Attack','artificer.battle-smith',5,'You can attack twice whenever you take the Attack action.'),
f('artificer.battle-smith.arcane-jolt','Arcane Jolt','artificer.battle-smith',9,'When you or your Steel Defender hits with a magic weapon, you can deal extra force damage or restore hit points.'),
f('artificer.battle-smith.improved-defender','Improved Defender','artificer.battle-smith',15,'Your Arcane Jolt improves and your Steel Defender gains stronger defenses and retaliation damage.'),
];