/** Concise 2014 PHB rule summaries; mechanics remain in the rules/effect layer. */
export const FEATURE_DESCRIPTIONS:Record<string,string>={
'barbarian:rage':'As a bonus action, enter a rage for up to 1 minute. While raging, gain advantage on Strength checks and saves, a rage damage bonus to Strength-based melee weapon attacks, and resistance to bludgeoning, piercing, and slashing damage. You cannot cast spells or concentrate on them while raging.',
'barbarian:unarmored-defense':'While wearing no armor, AC equals 10 + Dexterity modifier + Constitution modifier; a shield may still be used.',
'barbarian:reckless-attack':'From 2nd level, when you make your first attack using Strength on your turn, you can gain advantage on Strength-based melee attacks for the turn; attacks against you have advantage until your next turn.',
'barbarian:danger-sense':'You have advantage on Dexterity saves against effects you can see unless blinded, deafened, or incapacitated.',
'barbarian:primal-path':'At 3rd level, choose a Primal Path, which grants subclass features at its listed levels.',
'barbarian:fast-movement':'From 5th level, your speed increases by 10 feet while not wearing heavy armor.',
'barbarian:feral-instinct':'From 7th level, you have advantage on initiative rolls and can act normally when surprised by entering rage before other actions.',
'barbarian:brutal-critical':'From 9th level, critical hits with melee attacks add one weapon damage die; extra dice increase at higher levels.',
'barbarian:relentless-rage':'From 11th level, while raging, a Constitution save can let you drop to 1 hit point instead of 0; the DC increases after use and resets after a short or long rest.',
'barbarian:persistent-rage':'From 15th level, rage ends early only if you fall unconscious or choose to end it.',
'barbarian:indomitable-might':'From 18th level, if a Strength check total is below your Strength score, use the score instead.',
'barbarian:primal-champion':'At 20th level, Strength and Constitution increase by 4 and their maximums become 24.',
'bard:spellcasting':'You cast bard spells using Charisma; the bard table determines cantrips, spells known, and spell slots.',
'bard:bardic-inspiration':'As a bonus action, inspire a creature within 60 feet that can hear you; it gains a Bardic Inspiration die for a qualifying d20 roll within 10 minutes. Uses equal Charisma modifier per long rest.',
'bard:jack-of-all-trades':'From 2nd level, add half proficiency bonus, rounded down, to ability checks that do not already include proficiency.',
'bard:song-of-rest':'From 2nd level, allies who spend Hit Dice during a short rest while you perform regain extra hit points; the die improves at 9th, 13th, and 17th level.',
'bard:bard-college':'At 3rd level, choose a Bard College; it grants subclass features at its listed levels.',
'bard:expertise':'Double proficiency bonus for two proficient skills, or one skill and one tool; gain additional Expertise choices at higher levels.',
'bard:font-of-inspiration':'From 5th level, regain expended Bardic Inspiration on a short or long rest.',
'bard:countercharm':'At 6th level, as an action, perform to give allies within 30 feet advantage on saves against being frightened or charmed.',
'bard:magical-secrets':'At 10th level and again at higher levels, learn spells from any class list; they count as bard spells for you.',
'bard:superior-inspiration':'At 20th level, if you roll initiative with no Bardic Inspiration uses remaining, regain one.',
'cleric:spellcasting':'You prepare cleric spells using Wisdom; the cleric table determines cantrips and spell slots, and prepared spells can change after a long rest.',
'cleric:divine-domain':'At 1st level, choose a Divine Domain, gaining domain spells and features at its listed levels.',
'cleric:channel-divinity':'At 2nd level, gain Channel Divinity and a domain option. You regain uses on a short or long rest; additional uses arrive at higher levels.',
'cleric:destroy-undead':'From 5th level, undead that fail against your Channel Divinity turn effect are destroyed when their CR is within the threshold, which improves at 8th, 11th, 14th, and 17th level.',
'cleric:divine-intervention':'From 10th level, roll percentile dice to call on your deity; a result at or below your cleric level succeeds. After success, wait 7 days before using it again.',
'cleric:divine-intervention-improvement':'At 20th level, Divine Intervention succeeds automatically without a roll.',
'druid:druidic':'You know Druidic, the secret language of druids, and can leave hidden messages recognizable by other druids.',
'druid:spellcasting':'You prepare druid spells using Wisdom; prepared spells can change after a long rest and the druid table determines cantrips and slots.',
'druid:wild-shape':'From 2nd level, use an action to assume the form of a beast you have seen, following the PHB limits on CR, movement, duration, and capabilities.',
'druid:druid-circle':'At 2nd level, choose a Druid Circle; it grants features at 2nd, 6th, 10th, and 14th level.',
'druid:timeless-body':'At 18th level, primal magic slows aging: every 10 years, your body ages only 1 year.',
'druid:beast-spells':'At 18th level, you can cast many druid spells while in Wild Shape, providing verbal and somatic components but not material components.',
'druid:archdruid':'At 20th level, Wild Shape becomes unlimited and you can ignore verbal and somatic components of druid spells, subject to the PHB limits.',
'fighter:fighting-style':'At 1st level, choose a fighter Fighting Style; the same style cannot normally be chosen twice.',
'fighter:second-wind':'As a bonus action, regain 1d10 + fighter level hit points; recover the use on a short or long rest.',
'fighter:action-surge':'From 2nd level, take one additional action on your turn; recover the use on a short or long rest and gain a second use at 17th level.',
'fighter:martial-archetype':'At 3rd level, choose a Martial Archetype, gaining subclass features at its listed levels.',
'fighter:extra-attack':'At 5th level, attack twice with the Attack action; the number increases to three attacks at 11th and four at 20th level.',
'fighter:indomitable':'From 9th level, reroll a failed saving throw and use the new result; gain additional uses at 13th and 17th level and recover all uses on a long rest.',
'monk:unarmored-defense':'While wearing no armor and wielding no shield, AC equals 10 + Dexterity modifier + Wisdom modifier.',
'monk:martial-arts':'While unarmored and using monk weapons or unarmed strikes, use Dexterity for qualifying attacks and damage, use the Martial Arts die, and make an unarmed strike as a bonus action after attacking.',
'monk:ki':'At 2nd level, gain ki points equal to monk level. Ki fuels monk features and returns on a short or long rest.',
'monk:unarmored-movement':'From 2nd level, speed increases while unarmored and without a shield; the bonus improves and eventually enables movement across vertical surfaces and liquids.',
'monk:monastic-tradition':'At 3rd level, choose a Monastic Tradition, gaining subclass features at its listed levels.',
'monk:deflect-missiles':'Use your reaction to reduce ranged weapon damage by 1d10 + Dexterity modifier + monk level; if reduced to 0, spend 1 ki to catch and throw the missile.',
'monk:slow-fall':'From 4th level, use your reaction to reduce falling damage by five times your monk level.',
'monk:stunning-strike':'From 5th level, after hitting with a melee weapon attack, spend 1 ki to force a Constitution save; failure stuns the target until the end of your next turn.',
'monk:ki-empowered-strikes':'At 6th level, unarmed strikes count as magical for overcoming resistance and immunity to nonmagical attacks and damage.',
'monk:evasion':'At 7th level, Dexterity-save effects that deal half damage on success deal no damage on success and half on failure.',
'monk:stillness-of-mind':'At 7th level, use an action to end one effect causing you to be charmed or frightened.',
'monk:purity-of-body':'At 10th level, become immune to disease and poison.',
'monk:tongue-of-sun-moon':'At 13th level, understand all spoken languages and be understood by any creature that understands a language.',
'monk:diamond-soul':'At 14th level, gain proficiency in all saving throws and spend 1 ki to reroll a failed save.',
'monk:timeless-body':'At 15th level, you no longer suffer old-age frailty, cannot be magically aged, and no longer need food or water.',
'monk:empty-body':'At 18th level, spend 4 ki to become invisible for 1 minute and gain resistance to all damage except force; 8 ki also lets you cast astral projection on yourself without material components.',
'monk:perfect-self':'At 20th level, when initiative is rolled and you have fewer than 4 ki, regain ki until you have 4.',
'paladin:divine-sense':'As an action, detect celestials, fiends, and undead within 60 feet that are not behind total cover, plus consecrated or desecrated places or objects. Uses equal 1 + Charisma modifier per long rest.',
'paladin:lay-on-hands':'Your healing pool contains five times your paladin level in hit points. As an action, restore hit points by touch or spend 5 points to cure one disease or neutralize one poison.',
'paladin:fighting-style':'At 2nd level, choose a paladin Fighting Style.',
'paladin:spellcasting':'You prepare paladin spells using Charisma; the paladin table determines spell slots and prepared spells can change after a long rest.',
'paladin:divine-smite':'When you hit with a melee weapon attack, expend a spell slot for extra radiant damage; higher slots add dice and fiends or undead take extra damage.',
'paladin:sacred-oath':'At 3rd level, swear a Sacred Oath, gaining oath spells, Channel Divinity options, and subclass features.',
'paladin:divine-health':'At 3rd level, become immune to disease.',
'paladin:aura-of-protection':'From 6th level, you and friendly creatures within 10 feet add your Charisma modifier to saving throws while you are conscious; range becomes 30 feet at 18th level.',
'paladin:aura-of-courage':'From 10th level, you and friendly creatures within 10 feet cannot be frightened while you are conscious; range improves at 18th level.',
'paladin:improved-divine-smite':'From 11th level, every melee weapon hit deals 1d8 extra radiant damage.',
'paladin:cleansing-touch':'From 14th level, use an action to end one spell on yourself or a willing creature you touch. Uses equal Charisma modifier per long rest.',
'ranger:favored-enemy':'Choose a favored enemy and gain tracking and information benefits. Choose additional favored enemies and languages at 6th and 14th level.',
'ranger:natural-explorer':'Choose a favored terrain. It grants the PHB travel, navigation, stealth, foraging, and tracking benefits; choose more terrains at 6th and 10th level.',
'ranger:fighting-style':'At 2nd level, choose a ranger Fighting Style.',
'ranger:spellcasting':'You learn ranger spells using Wisdom; the ranger table determines spells known and spell slots.',
'ranger:ranger-archetype':'At 3rd level, choose a Ranger Archetype, gaining subclass features at its listed levels.',
'ranger:primeval-awareness':'From 3rd level, expend a ranger spell slot to sense whether certain creature types are present within 1 mile, or 6 miles in favored terrain, for 1 minute.',
'ranger:land-stride':'From 8th level, nonmagical difficult terrain costs no extra movement, nonmagical plants do not slow or harm you, and you have advantage against magically manipulated plants.',
'ranger:hide-in-plain-sight':'From 10th level, spend 1 minute creating camouflage. While motionless against a suitable surface, gain +10 to Stealth until you move or take an action or reaction.',
'ranger:vanish':'From 14th level, Hide as a bonus action and cannot be tracked nonmagically unless you choose to leave a trail.',
'ranger:feral-senses':'From 18th level, lack of sight does not impose disadvantage on attacks against creatures you fight if you are not blinded, and you sense invisible creatures within 30 feet that are not hidden.',
'ranger:foe-slayer':'At 20th level, once on each turn, add your Wisdom modifier to an attack or damage roll against your favored enemy.',
'rogue:expertise':'Double proficiency bonus for two proficient skills or one skill and thieves’ tools; gain additional Expertise choices at 6th level.',
'rogue:sneak-attack':'Once per turn, deal extra damage when you hit with a finesse or ranged weapon attack and meet the PHB advantage or ally-position requirements.',
'rogue:thieves-cant':'You know the secret language, jargon, and code of the criminal underworld and can communicate hidden messages with it.',
'rogue:cunning-action':'From 2nd level, take Dash, Disengage, or Hide as a bonus action.',
'rogue:roguish-archetype':'At 3rd level, choose a Roguish Archetype, gaining subclass features at its listed levels.',
'rogue:uncanny-dodge':'From 5th level, when an attacker you can see hits you with an attack, use your reaction to halve the attack damage.',
'rogue:evasion':'From 7th level, Dexterity-save effects that deal half damage on success deal no damage on success and half on failure.',
'rogue:reliable-talent':'From 11th level, when a proficient ability check would add proficiency, treat a d20 roll of 9 or lower as 10.',
'rogue:blindsense':'From 14th level, if you can hear, you know the location of hidden or invisible creatures within 10 feet.',
'rogue:slippery-mind':'At 15th level, gain proficiency in Wisdom saving throws.',
'rogue:elusive':'At 18th level, attack rolls against you cannot have advantage while you are not incapacitated.',
'rogue:stroke-of-luck':'At 20th level, once per short or long rest, turn a failed attack roll into a hit or a failed ability check into a 20; you can also turn an attack roll against you into a miss.',
'sorcerer:spellcasting':'You learn sorcerer spells using Charisma; the sorcerer table determines cantrips known, spells known, and spell slots.',
'sorcerer:sorcerous-origin':'At 1st level, choose a Sorcerous Origin, gaining subclass features at its listed levels.',
'sorcerer:font-of-magic':'At 2nd level, gain sorcery points equal to sorcerer level. Spend them to create spell slots or fuel Metamagic; recover all on a long rest.',
'sorcerer:metamagic':'At 3rd level, choose Metamagic options that modify spellcasting by spending sorcery points; learn more options at higher levels.',
'sorcerer:sorcerous-restoration':'At 20th level, regain 4 expended sorcery points when you finish a short rest.',
'warlock:otherworldly-patron':'At 1st level, choose an Otherworldly Patron, gaining patron features and expanded spell options at listed levels.',
'warlock:pact-magic':'You cast warlock spells using Charisma and regain Pact Magic slots on a short or long rest; all Pact Magic slots share the same level.',
'warlock:eldritch-invocations':'At 2nd level, learn Eldritch Invocations that grant magical abilities; learn more at listed levels and replace an invocation when gaining a warlock level.',
'warlock:pact-boon':'At 3rd level, your patron grants a Pact Boon such as Chain, Blade, or Tome.',
'warlock:mystic-arcanum':'At 11th level, choose a 6th-level spell as Mystic Arcanum; gain 7th-, 8th-, and 9th-level choices at 13th, 15th, and 17th. Each casts once per long rest without a slot.',
'warlock:eldritch-master':'At 20th level, spend 1 minute entreating your patron to regain all expended Pact Magic slots; once used, it requires a long rest.',
'wizard:spellcasting':'You learn wizard spells using Intelligence and maintain a spellbook; the wizard table determines cantrips and spell slots.',
'wizard:arcane-recovery':'Once per day after a short rest, recover spell slots with combined levels no greater than half wizard level, rounded up; no recovered slot may be 6th level or higher.',
'wizard:arcane-tradition':'At 2nd level, choose an Arcane Tradition, gaining subclass features at its listed levels.',
'wizard:spell-mastery':'At 18th level, choose one 1st-level and one 2nd-level wizard spell in your spellbook. Cast each at lowest level without a slot; choices can change after a short rest.',
'wizard:signature-spells':'At 20th level, choose two 3rd-level wizard spells as signature spells. They are always prepared and each can be cast once per short or long rest without a slot.',
'artificer:magical-tinkering':'Imbue a Tiny nonmagical object with a minor magical property such as light, a recorded message, an odor, or a static visual effect.',
'artificer:spellcasting':'You prepare artificer spells using Intelligence; the artificer table determines cantrips and slots, and tools can serve as a spellcasting focus.',
'artificer:infuse-item':'At 2nd level, learn magical infusions that turn mundane objects into magic items; know and maintain a limited number.',
'artificer:artificer-specialist':'At 3rd level, choose an Artificer Specialist, gaining subclass features at its listed levels.',
'artificer:right-tool-for-the-job':'At 3rd level, create one set of artisan’s tools in an unoccupied space within 5 feet; it lasts 1 hour and disappears after use.',
'artificer:tool-expertise':'At 6th level, double your proficiency bonus for ability checks using a proficient tool.',
'artificer:flash-of-genius':'At 7th level, use your reaction to add your Intelligence modifier to an ability check or saving throw made by you or another creature within 30 feet. Uses equal Intelligence modifier per long rest.',
'artificer:magic-item-adept':'At 10th level, attune to up to four magic items and craft common or uncommon magic items faster and for half the normal gold cost.',
'artificer:spell-storing-item':'At 11th level, store a 1st- or 2nd-level artificer spell with a 1-action casting time in an item; a holder can cast it using your spellcasting ability for the item’s limited uses.',
'artificer:magic-item-savant':'At 14th level, attune to up to five magic items and ignore class, race, spell, and level requirements for attunement.',
'artificer:magic-item-master':'At 18th level, attune to up to six magic items and add +1 to saving throws per attuned magic item.',
'artificer:soul-of-artifice':'At 20th level, add +1 to all saving throws per attuned magic item. When reduced to 0 hit points, end an infusion to drop to 1 hit point, subject to the feature limits.'
};
