import {FEAT_DESCRIPTIONS} from './feat-descriptions';
export type FeatSource='phb2014'|'xanathar2017'|'tasha2020'|'homebrew';
export interface FeatDefinition{id:string;name:string;source:FeatSource;prerequisite?:string;description:string}
const phb=(id:string,name:string,prerequisite?:string):FeatDefinition=>({id,name,source:'phb2014',prerequisite,description:FEAT_DESCRIPTIONS[id]??'Description not yet populated.'});
const optional=(id:string,name:string,source:'xanathar2017'|'tasha2020',prerequisite?:string):FeatDefinition=>({id,name,source,prerequisite,description:FEAT_DESCRIPTIONS[id]??'Description not yet populated.'});
export const FEATS:FeatDefinition[]=[
phb('alert','Alert'),phb('athlete','Athlete'),phb('actor','Actor'),phb('charger','Charger'),phb('crossbow-expert','Crossbow Expert'),phb('defensive-duelist','Defensive Duelist','Dexterity 13'),phb('dual-wielder','Dual Wielder'),phb('dungeon-delver','Dungeon Delver'),phb('durable','Durable','Constitution 13'),phb('elemental-adept','Elemental Adept','Spellcasting'),phb('grappler','Grappler','Strength 13'),phb('great-weapon-master','Great Weapon Master'),phb('healer','Healer'),phb('heavily-armored','Heavily Armored','Proficiency with medium armor'),phb('heavy-armor-master','Heavy Armor Master','Proficiency with heavy armor'),phb('inspiring-leader','Inspiring Leader','Charisma 13'),phb('keen-mind','Keen Mind'),phb('lightly-armored','Lightly Armored'),phb('linguist','Linguist','Intelligence 13'),phb('lucky','Lucky'),phb('mage-slayer','Mage Slayer'),phb('magic-initiate','Magic Initiate'),phb('martial-adept','Martial Adept'),phb('medium-armor-master','Medium Armor Master','Proficiency with medium armor'),phb('mobile','Mobile'),phb('moderately-armored','Moderately Armored','Proficiency with light armor'),phb('mounted-combatant','Mounted Combatant'),phb('observant','Observant','Intelligence or Wisdom 13'),phb('polearm-master','Polearm Master'),phb('resilient','Resilient'),phb('ritual-caster','Ritual Caster','Intelligence or Wisdom 13'),phb('savage-attacker','Savage Attacker'),phb('sentinel','Sentinel'),phb('sharpshooter','Sharpshooter'),phb('shield-master','Shield Master'),phb('skilled','Skilled'),phb('skulker','Skulker','Dexterity 13'),phb('spell-sniper','Spell Sniper','Spellcasting'),phb('tavern-brawler','Tavern Brawler','Strength 13 or Dexterity 13'),phb('tough','Tough'),phb('war-caster','War Caster','Spellcasting'),phb('weapon-master','Weapon Master'),
optional('elven-accuracy','Elven Accuracy','xanathar2017','Elf or half-elf'),optional('dwarven-fortitude','Dwarven Fortitude','xanathar2017','Dwarf'),optional('bountiful-luck','Bountiful Luck','xanathar2017','Halfling'),optional('dragon-fear','Dragon Fear','xanathar2017','Dragonborn'),optional('dragon-hide','Dragon Hide','xanathar2017','Dragonborn'),optional('drow-high-magic','Drow High Magic','xanathar2017','Drow'),optional('fade-away','Fade Away','xanathar2017','Gnome'),optional('fey-teleportation','Fey Teleportation','xanathar2017','High Elf'),optional('flames-of-phlegethos','Flames of Phlegethos','xanathar2017','Tiefling'),optional('infernal-constitution','Infernal Constitution','xanathar2017','Tiefling'),optional('orcish-fury','Orcish Fury','xanathar2017','Half-orc'),optional('prodigy','Prodigy','xanathar2017','Half-elf, half-orc, or human'),optional('wood-elf-magic','Wood Elf Magic','xanathar2017','Wood Elf'),
optional('artificer-initiate','Artificer Initiate','tasha2020'),optional('chef','Chef','tasha2020'),optional('crusher','Crusher','tasha2020'),optional('fey-touched','Fey Touched','tasha2020'),optional('fighting-initiate','Fighting Initiate','tasha2020','Proficiency with a martial weapon'),optional('metamagic-adept','Metamagic Adept','tasha2020','Spellcasting or Pact Magic'),optional('piercer','Piercer','tasha2020'),optional('poisoner','Poisoner','tasha2020'),optional('shadow-touched','Shadow Touched','tasha2020'),optional('skill-expert','Skill Expert','tasha2020'),optional('slasher','Slasher','tasha2020'),optional('telekinetic','Telekinetic','tasha2020'),optional('telepathic','Telepathic','tasha2020'),optional('eldritch-adept','Eldritch Adept','tasha2020','Spellcasting or Pact Magic')
];
