import type {Spell} from '../types';

const spell=(source:Spell['source'],value:Spell):Spell=>({...value,source});

/**
 * Paladin additions missing from the base catalog.
 * Availability follows the 2014 books: PHB core, Xanathar additions,
 * and Tasha's optional Additional Paladin Spells.
 */
export const PALADIN_SUPPLEMENTAL_SPELLS:Spell[]=[
 spell('phb2014',{id:'staggering-smite',name:'Staggering Smite',level:4,school:'Evocation',classes:['paladin'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V'],duration:'Concentration, up to 1 minute',description:'The next time you hit a creature with a melee weapon attack, the attack deals extra psychic damage. The target must make a Wisdom saving throw or suffer disadvantage on attack rolls and ability checks and be unable to take reactions until the end of its next turn.'}),
 spell('xanathar2017',{id:'ceremony',name:'Ceremony',level:1,school:'Abjuration',classes:['paladin'],ritual:true,castingTime:'1 hour',range:'Touch',components:['V','S','M'],duration:'Instantaneous',description:'You perform a special religious ceremony and choose one of several rites, including atonement, blessing water, coming of age, dedication, funeral rites, or marriage.'}),
 spell('xanathar2017',{id:'find-greater-steed',name:'Find Greater Steed',level:4,school:'Conjuration',classes:['paladin'],castingTime:'10 minutes',range:'30 feet',components:['V','S'],duration:'Instantaneous',description:'You summon a spirit that assumes the form of a loyal, majestic mount such as a griffon, pegasus, peryton, dire wolf, rhinoceros, or saber-toothed tiger.'}),
 spell('xanathar2017',{id:'holy-weapon',name:'Holy Weapon',level:5,school:'Evocation',classes:['paladin'],concentration:true,castingTime:'1 bonus action',range:'Touch',components:['V','S'],duration:'Concentration, up to 1 hour',description:'You imbue a weapon with holy power. Weapon attacks with it deal extra radiant damage and the weapon emits bright and dim light; you can dismiss the spell to unleash a burst of radiant energy.'}),
 spell('tasha2020',{id:'prayer-of-healing',name:'Prayer of Healing',level:2,school:'Evocation',classes:['paladin'],castingTime:'10 minutes',range:'30 feet',components:['V'],duration:'Instantaneous',description:'Up to six creatures you choose within range regain hit points equal to 2d8 + your spellcasting ability modifier. The spell does not affect constructs or undead.',higherLevels:'Healing increases by 1d8 for each slot level above 2nd.'}),
 spell('tasha2020',{id:'gentle-repose',name:'Gentle Repose',level:2,school:'Necromancy',classes:['paladin'],ritual:true,castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'10 days',description:'You touch a corpse or other remains. The target is protected from decay and cannot become undead for the duration.'}),
 spell('tasha2020',{id:'spirit-shroud',name:'Spirit Shroud',level:3,school:'Necromancy',classes:['paladin'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V','S'],duration:'Concentration, up to 1 minute',description:'Spirits of the dead surround you. Your attacks deal extra radiant, necrotic, or cold damage to nearby creatures, and nearby enemies can have their speed reduced and cannot regain hit points until the start of your next turn.',higherLevels:'The extra damage increases by 1d8 for every two slot levels above 3rd.'}),
 spell('tasha2020',{id:'summon-celestial',name:'Summon Celestial',level:5,school:'Conjuration',classes:['paladin'],concentration:true,castingTime:'1 minute',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a celestial spirit that appears in an unoccupied space within range, is friendly to you and your companions, and obeys your verbal commands.',higherLevels:'When cast with a 9th-level slot, the celestial can have a higher challenge rating as described by the spell.'}),
 spell('tasha2020',{id:'warding-bond',name:'Warding Bond',level:2,school:'Abjuration',classes:['paladin'],castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'1 hour',description:'You protect a willing creature and create a mystical bond. While it remains within 60 feet, it gains +1 AC, +1 to saving throws, and resistance to all damage, while you take the same amount of damage whenever it takes damage.'})
];
