import type {Feature} from '../types';

type OathFeature={id:string;name:string;level:number;description:string;source:'phb2014'|'tasha2020'};
const f=(oath:string,value:OathFeature):Feature=>({id:`subclass:paladin:${oath}:${value.id}`,name:value.name,source:'subclass',level:value.level,description:value.description,optional:value.source==='tasha2020'});

export const PALADIN_SUBCLASS_FEATURES:Record<string,Feature[]>={
 devotion:[
  f('devotion',{id:'oath-spells',name:'Oath Spells',level:3,source:'phb2014',description:'You gain oath spells at the paladin levels specified by the Oath of Devotion table. They are always prepared and do not count against your prepared-spell limit: protection from evil and good, sanctuary, lesser restoration, zone of truth, beacon of hope, dispel magic, freedom of movement, guardian of faith, commune, and flame strike.'}),
  f('devotion',{id:'channel-divinity-sacred-weapon',name:'Channel Divinity: Sacred Weapon',level:3,source:'phb2014',description:'As an action, imbue one weapon you are holding with positive energy. For 1 minute, add your Charisma modifier to its attack rolls, and it emits bright and dim light. The weapon becomes magical if it is not already.'}),
  f('devotion',{id:'channel-divinity-turn-the-unholy',name:'Channel Divinity: Turn the Unholy',level:3,source:'phb2014',description:'As an action, present your holy symbol and force fiends and undead within 30 feet that can see or hear you to make a Wisdom saving throw or be turned for 1 minute or until they take damage.'}),
  f('devotion',{id:'aura-of-devotion',name:'Aura of Devotion',level:7,source:'phb2014',description:'You and friendly creatures within 10 feet cannot be charmed while you are conscious. The aura increases to 30 feet at 18th level.'}),
  f('devotion',{id:'purity-of-spirit',name:'Purity of Spirit',level:15,source:'phb2014',description:'You are always under the effects of protection from evil and good.'}),
  f('devotion',{id:'holy-nimbus',name:'Holy Nimbus',level:20,source:'phb2014',description:'As an action, emanate sunlight for 1 minute, shed bright and dim light, and impose disadvantage on saves against your paladin spells and Channel Divinity options on fiends and undead. Once used, this feature returns after a long rest.'})
 ],
 ancients:[
  f('ancients',{id:'oath-spells',name:'Oath Spells',level:3,source:'phb2014',description:'You gain oath spells at the listed paladin levels and they are always prepared: ensnaring strike, speak with animals, moonbeam, misty step, plant growth, protection from energy, ice storm, stoneskin, commune with nature, and tree stride.'}),
  f('ancients',{id:'channel-divinity-natures-wrath',name:"Channel Divinity: Nature's Wrath",level:3,source:'phb2014',description:'As an action, cause spectral vines to restrain a creature within 10 feet that you can see. The target makes a Strength or Dexterity saving throw to avoid or end the effect.'}),
  f('ancients',{id:'channel-divinity-turn-the-faithless',name:'Channel Divinity: Turn the Faithless',level:3,source:'phb2014',description:'As an action, present your holy symbol and force fey and fiends within 30 feet that can see or hear you to make a Wisdom saving throw or be turned for 1 minute or until they take damage.'}),
  f('ancients',{id:'aura-of-warding',name:'Aura of Warding',level:7,source:'phb2014',description:'You and friendly creatures within 10 feet have resistance to damage from spells while you are conscious. The aura increases to 30 feet at 18th level.'}),
  f('ancients',{id:'undying-sentinel',name:'Undying Sentinel',level:15,source:'phb2014',description:'When reduced to 0 hit points and not killed outright, you can drop to 1 hit point instead. You also suffer none of the drawbacks of old age. The healing effect returns after a long rest.'}),
  f('ancients',{id:'elder-champion',name:'Elder Champion',level:20,source:'phb2014',description:'As an action, transform for 1 minute: regain 10 hit points at the start of each turn, cast paladin spells with a casting time of 1 action as bonus actions, and make enemies within 10 feet have disadvantage on saves against your paladin spells and Channel Divinity.'})
 ],
 vengeance:[
  f('vengeance',{id:'oath-spells',name:'Oath Spells',level:3,source:'phb2014',description:'You gain oath spells at the listed paladin levels and they are always prepared: bane, hunter’s mark, hold person, misty step, haste, protection from energy, banishment, dimension door, hold monster, and scrying.'}),
  f('vengeance',{id:'channel-divinity-abjure-enemy',name:'Channel Divinity: Abjure Enemy',level:3,source:'phb2014',description:'As an action, choose one creature within 60 feet. It must make a Wisdom saving throw or become frightened for 1 minute and have speed 0 while frightened; fiends and undead have disadvantage on the save.'}),
  f('vengeance',{id:'channel-divinity-vow-of-enmity',name:'Channel Divinity: Vow of Enmity',level:3,source:'phb2014',description:'As a bonus action, choose a creature within 10 feet and gain advantage on attack rolls against it for 1 minute or until it drops to 0 hit points or becomes unconscious.'}),
  f('vengeance',{id:'relentless-avenger',name:'Relentless Avenger',level:7,source:'phb2014',description:'When you hit a creature with an opportunity attack, you can move up to half your speed immediately afterward without provoking opportunity attacks from that creature.'}),
  f('vengeance',{id:'soul-of-vengeance',name:'Soul of Vengeance',level:15,source:'phb2014',description:'When a creature under your Vow of Enmity attacks a target other than you, you can use your reaction to make a melee weapon attack against it if it is within range.'}),
  f('vengeance',{id:'avenging-angel',name:'Avenging Angel',level:20,source:'phb2014',description:'As an action, assume an avenging form for 1 hour: gain a flying speed, emanate a 30-foot aura that frightens enemies, and gain advantage on attacks against frightened creatures. Once used, it returns after a long rest.'})
 ],
 glory:[
  f('glory',{id:'oath-spells',name:'Oath Spells',level:3,source:'tasha2020',description:'You gain oath spells at the listed paladin levels and they are always prepared: guiding bolt, heroism, enhance ability, magic weapon, haste, protection from energy, compulsion, freedom of movement, flame strike, and commune.'}),
  f('glory',{id:'channel-divinity-peerless-athlete',name:'Channel Divinity: Peerless Athlete',level:3,source:'tasha2020',description:'As a bonus action, use Channel Divinity to gain advantage on Strength (Athletics) and Dexterity (Acrobatics) checks, carry twice the normal weight, and increase your long and high jump distances for 10 minutes.'}),
  f('glory',{id:'channel-divinity-inspiring-smite',name:'Channel Divinity: Inspiring Smite',level:3,source:'tasha2020',description:'Immediately after damaging a creature with Divine Smite, use Channel Divinity as a bonus action to distribute temporary hit points among creatures of your choice within 30 feet, including yourself, equal to 2d8 + your paladin level.'}),
  f('glory',{id:'aura-of-alacrity',name:'Aura of Alacrity',level:7,source:'tasha2020',description:'Your speed increases by 10 feet, and friendly creatures that start their turn within 5 feet of you gain 10 feet of speed until the end of that turn while you are not incapacitated. The range increases to 10 feet at 18th level.'}),
  f('glory',{id:'glorious-defense',name:'Glorious Defense',level:15,source:'tasha2020',description:'When you or another creature within 10 feet is hit by an attack, use your reaction to grant a bonus to AC equal to your Charisma modifier, potentially causing the attack to miss. If it misses, you can make a weapon attack against the attacker.'}),
  f('glory',{id:'living-legend',name:'Living Legend',level:20,source:'tasha2020',description:'As a bonus action, become an avatar of glory for 1 minute: gain advantage on Charisma checks and death saves, and once per turn turn a failed attack roll into a hit. You can also use your reaction to reroll a failed saving throw. Once used, this feature returns after a long rest.'})
 ],
 watchers:[
  f('watchers',{id:'oath-spells',name:'Oath Spells',level:3,source:'tasha2020',description:'You gain oath spells at the listed paladin levels and they are always prepared: alarm, detect magic, moonbeam, see invisibility, counterspell, nondetection, aura of purity, banishment, hold monster, and scrying.'}),
  f('watchers',{id:'channel-divinity-watchers-will',name:"Channel Divinity: Watcher's Will",level:3,source:'tasha2020',description:'As an action, choose creatures within 30 feet that can hear you. For 1 minute, the chosen creatures have advantage on Intelligence, Wisdom, and Charisma saving throws.'}),
  f('watchers',{id:'channel-divinity-abjure-the-extraplanar',name:'Channel Divinity: Abjure the Extraplanar',level:3,source:'tasha2020',description:'As an action, present your holy symbol and force aberrations, celestials, elementals, fey, or fiends within 30 feet to make a Wisdom saving throw or be turned for 1 minute or until they take damage.'}),
  f('watchers',{id:'aura-of-the-sentinel',name:'Aura of the Sentinel',level:7,source:'tasha2020',description:'You and friendly creatures within 10 feet add your proficiency bonus to initiative rolls while you are conscious. The aura increases to 30 feet at 18th level.'}),
  f('watchers',{id:'vigilant-rebuke',name:'Vigilant Rebuke',level:15,source:'tasha2020',description:'When you or a creature within your Aura of the Sentinel succeeds on an Intelligence, Wisdom, or Charisma saving throw, you can use your reaction to deal 2d8 + your Charisma modifier psychic damage to the creature that forced the save, if within range.'}),
  f('watchers',{id:'mortal-bulwark',name:'Mortal Bulwark',level:20,source:'tasha2020',description:'As a bonus action, become an extraplanar sentinel for 1 minute: gain truesight, advantage on attack rolls against aberrations, celestials, elementals, fey, and fiends, and force such creatures to make a Wisdom save or become frightened. Once used, it returns after a long rest.'})
 ]
};
