import type {Ability,Feature,Skill,Size} from '../types';
export interface SpeciesOption{id:string;name:string;source:'phb2014'|'tasha2020';abilityBonuses:Partial<Record<Ability,number>>;abilityChoiceCount?:number;abilityChoiceBonus?:number;skillProficiencyChoices?:number;fixedSkillProficiencies?:Skill[];speed?:number;darkvision?:number;size?:Size;languages?:string[];languageChoiceCount?:number;traits:Feature[];subraces:SubraceOption[]}
export interface SubraceOption{id:string;name:string;abilityBonuses:Partial<Record<Ability,number>>;fixedSkillProficiencies?:Skill[];speed?:number;darkvision?:number;languages?:string[];languageChoiceCount?:number;traits:Feature[]}
const t=(id:string,name:string,description:string):Feature=>({id,name,description,source:'species',level:1});
const sub=(id:string,name:string,abilityBonuses:Partial<Record<Ability,number>>,traits:Feature[],extra?:Partial<SubraceOption>):SubraceOption=>({id,name,abilityBonuses,traits,...extra});
export const SPECIES_DATA:SpeciesOption[]=[
{id:'dragonborn',name:'Dragonborn',source:'phb2014',abilityBonuses:{str:2,cha:1},speed:30,size:'Medium',languages:['Common','Draconic'],traits:[t('dragonborn-ancestry','Draconic Ancestry','Choose a dragon type; it determines the damage type of your Breath Weapon and damage resistance.'),t('breath-weapon','Breath Weapon','Exhale destructive energy in a 15-foot cone or a 5-by-30-foot line; creatures make a Dexterity saving throw. Damage is 2d6 at 1st level, 3d6 at 6th, 4d6 at 11th, and 5d6 at 16th.'),t('damage-resistance','Damage Resistance','Resistance to the damage type associated with your draconic ancestry.')],subraces:[]},
{id:'dwarf',name:'Dwarf',source:'phb2014',abilityBonuses:{con:2},speed:25,size:'Medium',darkvision:60,languages:['Common','Dwarvish'],traits:[t('dwarven-resilience','Dwarven Resilience','Advantage on saving throws against poison and resistance to poison damage.'),t('dwarven-combat-training','Dwarven Combat Training','Proficiency with battleaxe, handaxe, light hammer and warhammer.'),t('stonecunning','Stonecunning','Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient and add double your proficiency bonus.')],subraces:[sub('hill-dwarf','Hill Dwarf',{wis:1},[t('dwarven-toughness','Dwarven Toughness','Your hit point maximum increases by 1, and it increases by 1 every time you gain a level.')]),sub('mountain-dwarf','Mountain Dwarf',{str:2},[t('dwarven-armor-training','Dwarven Armor Training','Proficiency with light and medium armor.')])]},
{id:'elf',name:'Elf',source:'phb2014',abilityBonuses:{dex:2},speed:30,size:'Medium',darkvision:60,languages:['Common','Elvish'],fixedSkillProficiencies:['perception'],traits:[t('keen-senses','Keen Senses','Proficiency in the Perception skill.'),t('fey-ancestry','Fey Ancestry','Advantage on saving throws against being charmed, and magic cannot put you to sleep.'),t('trance','Trance','Elves do not need to sleep and finish a long rest in 4 hours of meditation.')],subraces:[sub('high-elf','High Elf',{int:1},[t('elf-weapon-training','Elf Weapon Training','Proficiency with longsword, shortsword, shortbow and longbow.'),t('high-elf-cantrip','Cantrip','Know one cantrip of your choice from the wizard spell list.'),t('extra-language','Extra Language','Speak, read and write one additional language.')],{languageChoiceCount:1}),sub('wood-elf','Wood Elf',{wis:1},[t('wood-elf-speed','Fleet of Foot','Walking speed increases to 35 feet.'),t('mask-of-the-wild','Mask of the Wild','Can attempt to hide even when only lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena.')],{speed:35}),sub('drow','Drow',{cha:1},[t('superior-darkvision','Superior Darkvision','Darkvision range is 120 feet.'),t('sunlight-sensitivity','Sunlight Sensitivity','Disadvantage on attack rolls and Wisdom (Perception) checks that rely on sight when you, the target, or whatever you are trying to perceive is in direct sunlight.'),t('drow-magic','Drow Magic','Know dancing lights; at 3rd level gain faerie fire; at 5th level gain darkness. Charisma is the spellcasting ability.')],{darkvision:120})]},
{id:'gnome',name:'Gnome',source:'phb2014',abilityBonuses:{int:2},speed:25,size:'Small',darkvision:60,languages:['Common','Gnomish'],traits:[t('gnome-cunning','Gnome Cunning','Advantage on Intelligence, Wisdom and Charisma saving throws against magic.')],subraces:[sub('forest-gnome','Forest Gnome',{dex:1},[t('natural-illusionist','Natural Illusionist','Know the minor illusion cantrip; Intelligence is the spellcasting ability.'),t('speak-with-small-beasts','Speak with Small Beasts','Through sounds and gestures, convey simple ideas to Small or smaller beasts.')]),sub('rock-gnome','Rock Gnome',{con:1},[t('artificers-lore','Artificer’s Lore','Add twice your proficiency bonus to Intelligence (History) checks related to magic items, alchemical objects or technological devices.'),t('tinker','Tinker','Proficiency with tinker's tools; spend 1 hour and 10 gp in materials to construct a Tiny clockwork device.')])]},
{id:'half-elf',name:'Half-Elf',source:'phb2014',abilityBonuses:{cha:2},abilityChoiceCount:2,abilityChoiceBonus:1,skillProficiencyChoices:2,speed:30,size:'Medium',darkvision:60,languages:['Common','Elvish'],languageChoiceCount:1,traits:[t('fey-ancestry','Fey Ancestry','Advantage on saving throws against being charmed, and magic cannot put you to sleep.'),t('skill-versatility','Skill Versatility','Proficiency in two skills of your choice.')],subraces:[]},
{id:'half-orc',name:'Half-Orc',source:'phb2014',abilityBonuses:{str:2,con:1},speed:30,size:'Medium',darkvision:60,languages:['Common','Orc'],fixedSkillProficiencies:['intimidation'],traits:[t('menacing','Menacing','Proficiency in the Intimidation skill.'),t('relentless-endurance','Relentless Endurance','When reduced to 0 hit points but not killed outright, drop to 1 hit point instead. Once used, cannot use again until you finish a long rest.'),t('savage-attacks','Savage Attacks','When you score a critical hit with a melee weapon attack, roll one of the weapon’s damage dice one additional time and add it to the extra damage of the critical hit.')],subraces:[]},
{id:'halfling',name:'Halfling',source:'phb2014',abilityBonuses:{dex:2},speed:25,size:'Small',languages:['Common','Halfling'],traits:[t('lucky','Lucky','When you roll a 1 on an attack roll, ability check, or saving throw, reroll the die and use the new roll.'),t('brave','Brave','Advantage on saving throws against being frightened.'),t('halfling-nimbleness','Halfling Nimbleness','Move through the space of any creature that is of a size larger than yours.')],subraces:[sub('lightfoot','Lightfoot',{cha:1},[t('naturally-stealthy','Naturally Stealthy','Can attempt to hide even when obscured only by a creature at least one size larger than you.')]),sub('stout','Stout',{con:1},[t('stout-resilience','Stout Resilience','Advantage on saving throws against poison and resistance to poison damage.')])]},
{id:'human',name:'Human',source:'phb2014',abilityBonuses:{str:1,dex:1,con:1,int:1,wis:1,cha:1},speed:30,size:'Medium',languages:['Common'],languageChoiceCount:1,traits:[t('extra-language','Extra Language','Speak, read and write one extra language of your choice.')],subraces:[]},
{id:'variant-human',name:'Variant Human',source:'phb2014',abilityBonuses:{},abilityChoiceCount:2,abilityChoiceBonus:1,skillProficiencyChoices:1,speed:30,size:'Medium',languages:['Common'],languageChoiceCount:1,traits:[t('variant-human-skill','Skill Proficiency','Proficiency in one skill of your choice.'),t('variant-human-feat','Feat','One feat of your choice.')],subraces:[]},
{id:'tiefling',name:'Tiefling',source:'phb2014',abilityBonuses:{int:1,cha:2},speed:30,size:'Medium',darkvision:60,languages:['Common','Infernal'],traits:[t('hellish-resistance','Hellish Resistance','Resistance to fire damage.'),t('infernal-legacy','Infernal Legacy','Know thaumaturgy; at 3rd level gain hellish rebuke; at 5th level gain darkness. Charisma is the spellcasting ability.')],subraces:[]}
];
export const SPECIES_BY_ID=Object.fromEntries(SPECIES_DATA.map(s=>[s.id,s]));