import type {Ability,Feature,Skill,Size} from '../types';
export interface SpeciesOption{id:string;name:string;source:'phb2014'|'tasha2020';abilityBonuses:Partial<Record<Ability,number>>;abilityChoiceCount?:number;abilityChoiceBonus?:number;skillProficiencyChoices?:number;fixedSkillProficiencies?:Skill[];speed?:number;darkvision?:number;size?:Size;languages?:string[];languageChoiceCount?:number;traits:Feature[];subraces:SubraceOption[]}
export interface SubraceOption{id:string;name:string;abilityBonuses:Partial<Record<Ability,number>>;fixedSkillProficiencies?:Skill[];speed?:number;darkvision?:number;languages?:string[];languageChoiceCount?:number;traits:Feature[]}
const t=(id:string,name:string,description:string):Feature=>({id,name,description,source:'species',level:1});
const sub=(id:string,name:string,abilityBonuses:Partial<Record<Ability,number>>,traits:Feature[],extra?:Partial<SubraceOption>):SubraceOption=>({id,name,abilityBonuses,traits,...extra});
export const SPECIES_DATA:SpeciesOption[]=[
{id:'dragonborn',name:'Dragonborn',source:'phb2014',abilityBonuses:{str:2,cha:1},speed:30,size:'Medium',languages:['Common','Draconic'],traits:[t('dragonborn-ancestry','Draconic Ancestry','Choose a dragon type; it determines the damage type of your Breath Weapon and damage resistance.'),t('breath-weapon','Breath Weapon','Exhale destructive energy in a 15-foot cone or 5-by-30-foot line; creatures make a Dexterity saving throw. Damage scales with level.'),t('damage-resistance','Damage Resistance','Resistance to the damage type associated with your draconic ancestry.')],subraces:[]},
{id:'dwarf',name:'Dwarf',source:'phb2014',abilityBonuses:{con:2},speed:25,size:'Medium',darkvision:60,languages:['Common','Dwarvish'],traits:[t('darkvision','Darkvision','Accustomed to life underground, you can see in darkness within 60 feet as if it were dim light.'),t('dwarven-resilience','Dwarven Resilience','Advantage on saving throws against poison and resistance to poison damage.'),t('dwarven-combat-training','Dwarven Combat Training','Proficiency with battleaxe, handaxe, light hammer and warhammer.'),t('stonecunning','Stonecunning','Double proficiency bonus on Intelligence (History) checks related to stonework.')],subraces:[sub('hill-dwarf','Hill Dwarf',{wis:1},[t('dwarven-toughness','Dwarven Toughness','Maximum hit points increase by 1, and increase by 1 again whenever you gain a level.')]),sub('mountain-dwarf','Mountain Dwarf',{str:2},[t('dwarven-armor-training','Dwarven Armor Training','Proficiency with light and medium armor.')])]},
{id:'elf',name:'Elf',source:'phb2014',abilityBonuses:{dex:2},speed:30,size:'Medium',darkvision:60,languages:['Common','Elvish'],fixedSkillProficiencies:['perception'],traits:[t('darkvision','Darkvision','See in darkness within 60 feet as if it were dim light.'),t('keen-senses','Keen Senses','Proficiency in the Perception skill.'),t('fey-ancestry','Fey Ancestry','Advantage on saves against being charmed; magic cannot put you to sleep.'),t('trance','Trance','You do not need to sleep and finish a long rest in 4 hours of meditation.')],subraces:[sub('high-elf','High Elf',{int:1},[t('elf-weapon-training','Elf Weapon Training','Proficiency with longsword, shortsword, shortbow and longbow.'),t('high-elf-cantrip','Cantrip','Know one cantrip from the wizard spell list.'),t('extra-language','Extra Language','Speak, read and write one additional language.')],{languageChoiceCount:1}),sub('wood-elf','Wood Elf',{wis:1},[t('wood-elf-speed','Fleet of Foot','Walking speed increases to 35 feet.'),t('mask-of-the-wild','Mask of the Wild','Can attempt to hide when only lightly obscured by natural phenomena.')],{speed:35}),sub('drow','Drow',{cha:1},[t('superior-darkvision','Superior Darkvision','Darkvision range is 120 feet.'),t('sunlight-sensitivity','Sunlight Sensitivity','Disadvantage on attack rolls and Wisdom (Perception) checks relying on sight in direct sunlight.'),t('drow-magic','Drow Magic','Know dancing lights; gain faerie fire at 3rd level and darkness at 5th level.')],{darkvision:120})]},
{id:'gnome',name:'Gnome',source:'phb2014',abilityBonuses:{int:2},speed:25,size:'Small',darkvision:60,languages:['Common','Gnomish'],traits:[t('gnome-darkvision','Darkvision','See in darkness within 60 feet as if it were dim light.'),t('gnome-cunning','Gnome Cunning','Advantage on Intelligence, Wisdom and Charisma saving throws against magic.')],subraces:[sub('forest-gnome','Forest Gnome',{dex:1},[t('natural-illusionist','Natural Illusionist','Know the minor illusion cantrip.'),t('speak-with-small-beasts','Speak with Small Beasts','Communicate simple ideas with Small or smaller beasts.')]),sub('rock-gnome','Rock Gnome',{con:1},[t('artificers-lore','Artificer’s Lore','Add twice proficiency bonus to Intelligence (History) checks related to magic items, alchemical objects or technological devices.'),t('tinker','Tinker','Proficiency with tinkers tools and construct tiny clockwork devices.')])]},
{id:'half-elf',name:'Half-Elf',source:'phb2014',abilityBonuses:{cha:2},abilityChoiceCount:2,abilityChoiceBonus:1,skillProficiencyChoices:2,speed:30,size:'Medium',darkvision:60,languages:['Common','Elvish'],languageChoiceCount:1,traits:[t('darkvision','Darkvision','See in darkness within 60 feet as if it were dim light.'),t('fey-ancestry','Fey Ancestry','Advantage on saves against being charmed; magic cannot put you to sleep.'),t('skill-versatility','Skill Versatility','Proficiency in two skills of your choice.')],subraces:[]},
{id:'half-orc',name:'Half-Orc',source:'phb2014',abilityBonuses:{str:2,con:1},speed:30,size:'Medium',darkvision:60,languages:['Common','Orc'],fixedSkillProficiencies:['intimidation'],traits:[t('darkvision','Darkvision','See in darkness within 60 feet as if it were dim light.'),t('menacing','Menacing','Proficiency in Intimidation.'),t('relentless-endurance','Relentless Endurance','When reduced to 0 hit points but not killed outright, drop to 1 hit point instead, once per long rest.'),t('savage-attacks','Savage Attacks','When you score a critical hit with a melee weapon attack, roll one additional weapon damage die.')],subraces:[]},
{id:'halfling',name:'Halfling',source:'phb2014',abilityBonuses:{dex:2},speed:25,size:'Small',languages:['Common','Halfling'],traits:[t('lucky','Lucky','When you roll a 1 on an attack roll, ability check or saving throw, reroll and use the new result.'),t('brave','Brave','Advantage on saving throws against being frightened.'),t('halfling-nimbleness','Halfling Nimbleness','Move through the space of any creature larger than you.')],subraces:[sub('lightfoot','Lightfoot',{cha:1},[t('naturally-stealthy','Naturally Stealthy','Can attempt to hide when obscured by a creature at least one size larger than you.')]),sub('stout','Stout',{con:1},[t('stout-resilience','Stout Resilience','Advantage on saves against poison and resistance to poison damage.')])]},
{id:'human',name:'Human',source:'phb2014',abilityBonuses:{str:1,dex:1,con:1,int:1,wis:1,cha:1},speed:30,size:'Medium',languages:['Common'],languageChoiceCount:1,traits:[t('extra-language','Extra Language','Speak, read and write one extra language.')],subraces:[]},
{id:'variant-human',name:'Variant Human',source:'phb2014',abilityBonuses:{},abilityChoiceCount:2,abilityChoiceBonus:1,skillProficiencyChoices:1,speed:30,size:'Medium',languages:['Common'],languageChoiceCount:1,traits:[t('variant-human-skill','Skill Proficiency','Proficiency in one skill of your choice.'),t('variant-human-feat','Feat','One feat of your choice.')],subraces:[]},
{id:'tiefling',name:'Tiefling',source:'phb2014',abilityBonuses:{int:1,cha:2},speed:30,size:'Medium',darkvision:60,languages:['Common','Infernal'],traits:[t('darkvision','Darkvision','See in darkness within 60 feet as if it were dim light.'),t('hellish-resistance','Hellish Resistance','Resistance to fire damage.'),t('infernal-legacy','Infernal Legacy','Know thaumaturgy; gain hellish rebuke at 3rd level and darkness at 5th level.')],subraces:[]}
];
export const SPECIES_BY_ID=Object.fromEntries(SPECIES_DATA.map(s=>[s.id,s]));
