import type {Spell} from '../types';
export const SPELLS:Spell[]=[
{id:'bless',name:'Bless',level:1,school:'Enchantment',classes:['cleric','paladin'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'Bless up to three creatures. Each target can add 1d4 to attack rolls and saving throws while the spell lasts.',higherLevels:'Target one additional creature per slot level above 1st.',source:'phb2014'},
{id:'cure-wounds',name:'Cure Wounds',level:1,school:'Evocation',classes:['bard','cleric','druid','paladin','ranger'],castingTime:'1 action',range:'Touch',components:['V','S'],duration:'Instantaneous',description:'A creature you touch regains 1d8 + your spellcasting ability modifier hit points.',higherLevels:'Healing increases by 1d8 per slot level above 1st.',source:'phb2014'},
{id:'shield-of-faith',name:'Shield of Faith',level:1,school:'Abjuration',classes:['cleric','paladin'],concentration:true,castingTime:'1 bonus action',range:'60 feet',components:['V','S','M'],duration:'Concentration, up to 10 minutes',description:'A creature within range gains a +2 bonus to AC for the duration.',source:'phb2014'},
{id:'command',name:'Command',level:1,school:'Enchantment',classes:['cleric','paladin'],castingTime:'1 action',range:'60 feet',components:['V'],duration:'1 round',description:'A creature that fails a Wisdom save follows a one-word command on its next turn, provided the command does not directly harm it.',higherLevels:'Target one additional creature per slot level above 1st.',source:'phb2014'},
{id:'wrathful-smite',name:'Wrathful Smite',level:1,school:'Evocation',classes:['paladin'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V'],duration:'Concentration, up to 1 minute',description:'Your next melee weapon hit deals 1d6 psychic damage and can frighten the target on a failed Wisdom save.',source:'phb2014'},
{id:'aid',name:'Aid',level:2,school:'Abjuration',classes:['cleric','paladin'],castingTime:'1 action',range:'30 feet',components:['V','S','M'],duration:'8 hours',description:'Up to three creatures gain 5 current and maximum hit points for the duration.',higherLevels:'Increase the hit point bonus by 5 per slot level above 2nd.',source:'phb2014'},
{id:'find-steed',name:'Find Steed',level:2,school:'Conjuration',classes:['paladin'],castingTime:'10 minutes',range:'30 feet',components:['V','S'],duration:'Instantaneous',description:'Summon a spirit that assumes the form of an unusually intelligent, loyal, and trained steed.',source:'phb2014'},
{id:'lesser-restoration',name:'Lesser Restoration',level:2,school:'Abjuration',classes:['bard','cleric','druid','paladin','ranger'],castingTime:'1 action',range:'Touch',components:['V','S'],duration:'Instantaneous',description:'End one disease or one of the blinded, deafened, paralyzed, or poisoned conditions affecting a creature.',source:'phb2014'},
{id:'magic-weapon',name:'Magic Weapon',level:2,school:'Transmutation',classes:['paladin','ranger','wizard'],concentration:true,castingTime:'1 bonus action',range:'Touch',components:['V','S'],duration:'Concentration, up to 1 hour',description:'A nonmagical weapon becomes magical and gains +1 to attack and damage rolls.',higherLevels:'The bonus becomes +2 with a 4th-level slot and +3 with a 6th-level slot.',source:'phb2014'},
{id:'dispel-magic',name:'Dispel Magic',level:3,school:'Abjuration',classes:['bard','cleric','druid','paladin','sorcerer','warlock','wizard'],castingTime:'1 action',range:'120 feet',components:['V','S'],duration:'Instantaneous',description:'End spells on a creature, object, or magical effect. Spells of 3rd level or lower end automatically; higher-level spells require a spellcasting ability check.',higherLevels:'Automatically end a spell whose level is equal to or below the slot level used.',source:'phb2014'},
{id:'revivify',name:'Revivify',level:3,school:'Necromancy',classes:['cleric','paladin'],castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'Instantaneous',description:'Return a creature that died within the last minute to life with 1 hit point. It cannot restore death from old age or missing body parts.',source:'phb2014'},
{id:'aura-of-vitality',name:'Aura of Vitality',level:3,school:'Evocation',classes:['paladin'],concentration:true,castingTime:'1 action',range:'Self',components:['V'],duration:'Concentration, up to 1 minute',description:'A 30-foot aura lets you use a bonus action each round to restore 2d6 hit points to one creature in the aura.',source:'phb2014'},
{id:'banishment',name:'Banishment',level:4,school:'Abjuration',classes:['cleric','paladin','sorcerer','warlock','wizard'],concentration:true,castingTime:'1 action',range:'60 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A creature that fails a Charisma save is banished; depending on its plane of origin, it is held in a harmless demiplane or returned home.',higherLevels:'Target one additional creature per slot level above 4th.',source:'phb2014'},
{id:'death-ward',name:'Death Ward',level:4,school:'Abjuration',classes:['cleric','paladin'],castingTime:'1 action',range:'Touch',components:['V','S'],duration:'8 hours',description:'The first time the target would drop to 0 hit points from damage, it drops to 1 instead and the spell ends. It also protects against one effect that would kill it instantly.',source:'phb2014'},
{id:'circle-of-power',name:'Circle of Power',level:5,school:'Abjuration',classes:['paladin'],concentration:true,castingTime:'1 action',range:'Self',components:['V'],duration:'Concentration, up to 10 minutes',description:'You and friendly creatures within 30 feet have advantage on saves against spells and magical effects and take no damage on a successful save when normally taking half.',source:'phb2014'}
];
