import {strict as assert} from 'node:assert';
import {ALL_SPELLS,duplicateSpellIds} from './spell-catalog';
import {CONTENT_SOURCES} from './sources';
import {eligibleClassSpells} from '../rules/spellcasting';

for(const spell of ALL_SPELLS){assert.ok(spell.source,'Every catalogued spell must declare a source');assert.ok(CONTENT_SOURCES.some(source=>source.id===spell.source),'Every spell source must be known');assert.ok(spell.id,'Every spell must have an id');assert.ok(spell.description,'Every spell must have a description');}
assert.deepEqual(duplicateSpellIds(ALL_SPELLS),[],'Runtime spell catalog must never expose duplicate ids');
assert.equal(CONTENT_SOURCES.find(s=>s.id==='phb2014')?.enabledByDefault,true);
assert.equal(CONTENT_SOURCES.find(s=>s.id==='xanathar2017')?.enabledByDefault,false);
assert.equal(CONTENT_SOURCES.find(s=>s.id==='tasha2020')?.enabledByDefault,false);

const command=ALL_SPELLS.find(s=>s.id==='command');assert.ok(command);assert.deepEqual([...command.classes].sort(),['cleric','paladin']);assert.equal(command.source,'phb2014');
const corePaladin=eligibleClassSpells(ALL_SPELLS,'paladin',['phb2014']).map(s=>s.id);
const expectedCore=['bless','command','compelled-duel','cure-wounds','detect-evil-and-good','detect-magic','detect-poison-and-disease','divine-favor','heroism','protection-from-evil-and-good','purify-food-and-drink','searing-smite','shield-of-faith','thunderous-smite','wrathful-smite','aid','branding-smite','find-steed','lesser-restoration','locate-object','magic-weapon','protection-from-poison','zone-of-truth','aura-of-vitality','blinding-smite','create-food-and-water','crusaders-mantle','daylight','dispel-magic','elemental-weapon','magic-circle','remove-curse','revivify','aura-of-life','aura-of-purity','banishment','death-ward','locate-creature','banishing-smite','circle-of-power','destructive-wave','dispel-evil-and-good','geas','raise-dead'];
assert.equal(corePaladin.length,expectedCore.length);for(const id of expectedCore)assert.ok(corePaladin.includes(id),`Missing PHB paladin spell: ${id}`);

const xanatharIds=['control-flames','create-bonfire','frostbite','gust','infestation','magic-stone','mold-earth','primal-savagery','shape-water','thunderclap','toll-the-dead','word-of-radiance','absorb-elements','catapult','cause-fear','ceremony','chaos-bolt','earth-tremor','ice-knife','snare','zephyr-strike','aganazzars-scorcher','dragon-breath','dust-devil','earthbind','healing-spirit','maximilians-earthen-grasp','mind-spike','pyrotechnics','shadow-blade','skywrite','snillocs-snowball-swarm','warding-wind','catnap','enemies-abound','erupting-earth','flame-arrows','life-transference','melfs-minute-meteors','summon-lesser-demons','thunder-step','tidal-wave','tiny-servant','wall-of-sand','wall-of-water','charm-monster','elemental-bane','guardian-of-nature','sickening-radiance','shadow-of-moil','storm-sphere','summon-greater-demon','vitriolic-sphere','watery-sphere','control-winds','danse-macabre','enervation','far-step','immolation','infernal-calling','negative-energy-flood','skill-empowerment','steel-wind-strike','synaptic-static','transmute-rock','wall-of-light','wrath-of-nature','bones-of-the-earth','create-homunculus','investiture-of-flame','investiture-of-ice','investiture-of-stone','investiture-of-wind','mental-prison','scatter','soul-cage','whirlwind','crown-of-stars','power-word-pain','temple-of-the-gods','abi-dalzims-horrid-wilting','illusory-dragon','maddening-darkness','mighty-fortress','mass-polymorph','psychic-scream','beast-bond','dawn','holy-weapon','maelstrom','druid-grove','primordial-ward','tensers-transformation','invulnerability','find-greater-steed'];
assert.equal(xanatharIds.length,95);assert.equal(ALL_SPELLS.filter(s=>s.source==='xanathar2017').length,95,'Xanathar must expose exactly 95 unique spells');
for(const id of xanatharIds){const spell=ALL_SPELLS.find(s=>s.id===id);assert.ok(spell,`Missing Xanathar spell: ${id}`);assert.equal(spell?.source,'xanathar2017');}
assert.deepEqual(duplicateSpellIds(ALL_SPELLS.filter(s=>s.source==='xanathar2017')),[],'Xanathar catalog contains duplicate ids');
const xanPaladin=eligibleClassSpells(ALL_SPELLS,'paladin',['phb2014','xanathar2017']).map(s=>s.id);for(const id of ['ceremony','find-greater-steed','holy-weapon'])assert.ok(xanPaladin.includes(id),`Missing Xanathar paladin spell: ${id}`);
const xanRanger=eligibleClassSpells(ALL_SPELLS,'ranger',['phb2014','xanathar2017']).map(s=>s.id);for(const id of ['absorb-elements','beast-bond','snare','zephyr-strike','healing-spirit','flame-arrows','guardian-of-nature','steel-wind-strike','wrath-of-nature'])assert.ok(xanRanger.includes(id),`Missing Xanathar ranger spell: ${id}`);
const xanDruid=eligibleClassSpells(ALL_SPELLS,'druid',['phb2014','xanathar2017']).map(s=>s.id);for(const id of ['beast-bond','healing-spirit','maelstrom','druid-grove','primordial-ward','whirlwind'])assert.ok(xanDruid.includes(id),`Missing Xanathar druid spell: ${id}`);
const xanWizard=eligibleClassSpells(ALL_SPELLS,'wizard',['phb2014','xanathar2017']).map(s=>s.id);for(const id of ['dawn','tensers-transformation','invulnerability','mighty-fortress','illusory-dragon'])assert.ok(xanWizard.includes(id),`Missing Xanathar wizard spell: ${id}`);
const withoutXanathar=eligibleClassSpells(ALL_SPELLS,'paladin',['phb2014']).map(s=>s.id);for(const id of ['ceremony','find-greater-steed','holy-weapon'])assert.ok(!withoutXanathar.includes(id),`Xanathar spell leaked into core list: ${id}`);

const tashaIds=['booming-blade','green-flame-blade','lightning-lure','mind-sliver','sword-burst','tashas-caustic-brew','summon-beast','tashas-mind-whip','summon-shadowspawn','summon-fey','summon-undead','intellect-fortress','spirit-shroud','summon-aberration','summon-construct','summon-elemental','summon-celestial','tashas-otherworldly-guise','summon-fiend','dream-of-the-blue-veil','blade-of-disaster'];
assert.equal(tashaIds.length,21,'Tasha chapter 3 new-spell list must contain 21 spells');
assert.equal(ALL_SPELLS.filter(s=>s.source==='tasha2020').length,24,'Tasha source catalog must contain 21 chapter 3 spells plus 3 optional paladin additions');
for(const id of tashaIds){const spell=ALL_SPELLS.find(s=>s.id===id);assert.ok(spell,`Missing Tasha spell: ${id}`);assert.equal(spell?.source,'tasha2020');}
for(const id of ['prayer-of-healing','gentle-repose','warding-bond']){const spell=ALL_SPELLS.find(s=>s.id===id);assert.ok(spell,`Missing Tasha additional paladin spell: ${id}`);assert.equal(spell?.source,'tasha2020');assert.ok(spell.classes.includes('paladin'));}
const corePaladinWithTasha=eligibleClassSpells(ALL_SPELLS,'paladin',['phb2014','tasha2020']).map(s=>s.id);for(const id of ['spirit-shroud','summon-celestial','prayer-of-healing','gentle-repose','warding-bond'])assert.ok(corePaladinWithTasha.includes(id),`Missing Tasha paladin spell: ${id}`);
const corePaladinWithoutTasha=eligibleClassSpells(ALL_SPELLS,'paladin',['phb2014']).map(s=>s.id);for(const id of ['spirit-shroud','summon-celestial','prayer-of-healing','gentle-repose','warding-bond'])assert.ok(!corePaladinWithoutTasha.includes(id),`Tasha spell leaked into core paladin list: ${id}`);
console.log('Spell/content-source/duplicate invariants passed');
