import type {Spell} from '../types';

const phb=(spell:Spell):Spell=>({...spell,source:'phb2014'});

/** PHB 2014 spells referenced by subclass spell lists that are not part of the current base spell catalog yet. */
export const SUBCLASS_CANONICAL_SPELLS:Spell[]=[
 phb({id:'sanctuary',name:'Sanctuary',level:1,school:'Abjuration',classes:['cleric'],castingTime:'1 bonus action',range:'30 feet',components:['V','S','M'],duration:'1 minute',description:'You ward a creature within range against attack. A creature that targets the warded creature with an attack or harmful spell must make a Wisdom saving throw or choose a new target, subject to the spell’s restrictions. The ward ends if the protected creature makes an attack or casts a spell that affects an enemy.'}),
 phb({id:'ensnaring-strike',name:'Ensnaring Strike',level:1,school:'Conjuration',classes:['ranger'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V'],duration:'Concentration, up to 1 minute',description:'The next time you hit a creature with a weapon attack before the spell ends, thorny vines restrain it on a failed Strength save and deal piercing damage at the start of its turns until it escapes or the spell ends.'}),
 phb({id:'heroism',name:'Heroism',level:1,school:'Enchantment',classes:['bard','paladin'],concentration:true,castingTime:'1 action',range:'Touch',components:['V','S'],duration:'Concentration, up to 1 minute',description:'A willing creature you touch is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier at the start of each of its turns.'}),
 phb({id:'moonbeam',name:'Moonbeam',level:2,school:'Evocation',classes:['druid'],concentration:true,castingTime:'1 action',range:'120 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder. Creatures entering it for the first time on a turn or starting there make Constitution saves, taking 2d10 radiant damage on a failure or half on a success. Shapechangers have disadvantage and revert on a failure. You can move the beam on later turns.'}),
 phb({id:'beacon-of-hope',name:'Beacon of Hope',level:3,school:'Abjuration',classes:['cleric'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V','S'],duration:'Concentration, up to 1 minute',description:'Chosen creatures gain advantage on Wisdom and death saving throws and regain the maximum possible hit points from healing.'}),
 phb({id:'freedom-of-movement',name:'Freedom of Movement',level:4,school:'Abjuration',classes:['bard','cleric','druid','ranger'],castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'1 hour',description:'The target ignores difficult terrain, has its speed unaffected by magical effects, can escape nonmagical restraints with 5 feet of movement, and cannot be paralyzed or restrained by magic.'}),
 phb({id:'guardian-of-faith',name:'Guardian of Faith',level:4,school:'Conjuration',classes:['cleric'],castingTime:'1 action',range:'30 feet',components:['V'],duration:'8 hours',description:'You summon a spectral guardian that attacks hostile creatures entering its range, dealing radiant damage on a failed Dexterity save or half on a success, until its damage limit is reached.'}),
 phb({id:'commune',name:'Commune',level:5,school:'Divination',classes:['cleric'],ritual:true,castingTime:'1 minute',range:'Self',components:['V','S','M'],duration:'1 minute',description:'You contact your deity or divine proxy and ask up to three questions that can be answered yes or no, receiving truthful answers unless the power does not know.'}),
 phb({id:'flame-strike',name:'Flame Strike',level:5,school:'Evocation',classes:['cleric'],castingTime:'1 action',range:'60 feet',components:['V','S','M'],duration:'Instantaneous',description:'A column of divine fire fills a cylinder. Creatures make Dexterity saves, taking fire and radiant damage on a failure or half on a success.',higherLevels:'The fire or radiant damage increases by 1d6 for each slot level above 5th.'}),
 phb({id:'misty-step',name:'Misty Step',level:2,school:'Conjuration',classes:['sorcerer','warlock','wizard'],castingTime:'1 bonus action',range:'Self',components:['V'],duration:'Instantaneous',description:'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.'}),
 phb({id:'plant-growth',name:'Plant Growth',level:3,school:'Transmutation',classes:['bard','druid','ranger'],castingTime:'1 action',range:'150 feet',components:['V','S'],duration:'Instantaneous',description:'This spell channels vitality into plants. A 100-foot-radius area can become overgrown and difficult terrain, or vegetation can be enriched depending on the casting option.'}),
 phb({id:'protection-from-energy',name:'Protection from Energy',level:3,school:'Abjuration',classes:['cleric','druid','ranger','sorcerer','wizard'],concentration:true,castingTime:'1 action',range:'Touch',components:['V','S'],duration:'Concentration, up to 1 hour',description:'The willing creature you touch gains resistance to one damage type: acid, cold, fire, lightning, or thunder.'}),
 phb({id:'ice-storm',name:'Ice Storm',level:4,school:'Evocation',classes:['druid','sorcerer','wizard'],castingTime:'1 action',range:'300 feet',components:['V','S','M'],duration:'Instantaneous',description:'Hail crashes down in a cylinder, dealing bludgeoning and cold damage and turning the area into difficult terrain temporarily.'}),
 phb({id:'stoneskin',name:'Stoneskin',level:4,school:'Transmutation',classes:['druid','ranger','sorcerer','wizard'],concentration:true,castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'The willing creature you touch gains resistance to nonmagical bludgeoning, piercing, and slashing damage.'}),
 phb({id:'commune-with-nature',name:'Commune with Nature',level:5,school:'Divination',classes:['druid','ranger'],ritual:true,castingTime:'1 minute',range:'Self',components:['V','S'],duration:'Instantaneous',description:'You briefly become one with nature and gain knowledge of the surrounding terrain and significant natural features and creatures within the spell’s area.'}),
 phb({id:'tree-stride',name:'Tree Stride',level:5,school:'Conjuration',classes:['druid','ranger'],concentration:true,castingTime:'1 action',range:'Self',components:['V','S'],duration:'Concentration, up to 1 minute',description:'You gain the ability to enter a tree and move from inside one tree to another of the same kind within the spell’s limits.'}),
 phb({id:'enhance-ability',name:'Enhance Ability',level:2,school:'Transmutation',classes:['bard','cleric','druid','sorcerer'],concentration:true,castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You touch a creature and grant it an enhancement to one ability, providing advantage on checks using that ability and an additional benefit depending on the chosen enhancement.'}),
 phb({id:'haste',name:'Haste',level:3,school:'Transmutation',classes:['sorcerer','wizard'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'The willing target gains doubled speed, a bonus to AC, advantage on Dexterity saves, and an additional action with limited uses. When the spell ends, the target cannot move or act until after its next turn.'}),
 phb({id:'compulsion',name:'Compulsion',level:4,school:'Enchantment',classes:['bard'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V','S'],duration:'Concentration, up to 1 minute',description:'Creatures of your choice within range that fail a Wisdom save are compelled to move in a direction you choose on their turns, subject to the spell’s restrictions.'}),
 phb({id:'alarm',name:'Alarm',level:1,school:'Abjuration',classes:['ranger','wizard'],ritual:true,castingTime:'1 minute',range:'30 feet',components:['V','S','M'],duration:'8 hours',description:'You set an alarm against unwanted intrusion into a door, window, or area. You can choose a mental or audible alarm and define conditions for triggering it.'}),
 phb({id:'detect-magic',name:'Detect Magic',level:1,school:'Divination',classes:['bard','cleric','druid','paladin','ranger','sorcerer','wizard'],ritual:true,concentration:true,castingTime:'1 action',range:'Self',components:['V','S'],duration:'Concentration, up to 10 minutes',description:'You sense the presence of magic within 30 feet and can use an action to see a faint aura around a visible magical creature or object and learn its school, if any.'}),
 phb({id:'see-invisibility',name:'See Invisibility',level:2,school:'Divination',classes:['bard','sorcerer','wizard'],castingTime:'1 action',range:'Self',components:['V','S','M'],duration:'1 hour',description:'For the duration, you see invisible creatures and objects as if they were visible and can see into the Ethereal Plane within the spell’s range.'}),
 phb({id:'counterspell',name:'Counterspell',level:3,school:'Abjuration',classes:['sorcerer','warlock','wizard'],castingTime:'1 reaction',range:'60 feet',components:['S'],duration:'Instantaneous',description:'You attempt to interrupt a creature in the process of casting a spell. A spell of 3rd level or lower fails automatically; higher-level spells require an ability check as specified by the spell.'}),
 phb({id:'nondetection',name:'Nondetection',level:3,school:'Abjuration',classes:['bard','ranger','wizard'],castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'8 hours',description:'You hide the target from divination magic. The target cannot be targeted by such magic or perceived through magical scrying sensors for the duration.'}),
 phb({id:'hold-monster',name:'Hold Monster',level:5,school:'Enchantment',classes:['bard','sorcerer','warlock','wizard'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A creature you can see that fails a Wisdom saving throw is paralyzed for the duration and can repeat the save at the end of each of its turns.'}),
 phb({id:'scrying',name:'Scrying',level:5,school:'Divination',classes:['bard','cleric','druid','warlock','wizard'],concentration:true,castingTime:'10 minutes',range:'Self',components:['V','S','M'],duration:'Concentration, up to 10 minutes',description:'You can see and hear a particular creature or location through a magical sensor, subject to familiarity, saving throws, and the spell’s restrictions.'}),
];
