export interface SubclassDefinition{id:string;name:string;source:'phb2014'|'xanathar2017'|'tasha2020';subclassLevel:number}
export const EXPANSION_SUBCLASSES:Record<string,SubclassDefinition[]>={
barbarian:[{id:'ancestral-guardian',name:'Path of the Ancestral Guardian',source:'xanathar2017',subclassLevel:3},{id:'storm-herald',name:'Path of the Storm Herald',source:'xanathar2017',subclassLevel:3},{id:'zealot',name:'Path of the Zealot',source:'xanathar2017',subclassLevel:3},{id:'beast',name:'Path of the Beast',source:'tasha2020',subclassLevel:3},{id:'wild-magic',name:'Path of Wild Magic',source:'tasha2020',subclassLevel:3}],
bard:[{id:'whispers',name:'College of Whispers',source:'xanathar2017',subclassLevel:3},{id:'glamour',name:'College of Glamour',source:'xanathar2017',subclassLevel:3},{id:'swords',name:'College of Swords',source:'xanathar2017',subclassLevel:3},{id:'eloquence',name:'College of Eloquence',source:'tasha2020',subclassLevel:3},{id:'creation',name:'College of Creation',source:'tasha2020',subclassLevel:3}],
cleric:[{id:'forge',name:'Forge Domain',source:'xanathar2017',subclassLevel:1},{id:'grave',name:'Grave Domain',source:'xanathar2017',subclassLevel:1},{id:'twilight',name:'Twilight Domain',source:'tasha2020',subclassLevel:1},{id:'order',name:'Order Domain',source:'tasha2020',subclassLevel:1},{id:'peace',name:'Peace Domain',source:'tasha2020',subclassLevel:1}],
druid:[{id:'dreams',name:'Circle of Dreams',source:'xanathar2017',subclassLevel:2},{id:'shepherd',name:'Circle of the Shepherd',source:'xanathar2017',subclassLevel:2},{id:'wildfire',name:'Circle of Wildfire',source:'tasha2020',subclassLevel:2},{id:'spores',name:'Circle of Spores',source:'tasha2020',subclassLevel:2},{id:'stars',name:'Circle of Stars',source:'tasha2020',subclassLevel:2}],
fighter:[{id:'arcane-archer',name:'Arcane Archer',source:'xanathar2017',subclassLevel:3},{id:'cavalier',name:'Cavalier',source:'xanathar2017',subclassLevel:3},{id:'samurai',name:'Samurai',source:'xanathar2017',subclassLevel:3},{id:'echo-knight',name:'Echo Knight',source:'tasha2020',subclassLevel:3},{id:'psi-warrior',name:'Psi Warrior',source:'tasha2020',subclassLevel:3},{id:'rune-knight',name:'Rune Knight',source:'tasha2020',subclassLevel:3}],
monk:[{id:'kensei',name:'Way of the Kensei',source:'xanathar2017',subclassLevel:3},{id:'drunken-master',name:'Way of the Drunken Master',source:'xanathar2017',subclassLevel:3},{id:'sun-soul',name:'Way of the Sun Soul',source:'xanathar2017',subclassLevel:3},{id:'astral-self',name:'Way of the Astral Self',source:'tasha2020',subclassLevel:3},{id:'mercy',name:'Way of Mercy',source:'tasha2020',subclassLevel:3}],
paladin:[{id:'conquest',name:'Oath of Conquest',source:'xanathar2017',subclassLevel:3},{id:'redemption',name:'Oath of Redemption',source:'xanathar2017',subclassLevel:3},{id:'watchers',name:'Oath of the Watchers',source:'tasha2020',subclassLevel:3},{id:'glory',name:'Oath of Glory',source:'tasha2020',subclassLevel:3}],
ranger:[{id:'gloom-stalker',name:'Gloom Stalker',source:'xanathar2017',subclassLevel:3},{id:'monster-slayer',name:'Monster Slayer',source:'xanathar2017',subclassLevel:3},{id:'horizon-walker',name:'Horizon Walker',source:'xanathar2017',subclassLevel:3},{id:'swarmkeeper',name:'Swarmkeeper',source:'tasha2020',subclassLevel:3},{id:'fey-wanderer',name:'Fey Wanderer',source:'tasha2020',subclassLevel:3},{id:'beast-master-tasha',name:'Beast Master (Primal Companion)',source:'tasha2020',subclassLevel:3}],
rogue:[{id:'scout',name:'Scout',source:'xanathar2017',subclassLevel:3},{id:'inquisitive',name:'Inquisitive',source:'xanathar2017',subclassLevel:3},{id:'mastermind',name:'Mastermind',source:'xanathar2017',subclassLevel:3},{id:'swashbuckler',name:'Swashbuckler',source:'xanathar2017',subclassLevel:3}],
sorcerer:[{id:'divine-soul',name:'Divine Soul',source:'xanathar2017',subclassLevel:1},{id:'shadow-magic',name:'Shadow Magic',source:'xanathar2017',subclassLevel:1},{id:'storm-sorcery',name:'Storm Sorcery',source:'xanathar2017',subclassLevel:1}],
warlock:[{id:'celestial',name:'The Celestial',source:'xanathar2017',subclassLevel:1},{id:'hexblade',name:'The Hexblade',source:'xanathar2017',subclassLevel:1}],
wizard:[{id:'war-magic',name:'War Magic',source:'xanathar2017',subclassLevel:2},{id:'bladesinging',name:'Bladesinging',source:'tasha2020',subclassLevel:2},{id:'order-of-scribes',name:'Order of Scribes',source:'tasha2020',subclassLevel:2}]
};
