import type {Spell} from '../types';

const phb=(spell:Spell):Spell=>({...spell,source:'phb2014'});

/** Additional PHB 2014 records referenced by subclass spell access and absent from the base canonical catalog. */
export const SUBCLASS_CANONICAL_SPELLS_EXTRA:Spell[]=[
 phb({id:'bane',name:'Bane',level:1,school:'Enchantment',classes:['bard','cleric'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'Up to three creatures of your choice within range that can see or hear you make Charisma saving throws. A target that fails subtracts 1d4 from attack rolls and saving throws for the duration.'}),
 phb({id:'speak-with-animals',name:'Speak with Animals',level:1,school:'Divination',classes:['bard','druid','ranger'],ritual:true,castingTime:'1 action',range:'Self',components:['V','S'],duration:'10 minutes',description:'You gain the ability to comprehend and verbally communicate with beasts for the duration. The knowledge and awareness of many beasts is limited by their intelligence, but they can give you information about nearby locations and monsters and can perceive things since the last day.'}),
 phb({id:'hunters-mark',name:'Hunter’s Mark',level:1,school:'Divination',classes:['ranger'],concentration:true,castingTime:'1 bonus action',range:'90 feet',components:['V'],duration:'Concentration, up to 1 hour',description:'You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on Wisdom (Perception or Survival) checks to find it. If the target drops to 0 hit points, you can use a bonus action on a subsequent turn to mark a new creature.',higherLevels:'When you cast this spell using a 3rd- or 4th-level spell slot, you can maintain concentration for up to 8 hours. When you use a 5th-level or higher slot, you can maintain concentration for up to 24 hours.'}),
 phb({id:'guiding-bolt',name:'Guiding Bolt',level:1,school:'Evocation',classes:['cleric'],castingTime:'1 action',range:'120 feet',components:['V','S'],duration:'1 round',description:'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against it before the end of your next turn has advantage as dim mystical light clings to the target.',higherLevels:'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.'}),
 phb({id:'dimension-door',name:'Dimension Door',level:4,school:'Conjuration',classes:['bard','sorcerer','warlock','wizard'],castingTime:'1 action',range:'500 feet',components:['V'],duration:'Instantaneous',description:'You teleport from your current location to any other spot within range. You arrive exactly at the desired spot, which can be a place you can see or one you can describe by stating its distance and direction. You can bring along objects you can carry and one willing creature of your size or smaller that is within 5 feet of you. If you arrive in a place already occupied by an object or creature, you and any creature traveling with you each take 4d6 force damage and the teleportation fails.'}),
 phb({id:'aura-of-purity',name:'Aura of Purity',level:4,school:'Abjuration',classes:['cleric','paladin'],concentration:true,castingTime:'1 action',range:'Self (30-foot radius)',components:['V'],duration:'Concentration, up to 10 minutes',description:'You radiate a purifying aura in a 30-foot radius centered on you. Until the spell ends, the aura moves with you. Each nonhostile creature in the aura, including you, cannot become diseased, has resistance to poison damage, and has advantage on saving throws against effects that cause the blinded, charmed, deafened, frightened, paralyzed, poisoned, or stunned conditions.'}),
];
