import type {Spell} from '../types';

const phb=(spell:Spell):Spell=>({...spell,source:'phb2014'});

/** PHB 2014 spells referenced by subclass spell lists that are not part of the current base spell catalog yet. */
export const SUBCLASS_CANONICAL_SPELLS:Spell[]=[
 phb({id:'sanctuary',name:'Sanctuary',level:1,school:'Abjuration',classes:['cleric'],castingTime:'1 bonus action',range:'30 feet',components:['V','S','M'],duration:'1 minute',description:'You ward a creature within range against attack. A creature that targets the warded creature with an attack or harmful spell must make a Wisdom saving throw or choose a new target, subject to the spell’s restrictions. The ward ends if the protected creature makes an attack or casts a spell that affects an enemy.'}),
 phb({id:'ensnaring-strike',name:'Ensnaring Strike',level:1,school:'Conjuration',classes:['ranger'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V'],duration:'Concentration, up to 1 minute',description:'The next time you hit a creature with a weapon attack before the spell ends, a mass of thorny vines appears at the point of impact. The target must succeed on a Strength saving throw or be restrained and take 1d6 piercing damage at the start of each of its turns until it escapes or the spell ends. A creature can use its action to make a Strength check against your spell save DC to escape.'}),
 phb({id:'moonbeam',name:'Moonbeam',level:2,school:'Evocation',classes:['druid'],concentration:true,castingTime:'1 action',range:'120 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder. When a creature enters the area for the first time on a turn or starts its turn there, it must make a Constitution saving throw, taking 2d10 radiant damage on a failed save or half as much on a success. A shapechanger makes the saving throw with disadvantage and reverts to its true form on a failure. On subsequent turns, you can use an action to move the beam up to 60 feet.'}),
 phb({id:'beacon-of-hope',name:'Beacon of Hope',level:3,school:'Abjuration',classes:['cleric'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V','S'],duration:'Concentration, up to 1 minute',description:'Your spell bestows hope and vitality. Choose any number of creatures within range. Each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum possible number of hit points from any healing.'}),
 phb({id:'freedom-of-movement',name:'Freedom of Movement',level:4,school:'Abjuration',classes:['bard','cleric','druid','ranger'],castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'1 hour',description:'The touched creature is unaffected by difficult terrain, has its speed unaffected by magical effects, can spend 5 feet of movement to escape nonmagical restraints, and cannot be paralyzed or restrained by magic.'}),
 phb({id:'guardian-of-faith',name:'Guardian of Faith',level:4,school:'Conjuration',classes:['cleric'],castingTime:'1 action',range:'30 feet',components:['V'],duration:'8 hours',description:'You summon a spectral guardian in an unoccupied space. It remains there and attacks hostile creatures that enter its range, dealing 20 radiant damage on a failed Dexterity saving throw or half as much on a success. The guardian can deal a total of 60 damage before disappearing.'}),
 phb({id:'commune',name:'Commune',level:5,school:'Divination',classes:['cleric'],ritual:true,castingTime:'1 minute',range:'Self',components:['V','S','M'],duration:'1 minute',description:'You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no. The spell provides correct answers unless the divine power does not know the information.'}),
 phb({id:'flame-strike',name:'Flame Strike',level:5,school:'Evocation',classes:['cleric'],castingTime:'1 action',range:'60 feet',components:['V','S','M'],duration:'Instantaneous',description:'A vertical column of divine fire roars down in a cylinder. Creatures in the area make Dexterity saving throws, taking 4d6 fire damage and 4d6 radiant damage on a failure, or half as much on a success.',higherLevels:'The fire or radiant damage increases by 1d6 for each slot level above 5th.'}),
];
