import type {Spell} from '../types';
const tasha=(spell:Spell):Spell=>({...spell,source:'tasha2020'});
/** Tasha's Cauldron of Everything, chapter 3: new spells only. Class access follows the source table. */
export const TASHA_SPELLS:Spell[]=[
 tasha({id:'booming-blade',name:'Booming Blade',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (5-foot radius)',components:['S','M'],duration:'1 round',description:'You make a melee weapon attack as part of the spell; on a hit, the target is wrapped in booming energy and can take additional thunder damage if it willingly moves before your next turn.'}),
 tasha({id:'green-flame-blade',name:'Green-Flame Blade',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (5-foot radius)',components:['S','M'],duration:'Instantaneous',description:'You make a melee weapon attack as part of the spell; on a hit, green flame leaps to another creature of your choice nearby and deals fire damage.'}),
 tasha({id:'lightning-lure',name:'Lightning Lure',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (15-foot radius)',components:['V'],duration:'Instantaneous',description:'A creature you can see within range makes a Strength save or is pulled up to 10 feet toward you and takes lightning damage if it ends within 5 feet of you.'}),
 tasha({id:'mind-sliver',name:'Mind Sliver',level:0,school:'Enchantment',classes:['wizard','sorcerer','warlock'],castingTime:'1 action',range:'60 feet',components:['V'],duration:'1 round',description:'A creature makes an Intelligence save or takes psychic damage and subtracts 1d4 from its next saving throw before the end of your next turn.'}),
 tasha({id:'sword-burst',name:'Sword Burst',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (5-foot radius)',components:['V'],duration:'Instantaneous',description:'Spectral blades surround you; creatures of your choice within 5 feet make Dexterity saves and take force damage on failures.'}),
 tasha({id:'tashas-caustic-brew',name:"Tasha's Caustic Brew",level:1,school:'Evocation',classes:['artificer','wizard','sorcerer'],concentration:true,castingTime:'1 action',range:'Self (30-foot line)',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A line of acid sprays from you; creatures in the line make Dexterity saves and a failed target takes acid damage and can continue taking damage until the acid is removed.'}),
 tasha({id:'summon-beast',name:'Summon Beast',level:2,school:'Conjuration',classes:['druid','ranger'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a beast spirit using the Beast Spirit statistics; it acts immediately after your turn and follows your verbal commands.'}),
 tasha({id:'tashas-mind-whip',name:"Tasha's Mind Whip",level:2,school:'Enchantment',classes:['wizard','sorcerer'],castingTime:'1 action',range:'90 feet',components:['V'],duration:'1 round',description:'A creature makes an Intelligence save, taking psychic damage on a failure and being limited to one of movement, an action, or a bonus action on its next turn.'}),
 tasha({id:'summon-shadowspawn',name:'Summon Shadowspawn',level:3,school:'Conjuration',classes:['wizard','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a shadow spirit whose chosen emotional form determines features of its statistics.'}),
 tasha({id:'summon-fey',name:'Summon Fey',level:3,school:'Conjuration',classes:['druid','wizard','ranger','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a fey spirit whose chosen emotional form determines features of its statistics.'}),
 tasha({id:'summon-undead',name:'Summon Undead',level:3,school:'Necromancy',classes:['wizard','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon an undead spirit whose chosen form determines features of its statistics.'}),
 tasha({id:'intellect-fortress',name:'Intellect Fortress',level:3,school:'Abjuration',classes:['artificer','bard','wizard','sorcerer','warlock'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V'],duration:'Concentration, up to 1 hour',description:'Up to three willing creatures gain resistance to psychic damage and advantage on Intelligence, Wisdom, and Charisma saving throws.'}),
 tasha({id:'spirit-shroud',name:'Spirit Shroud',level:3,school:'Necromancy',classes:['cleric','wizard','paladin','warlock'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V','S'],duration:'Concentration, up to 1 minute',description:'Spirits surround you, causing your attacks to deal extra damage, preventing hit-point recovery from your attacks, and reducing the speed of nearby creatures.'}),
 tasha({id:'summon-aberration',name:'Summon Aberration',level:4,school:'Conjuration',classes:['wizard','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon an aberrant spirit whose chosen form determines features of its statistics.'}),
 tasha({id:'summon-construct',name:'Summon Construct',level:4,school:'Conjuration',classes:['artificer','wizard'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a construct spirit using the Construct Spirit statistics.'}),
 tasha({id:'summon-elemental',name:'Summon Elemental',level:4,school:'Conjuration',classes:['druid','wizard','ranger'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon an elemental spirit; its elemental form determines damage and movement traits.'}),
 tasha({id:'summon-celestial',name:'Summon Celestial',level:5,school:'Conjuration',classes:['cleric','paladin'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a celestial spirit whose form determines additional abilities.'}),
 tasha({id:'tashas-otherworldly-guise',name:"Tasha's Otherworldly Guise",level:6,school:'Transmutation',classes:['wizard','sorcerer','warlock'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'You draw on the magic of an Upper or Lower Plane and gain planar combat benefits, including enhanced attacks and defenses.'}),
 tasha({id:'summon-fiend',name:'Summon Fiend',level:6,school:'Conjuration',classes:['wizard','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a fiendish spirit whose chosen form determines additional abilities.'}),
 tasha({id:'dream-of-the-blue-veil',name:'Dream of the Blue Veil',level:7,school:'Conjuration',classes:['bard','wizard','sorcerer','warlock'],castingTime:'10 minutes',range:'20 feet',components:['V','S','M'],duration:'6 hours',description:'You and willing creatures enter a magical slumber and project into another world of the Material Plane known to you.'}),
 tasha({id:'blade-of-disaster',name:'Blade of Disaster',level:9,school:'Conjuration',classes:['wizard','sorcerer','warlock'],concentration:true,castingTime:'1 bonus action',range:'60 feet',components:['V','S'],duration:'Concentration, up to 1 minute',description:'You create a planar blade that can be moved and used for spell attacks; critical hits deal devastating additional damage and the blade can pass through barriers.'}),
];