import type {Spell} from '../types';

const tasha=(spell:Spell):Spell=>({...spell,source:'tasha2020'});

/** Tasha's Cauldron of Everything, chapter 3: new spells only. */
export const TASHA_SPELLS:Spell[]=[
 tasha({id:'booming-blade',name:'Booming Blade',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (5-foot radius)',components:['S','M'],duration:'1 round',description:'You make a melee weapon attack as part of the spell. On a hit, the target suffers the weapon attack normally and is sheathed in booming energy; if it willingly moves before your next turn, it takes additional thunder damage.'}),
 tasha({id:'green-flame-blade',name:'Green-Flame Blade',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (5-foot radius)',components:['S','M'],duration:'Instantaneous',description:'You make a melee weapon attack as part of the spell. On a hit, green flame leaps from the target to another creature of your choice within range and deals fire damage to it.'}),
 tasha({id:'lightning-lure',name:'Lightning Lure',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (15-foot radius)',components:['V'],duration:'Instantaneous',description:'Lightning lashes a creature you can see within range. It makes a Strength save; on a failure it is pulled up to 10 feet toward you and takes lightning damage if it ends within 5 feet of you.'}),
 tasha({id:'mind-sliver',name:'Mind Sliver',level:0,school:'Enchantment',classes:['wizard','sorcerer','warlock'],castingTime:'1 action',range:'60 feet',components:['V'],duration:'1 round',description:'One creature in range makes an Intelligence save. On a failure it takes psychic damage and subtracts 1d4 from the next saving throw it makes before the end of your next turn.'}),
 tasha({id:'sword-burst',name:'Sword Burst',level:0,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],castingTime:'1 action',range:'Self (5-foot radius)',components:['V'],duration:'Instantaneous',description:'Spectral blades briefly appear around you. Creatures of your choice within 5 feet make a Dexterity save and take force damage on a failure.'}),
 tasha({id:'tashas-caustic-brew',name:"Tasha's Caustic Brew",level:1,school:'Evocation',classes:['artificer','wizard','sorcerer','warlock'],concentration:true,castingTime:'1 action',range:'Self (30-foot line)',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A line of acid sprays from you. A creature in the line makes a Dexterity save, taking acid damage on a failure and continuing to take damage at the start of its turns until it cleans itself or another creature uses an action to remove the acid.'}),
 tasha({id:'summon-beast',name:'Summon Beast',level:2,school:'Conjuration',classes:['druid','ranger'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a spirit of a beast in an unoccupied space within range. It uses the spell’s Beast Spirit statistics and acts immediately after your turn, following your verbal commands.'}),
 tasha({id:'tashas-mind-whip',name:"Tasha's Mind Whip",level:2,school:'Enchantment',classes:['wizard','sorcerer'],castingTime:'1 action',range:'90 feet',components:['V'],duration:'1 round',description:'One creature you can see makes an Intelligence save and takes psychic damage on a failure, then suffers a restriction on the options it can choose on its next turn; on a successful save it takes half damage only.'}),
 tasha({id:'summon-shadowspawn',name:'Summon Shadowspawn',level:3,school:'Conjuration',classes:['wizard','sorcerer','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a shadowy spirit that uses the Shadow Spirit statistics. You choose its emotional form when it appears, which determines features of the summoned creature.'}),
 tasha({id:'summon-fey',name:'Summon Fey',level:3,school:'Conjuration',classes:['druid','ranger','wizard','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a spirit from the Feywild that uses the Fey Spirit statistics. You choose its emotional form when it appears, which determines features of the summoned creature.'}),
 tasha({id:'summon-undead',name:'Summon Undead',level:3,school:'Necromancy',classes:['wizard','warlock'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon an undead spirit that uses the Undead Spirit statistics. You choose its form when it appears, which determines features of the summoned creature.'}),
 tasha({id:'intellect-fortress',name:'Intellect Fortress',level:3,school:'Abjuration',classes:['artificer','bard','wizard','sorcerer','warlock'],concentration:true,castingTime:'1 action',range:'30 feet',components:['V'],duration:'Concentration, up to 1 hour',description:'Up to three willing creatures within range gain resistance to psychic damage and advantage on Intelligence, Wisdom, and Charisma saving throws.'}),
 tasha({id:'spirit-shroud',name:'Spirit Shroud',level:3,school:'Necromancy',classes:['cleric','paladin'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V','S'],duration:'Concentration, up to 1 minute',description:'Spirits surround you. Your attacks deal extra damage, creatures you hit cannot regain hit points, and nearby creatures have reduced speed while within the shroud.'}),
 tasha({id:'summon-aberration',name:'Summon Aberration',level:4,school:'Conjuration',classes:['artificer','wizard'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon an aberrant spirit that uses the Aberrant Spirit statistics. Its form and some abilities depend on the type you choose when it appears.'}),
 tasha({id:'summon-construct',name:'Summon Construct',level:4,school:'Conjuration',classes:['artificer','wizard'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a construct spirit that uses the Construct Spirit statistics. Its nature determines additional features of the summoned creature.'}),
 tasha({id:'summon-elemental',name:'Summon Elemental',level:4,school:'Conjuration',classes:['druid','wizard','ranger'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon an elemental spirit that uses the Elemental Spirit statistics. Its elemental type determines its damage and movement traits.'}),
 tasha({id:'summon-celestial',name:'Summon Celestial',level:5,school:'Conjuration',classes:['cleric','paladin'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a celestial spirit that uses the Celestial Spirit statistics. Its form determines additional abilities.'}),
 tasha({id:'tashas-otherworldly-guise',name:"Tasha's Otherworldly Guise",level:6,school:'Transmutation',classes:['wizard','sorcerer','warlock'],concentration:true,castingTime:'1 bonus action',range:'Self',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'You draw on the magic of either the Upper or Lower Planes, gaining a suite of combat benefits including a flying speed, enhanced attacks, and immunities or resistances based on the chosen planar source.'}),
 tasha({id:'summon-fiend',name:'Summon Fiend',level:6,school:'Conjuration',classes:['artificer','wizard'],concentration:true,castingTime:'1 action',range:'90 feet',components:['V','S','M'],duration:'Concentration, up to 1 hour',description:'You summon a fiendish spirit that uses the Fiendish Spirit statistics. Its form determines additional abilities.'}),
 tasha({id:'dream-of-the-blue-veil',name:'Dream of the Blue Veil',level:7,school:'Conjuration',classes:['bard','wizard','sorcerer','warlock'],castingTime:'10 minutes',range:'20 feet',components:['V','S','M'],duration:'6 hours',description:'You and willing creatures fall into a magical slumber and project into another world of the Material Plane that you have heard about or know exists, arriving after the journey described by the spell.'}),
 tasha({id:'blade-of-disaster',name:'Blade of Disaster',level:9,school:'Conjuration',classes:['wizard','sorcerer','warlock'],concentration:true,castingTime:'1 bonus action',range:'60 feet',components:['V','S'],duration:'Concentration, up to 1 minute',description:'You create a blade-shaped tear in planar space that you can move and use to make spell attacks. Critical hits deal devastating extra damage and the blade can pass through barriers.'}),
];
