import type {Spell} from '../types';
const xan=(spell:Spell):Spell=>({...spell,source:'xanathar2017'});
/** Final eight entries completing Xanathar's 95-spell chapter 3 catalog. */
export const XANATHAR_SPELLS_EXTRA:Spell[]=[
 xan({id:'beast-bond',name:'Beast Bond',level:1,school:'Divination',classes:['druid','ranger'],concentration:true,castingTime:'1 action',range:'Touch',components:['V','S','M'],duration:'Concentration, up to 10 minutes',description:'You establish a telepathic link with a willing beast, allowing communication and improving the range and reliability of your perception of each other while the bond lasts.'}),
 xan({id:'dawn',name:'Dawn',level:5,school:'Evocation',classes:['cleric','wizard'],castingTime:'1 action',range:'60 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A shaft of sunlight fills a sphere and can be moved on later turns. Creatures in the light make Constitution saves or take radiant damage and suffer the spell’s ongoing effects.'}),
 xan({id:'holy-weapon',name:'Holy Weapon',level:5,school:'Evocation',classes:['cleric','paladin'],concentration:true,castingTime:'1 bonus action',range:'Touch',components:['V','S'],duration:'Concentration, up to 1 hour',description:'A weapon becomes infused with radiant power, gaining a bonus to attacks and dealing extra radiant damage. The spell can end in a burst of radiant energy that damages nearby creatures and can blind them.'}),
 xan({id:'maelstrom',name:'Maelstrom',level:5,school:'Evocation',classes:['druid'],concentration:true,castingTime:'1 action',range:'120 feet',components:['V','S','M'],duration:'Concentration, up to 1 minute',description:'A powerful whirlpool appears in water or on the ground, creating difficult terrain and pulling creatures toward its center while damaging them when they enter or end their turns there.'}),
 xan({id:'druid-grove',name:'Druid Grove',level:6,school:'Abjuration',classes:['druid'],castingTime:'10 minutes',range:'Touch',components:['V','S','M'],duration:'24 hours',description:'You protect a large area of natural terrain with a permanent magical ward and can create several supernatural features within the grove, including guardians, weather, and barriers.'}),
 xan({id:'primordial-ward',name:'Primordial Ward',level:6,school:'Abjuration',classes:['druid'],concentration:true,castingTime:'1 action',range:'Self',components:['V','S'],duration:'Concentration, up to 1 minute',description:'You gain resistance to acid, cold, fire, lightning, and thunder damage. When a resistance is triggered, you can use the stored energy to release a corresponding elemental effect.'}),
 xan({id:'tensers-transformation',name:"Tenser's Transformation",level:6,school:'Transmutation',classes:['wizard'],concentration:true,castingTime:'1 action',range:'Self',components:['V','S','M'],duration:'Concentration, up to 10 minutes',description:'You transform into a magically enhanced warrior, gaining temporary hit points, advantage on attacks, extra force damage, proficiency in weapons and armor, and other martial benefits while the transformation lasts.'}),
 xan({id:'invulnerability',name:'Invulnerability',level:9,school:'Abjuration',classes:['wizard'],concentration:true,castingTime:'1 action',range:'Self',components:['V','S','M'],duration:'Concentration, up to 10 minutes',description:'You become immune to all damage for the duration, subject to the spell’s concentration requirement and the specified interactions that can end or bypass the protection.'}),
];
