import type {SubclassFeature} from './subclassFeatures';
const f=(id:string,name:string,subclassId:string,level:number,description:string):SubclassFeature=>({id,name,subclassId,level,source:'subclass',description});
export const XANATHAR_SUBCLASS_FEATURES:SubclassFeature[]=[
// Rogue
f('rogue.scout.skirmisher','Skirmisher','rogue.scout',3,'When an enemy ends its turn within 5 feet of you, you can move up to half your speed as a reaction without provoking an opportunity attack from that creature.'),
f('rogue.scout.survivalist','Survivalist','rogue.scout',3,'You gain proficiency and expertise in Nature or Survival as specified by the feature.'),
f('rogue.scout.superior-mobility','Superior Mobility','rogue.scout',9,'Your walking speed increases by 10 feet.'),
f('rogue.scout.ambush-master','Ambush Master','rogue.scout',13,'You gain advantage on initiative rolls and can grant an ally advantage against the first creature you hit during the first round.'),
f('rogue.scout.sudden-strike','Sudden Strike','rogue.scout',17,'You can make an additional Sneak Attack against a different creature during the same turn, subject to the feature rules.'),
f('rogue.inquisitive.ear-for-deceit','Ear for Deceit','rogue.inquisitive',3,'A d20 roll of 7 or lower on a Wisdom (Insight) check to determine whether someone is lying counts as an 8.'),
f('rogue.inquisitive.eye-for-detail','Eye for Detail','rogue.inquisitive',3,'You can use a bonus action to make a Wisdom (Perception) check to spot a hidden creature or object, or an Intelligence (Investigation) check to uncover clues.'),
f('rogue.inquisitive.insightful-fighting','Insightful Fighting','rogue.inquisitive',3,'You can study a creature with an Insight check; on success, Sneak Attack applies against it without needing advantage while the feature lasts.'),
f('rogue.inquisitive.steady-eye','Steady Eye','rogue.inquisitive',9,'You gain advantage on Wisdom (Perception) or Intelligence (Investigation) checks if you move no more than half your speed.'),
f('rogue.inquisitive.unerring-eye','Unerring Eye','rogue.inquisitive',13,'You can sense magical deception and illusions within a limited range using the feature’s uses per rest.'),
f('rogue.inquisitive.eye-for-weakness','Eye for Weakness','rogue.inquisitive',17,'Your Insightful Fighting target takes extra Sneak Attack damage when you hit it.'),
f('rogue.mastermind.master-of-intrigue','Master of Intrigue','rogue.mastermind',3,'You gain proficiencies, languages, and the ability to mimic speech and writing as specified by the feature.'),
f('rogue.mastermind.master-of-tactics','Master of Tactics','rogue.mastermind',3,'You can use Help as a bonus action, including at range under the feature’s conditions.'),
f('rogue.mastermind.insightful-manipulator','Insightful Manipulator','rogue.mastermind',9,'You can assess a creature’s capabilities relative to your own after observing or interacting with it for at least 1 minute.'),
f('rogue.mastermind.misdirection','Misdirection','rogue.mastermind',13,'You can use your reaction to redirect an attack that hits you to another creature you can see, if the feature conditions are met.'),
f('rogue.mastermind.soul-of-deceit','Soul of Deceit','rogue.mastermind',17,'Your thoughts cannot be read and you can make false statements appear truthful to magic that detects lies, subject to the feature.'),
f('rogue.swashbuckler.fancy-footwork','Fancy Footwork','rogue.swashbuckler',3,'A creature you make a melee attack against cannot make opportunity attacks against you for the rest of your turn.'),
f('rogue.swashbuckler.rakish-audacity','Rakish Audacity','rogue.swashbuckler',3,'You add your Charisma modifier to initiative and can qualify for Sneak Attack while fighting a creature one-on-one.'),
f('rogue.swashbuckler.panache','Panache','rogue.swashbuckler',9,'You can use Persuasion to taunt or charm a creature, with different combat and social effects.'),
f('rogue.swashbuckler.elegant-maneuver','Elegant Maneuver','rogue.swashbuckler',13,'You can gain advantage on the next Acrobatics or Athletics check you make during the turn.'),
f('rogue.swashbuckler.master-duelist','Master Duelist','rogue.swashbuckler',17,'Once per short or long rest, you can turn a missed attack into a hit.'),
// Monk
f('monk.kensei.path-of-the-kensei','Path of the Kensei','monk.kensei',3,'You gain proficiency with chosen kensei weapons and the Agile Parry and Kensei’s Shot options.'),
f('monk.kensei.one-with-the-blade','One with the Blade','monk.kensei',6,'Your kensei weapons count as magical and you gain the Deft Strike option.'),
f('monk.kensei.sharpen-the-blade','Sharpen the Blade','monk.kensei',6,'You can expend ki to grant a kensei weapon a temporary bonus to attack and damage rolls.'),
f('monk.kensei.unerring-accuracy','Unerring Accuracy','monk.kensei',17,'Once on each of your turns, you can reroll a missed attack with a monk weapon.'),
f('monk.drunken-master.drunkard-martial-arts','Drunken Technique','monk.drunken-master',3,'Flurry of Blows also grants increased movement and removes the opportunity-attack penalty as specified.'),
f('monk.drunken-master.tipsy-sway','Tipsy Sway','monk.drunken-master',6,'You gain benefits that let you rise more easily and redirect attacks using Deflect Attack.'),
f('monk.drunken-master.drunkards-luck','Drunkard’s Luck','monk.drunken-master',11,'You can spend ki to cancel disadvantage on an ability check, attack roll, or saving throw.'),
f('monk.drunken-master.intoxicated-frenzy','Intoxicated Frenzy','monk.drunken-master',17,'When you use Flurry of Blows, you can make additional attacks against different creatures as specified.'),
f('monk.sun-soul.radiant-sun-bolt','Radiant Sun Bolt','monk.sun-soul',3,'You can make ranged spell-like attacks with radiant energy using your martial arts die.'),
f('monk.sun-soul.searing-arc-strike','Searing Arc Strike','monk.sun-soul',6,'You can cast burning hands by spending ki and use the feature’s scaling rules.'),
f('monk.sun-soul.searing-sunburst','Searing Sunburst','monk.sun-soul',11,'You can create a sphere of radiant energy that deals radiant damage on a failed Constitution saving throw.'),
f('monk.sun-soul.sun-shield','Sun Shield','monk.sun-soul',17,'You shed bright light and can use your reaction to deal radiant damage to a creature that hits you with a melee attack.'),
// Paladin
f('paladin.conquest.oath-spells','Oath Spells','paladin.conquest',3,'You gain the Oath of Conquest oath spells at the paladin levels specified by the oath.'),
f('paladin.conquest.channel-divinity','Channel Divinity','paladin.conquest',3,'You gain the Conquering Presence and Guided Strike Channel Divinity options.'),
f('paladin.conquest.aura-of-conquest','Aura of Conquest','paladin.conquest',7,'Creatures frightened by you have their speed reduced to 0 and take psychic damage while in your aura.'),
f('paladin.conquest.scornful-rebuke','Scornful Rebuke','paladin.conquest',15,'Whenever a creature hits you with an attack, it takes psychic damage based on your Charisma modifier.'),
f('paladin.conquest.invincible-conqueror','Invincible Conqueror','paladin.conquest',20,'You can assume a conquering form that grants resistance, an extra attack, and improved critical range as specified.'),
f('paladin.redemption.oath-spells','Oath Spells','paladin.redemption',3,'You gain the Oath of Redemption oath spells at the paladin levels specified by the oath.'),
f('paladin.redemption.channel-divinity','Channel Divinity','paladin.redemption',3,'You gain Emissary of Peace and Rebuke the Violent as Channel Divinity options.'),
f('paladin.redemption.aura-of-the-guardian','Aura of the Guardian','paladin.redemption',7,'You can use your reaction to take damage dealt to another creature within your aura.'),
f('paladin.redemption.protective-spirit','Protective Spirit','paladin.redemption',15,'You regain hit points at the end of your turn while below half your hit points and not incapacitated.'),
f('paladin.redemption.emissary-of-redemption','Emissary of Redemption','paladin.redemption',20,'You gain resistance to damage from other creatures and reflect damage from creatures that attack you while you remain under the feature’s conditions.'),
// Ranger
f('ranger.monster-slayer.hunters-sense','Hunter’s Sense','ranger.monster-slayer',3,'You can sense whether a creature has damage immunities, resistances, or vulnerabilities after studying it.'),
f('ranger.monster-slayer.slayers-prey','Slayer’s Prey','ranger.monster-slayer',3,'You mark one creature as your prey and deal extra weapon damage to it once per turn.'),
f('ranger.monster-slayer.supernatural-defense','Supernatural Defense','ranger.monster-slayer',7,'When your Slayer’s Prey forces you to make a saving throw or contest an ability check, you add a d6 to the result.'),
f('ranger.monster-slayer.magic-users-nemesis','Magic-User’s Nemesis','ranger.monster-slayer',11,'When a creature you can see casts a spell or teleports, you can use your reaction to force a saving throw and potentially interrupt it.'),
f('ranger.monster-slayer.slayers-counter','Slayer’s Counter','ranger.monster-slayer',15,'When your Slayer’s Prey forces you to make a saving throw or attack roll, you can use your reaction to attack the creature on a success.'),
f('ranger.horizon-walker.detect-portal','Detect Portal','ranger.horizon-walker',3,'You can magically sense the distance and direction to the nearest planar portal within range.'),
f('ranger.horizon-walker.planar-warrior','Planar Warrior','ranger.horizon-walker',3,'You can transform a weapon attack’s damage into force damage and deal extra force damage to the target.'),
f('ranger.horizon-walker.ethereal-step','Ethereal Step','ranger.horizon-walker',7,'You can cast etherealness on yourself until the end of the current turn by expending a bonus action.'),
f('ranger.horizon-walker.distant-strike','Distant Strike','ranger.horizon-walker',11,'You can teleport before each attack and make an additional attack when you attack at least two creatures.'),
f('ranger.horizon-walker.spectral-defense','Spectral Defense','ranger.horizon-walker',15,'When you take damage from an attack, you can use your reaction to gain resistance to that attack’s damage.'),
// Sorcerer
f('sorcerer.divine-soul.divine-magic','Divine Magic','sorcerer.divine-soul',1,'You can learn spells from the cleric spell list in addition to the sorcerer list, subject to the feature.'),
f('sorcerer.divine-soul.favored-by-the-gods','Favored by the Gods','sorcerer.divine-soul',1,'When you fail a saving throw or miss an attack roll, you can add 2d4 to the result.'),
f('sorcerer.divine-soul.empowered-healing','Empowered Healing','sorcerer.divine-soul',6,'You can spend sorcery points to reroll dice when you or an ally within range regains hit points.'),
f('sorcerer.divine-soul.otherworldly-wings','Otherworldly Wings','sorcerer.divine-soul',14,'You can manifest wings and gain a flying speed as a bonus action.'),
f('sorcerer.divine-soul.unearthed-form','Unearthly Recovery','sorcerer.divine-soul',18,'You can recover hit points equal to half your maximum hit points once per long rest when reduced to below half.'),
f('sorcerer.shadow-magic.eyes-of-the-dark','Eyes of the Dark','sorcerer.shadow-magic',1,'You gain darkvision and later gain the ability to cast darkness with sorcery points.'),
f('sorcerer.shadow-magic.strength-of-the-grave','Strength of the Grave','sorcerer.shadow-magic',1,'When reduced to 0 hit points, you can make a Charisma saving throw to drop to 1 hit point instead.'),
f('sorcerer.shadow-magic.hound-of-ill-omen','Hound of Ill Omen','sorcerer.shadow-magic',6,'You can spend sorcery points to summon a shadow hound that relentlessly pursues a target.'),
f('sorcerer.shadow-magic.shadow-walk','Shadow Walk','sorcerer.shadow-magic',14,'You can teleport from one area of dim light or darkness to another as a bonus action.'),
f('sorcerer.shadow-magic.umbrally-form','Umbral Form','sorcerer.shadow-magic',18,'You can become shadowy and move through objects and creatures while gaining resistance to nonmagical damage.'),
f('sorcerer.storm-sorcery.wind-speaker','Wind Speaker','sorcerer.storm-sorcery',1,'You learn Primordial and can speak it to communicate with creatures that know its dialects.'),
f('sorcerer.storm-sorcery.tempestuous-magic','Tempestuous Magic','sorcerer.storm-sorcery',1,'Immediately before or after casting a spell of 1st level or higher, you can fly up to 10 feet without provoking opportunity attacks.'),
f('sorcerer.storm-sorcery.heart-of-the-storm','Heart of the Storm','sorcerer.storm-sorcery',6,'You gain resistance to lightning and thunder damage and can deal storm damage to nearby creatures when casting qualifying spells.'),
f('sorcerer.storm-sorcery.storm-guide','Storm Guide','sorcerer.storm-sorcery',6,'You can subtly control wind and later precipitation in your surrounding area.'),
f('sorcerer.storm-sorcery.storms-fury','Storm’s Fury','sorcerer.storm-sorcery',18,'When hit by a melee attack, you can use your reaction to deal lightning damage and potentially knock the attacker prone.'),
// Warlock
f('warlock.celestial.expanded-spell-list','Expanded Spell List','warlock.celestial',1,'The Celestial lets you choose from additional spells when you learn a warlock spell.'),
f('warlock.celestial.healing-light','Healing Light','warlock.celestial',1,'You gain a pool of d6s that can restore hit points to creatures within range as a bonus action.'),
f('warlock.celestial.radiant-soul','Radiant Soul','warlock.celestial',6,'You gain resistance to radiant damage and can add radiant damage to one damage roll of a spell or attack once per turn.'),
f('warlock.celestial.celestial-resilience','Celestial Resilience','warlock.celestial',10,'You gain temporary hit points after a short or long rest and can grant temporary hit points to allies.'),
f('warlock.celestial.searing-vengeance','Searing Vengeance','warlock.celestial',14,'When reduced to 0 hit points, you can regain hit points and deal radiant damage to nearby creatures, potentially blinding them.'),
f('warlock.hexblade.hexblades-curse','Hexblade’s Curse','warlock.hexblade',1,'You curse a creature, gaining bonuses to attacks, critical hits, and hit-point recovery against it.'),
f('warlock.hexblade.hex-warrior','Hex Warrior','warlock.hexblade',1,'You gain medium armor, shield, and martial weapon proficiency and can use Charisma for attacks with one suitable weapon.'),
f('warlock.hexblade.accursed-specter','Accursed Specter','warlock.hexblade',6,'You can raise a slain humanoid as a specter that obeys your commands until your next long rest.'),
f('warlock.hexblade.armor-of-hexes','Armor of Hexes','warlock.hexblade',10,'When your cursed target hits you, you can use your reaction to roll a d6 and potentially cause the attack to miss.'),
f('warlock.hexblade.master-of-hexes','Master of Hexes','warlock.hexblade',14,'When your cursed target dies, you can transfer the curse to another creature you can see within range.'),
// Wizard
f('wizard.war-magic.arcane-deflection','Arcane Deflection','wizard.war-magic',2,'When hit or failing a saving throw, you can use your reaction to gain a bonus to AC or the saving throw.'),
f('wizard.war-magic.tactical-wit','Tactical Wit','wizard.war-magic',2,'You add your Intelligence modifier to initiative rolls.'),
f('wizard.war-magic.power-surge','Power Surge','wizard.war-magic',6,'You can store arcane energy and expend it to deal extra force damage with a spell.'),
f('wizard.war-magic.durable-magic','Durable Magic','wizard.war-magic',10,'While concentrating on a spell, you gain bonuses to AC and saving throws.'),
f('wizard.war-magic.deflecting-shroud','Deflecting Shroud','wizard.war-magic',14,'When you use Arcane Deflection, you can cause creatures of your choice near you to take force damage.'),
];