import {useMemo,useState} from 'react';
import {TEST_CHARACTER,SPELLS} from './domain/sample-data';
import {SKILLS,armorClass,hpPercent,initiative,passivePerception,skillBonus} from './domain/rules';
import type {Character,Item,ItemKind,Skill,Spell} from './domain/types';

const sections=['sheet','skills','equipment','spells','features','resources'] as const; type Section=typeof sections[number];
const labels:Record<Section,string>={sheet:'Character Sheet',skills:'Skills',equipment:'Equipment',spells:'Spells',features:'Features',resources:'Resources'};
function App(){
 const [c,setC]=useState<Character>(structuredClone(TEST_CHARACTER)); const [section,setSection]=useState<Section>('sheet'); const [spellTab,setSpellTab]=useState<'prepared'|'list'>('prepared');
 const setHP=(v:number)=>setC(x=>({...x,currentHP:Math.max(0,Math.min(x.maxHP,v))}));
 const toggleSkill=(s:Skill,type:'proficient'|'expertise')=>setC(x=>({...x,skillStates:{...x.skillStates,[s]:{...x.skillStates[s],[type]:!x.skillStates[s][type],...(type==='expertise'?{proficient:true}:{})}}}));
 const prepared=Object.values(c.spellcasting).flatMap(x=>[...x.alwaysPrepared,...x.prepared]); const classId=c.classes[0].id;
 const classSpells=SPELLS.filter(s=>s.classes.includes(classId));
 const togglePrepared=(id:string)=>setC(x=>{const sc=x.spellcasting[classId];const prepared=new Set(sc.prepared);prepared.has(id)?prepared.delete(id):prepared.add(id);return {...x,spellcasting:{...x.spellcasting,[classId]:{...sc,prepared:[...prepared]}}};});
 const grouped=useMemo(()=>Object.groupBy(classSpells,s=>s.level),[classSpells]);
 return <div className="app"><header><div><span className="eyebrow">5e 2014 · Character Companion</span><h1>{c.name}</h1><p>{c.species} · {c.classes.map(x=>`${x.name} ${x.level}`).join(' / ')} · {c.classes[0].subclassName}</p></div><div className="header-stats"><b>Level {c.level}</b><span>PB +{c.proficiencyBonus}</span></div></header>
 <nav>{sections.map(s=><button className={section===s?'active':''} onClick={()=>setSection(s)} key={s}>{labels[s]}</button>)}</nav>
 <main>{section==='sheet'&&<Sheet c={c} setHP={setHP}/>} {section==='skills'&&<Skills c={c} toggle={toggleSkill}/>} {section==='equipment'&&<Equipment c={c} setC={setC}/>} {section==='spells'&&<Spells c={c} tab={spellTab} setTab={setSpellTab} prepared={prepared} grouped={grouped} toggle={togglePrepared}/>} {section==='features'&&<Features c={c}/>} {section==='resources'&&<Resources c={c}/>}</main></div>
}
function Sheet({c,setHP}:{c:Character;setHP:(v:number)=>void}){return <div className="grid"><section className="card hero"><div className="hp"><div><small>HIT POINTS</small><strong>{c.currentHP} / {c.maxHP}</strong></div><div className="hpbar"><i style={{width:`${hpPercent(c)}%`}}/></div><input type="number" value={c.currentHP} onChange={e=>setHP(Number(e.target.value))}/><div className="hp-actions"><button onClick={()=>setHP(c.currentHP-1)}>−1</button><button onClick={()=>setHP(c.currentHP+1)}>+1</button><button onClick={()=>setHP(c.currentHP-5)}>−5</button><button onClick={()=>setHP(c.currentHP+5)}>+5</button></div></div></section><section className="card stats"><h2>Combat</h2><div className="statgrid"><b>AC <span>{armorClass(c)}</span></b><b>Initiative <span>{initiative(c)>=0?`+${initiative(c)}`:initiative(c)}</span></b><b>Passive Perception <span>{passivePerception(c)}</span></b><b>Hit Dice <span>{c.hitDice.current}/{c.hitDice.max} d{c.hitDice.die}</span></b></div></section><section className="card"><h2>Ability Scores</h2><div className="statgrid six">{Object.entries(c.abilityScores).map(([a,v])=><b key={a}>{a.toUpperCase()} <span>{v} ({v>=10?'+':''}{Math.floor((v-10)/2)})</span></b>)}</div></section><section className="card"><h2>Defenses & Status</h2><p>Conditions: {c.conditions.length?c.conditions.join(', '):'None'}</p><p>Resistances: {c.resistances.length?c.resistances.join(', '):'None'}</p><p>Death Saves: {c.deathSaves.successes} successes · {c.deathSaves.failures} failures</p></section></div>}
function Skills({c,toggle}:{c:Character;toggle:(s:Skill,t:'proficient'|'expertise')=>void}){return <section className="card"><h2>Skills</h2><p className="muted">Click the proficiency or expertise control. Expertise requires proficiency.</p><div className="skill-list">{(Object.keys(SKILLS) as Skill[]).map(s=>{const st=c.skillStates[s];return <div className="skill" key={s}><span>{SKILLS[s].name}<small>{SKILLS[s].ability.toUpperCase()}</small></span><b>{skillBonus(c,s)>=0?`+${skillBonus(c,s)}`:skillBonus(c,s)}</b><button className={st.proficient?'tick on':'tick'} onClick={()=>toggle(s,'proficient')} aria-label={`Proficiency ${SKILLS[s].name}`}>P</button><button className={st.expertise?'tick expert':'tick'} onClick={()=>toggle(s,'expertise')} aria-label={`Expertise ${SKILLS[s].name}`}>E</button></div>})}</div></section>}
function Equipment({c,setC}:{c:Character;setC:React.Dispatch<React.SetStateAction<Character>>}){const kinds:ItemKind[]=['armor','weapon','shield','focus','gear','magic'];const add=(kind:ItemKind)=>{const item:Item={id:crypto.randomUUID(),name:kind==='weapon'?'New Weapon':kind==='armor'?'New Armor':kind==='shield'?'New Shield':'New Item',kind,quantity:1,equipped:false,description:'',...(kind==='weapon'?{weapon:{attackAbility:'str',proficient:false,attackBonus:0,damageBonus:0,damage:[{dice:1,die:8,type:'slashing'}],properties:[]}}:{}),...(kind==='armor'?{armor:{category:'light',baseAC:11,dexBonus:true,stealthDisadvantage:false,magicBonus:0}}:{}),...(kind==='shield'?{shield:{acBonus:2,magicBonus:0}}:{})};setC(x=>({...x,items:[...x.items,item]}));};return <div className="grid">{kinds.map(k=><section className="card" key={k}><div className="row"><h2>{k[0].toUpperCase()+k.slice(1)}</h2><button onClick={()=>add(k)}>+ Add</button></div>{c.items.filter(i=>i.kind===k).map(i=><div className="item" key={i.id}><div><b>{i.name}</b><small>{i.description||'No description'}</small></div><span>{i.equipped?'Equipped':'Carried'}</span></div>)}{!c.items.some(i=>i.kind===k)&&<p className="muted">No items.</p>}</section>)}</div>}
function Spells({c,tab,setTab,prepared,grouped,toggle}:{c:Character;tab:'prepared'|'list';setTab:(x:'prepared'|'list')=>void;prepared:string[];grouped:Record<string,Spell[]|undefined>;toggle:(id:string)=>void}){const sc=c.spellcasting[c.classes[0].id];return <section className="card"><div className="row"><h2>Spells</h2><div className="tabs"><button className={tab==='prepared'?'active':''} onClick={()=>setTab('prepared')}>Prepared</button><button className={tab==='list'?'active':''} onClick={()=>setTab('list')}>Class Spell List</button></div></div>{tab==='prepared'?<><h3>Always Prepared</h3>{sc.alwaysPrepared.map(id=><SpellRow key={id} spell={SPELLS.find(s=>s.id===id)} locked/>)}<h3>Prepared by You</h3>{sc.prepared.map(id=><SpellRow key={id} spell={SPELLS.find(s=>s.id===id)} onClick={()=>toggle(id)}/>)}</>:Object.keys(grouped).sort((a,b)=>+a-+b).map(level=><div className="spell-level" key={level}><h3>{level==='0'?'Cantrips':`Level ${level}`}</h3>{grouped[level]?.map(s=><SpellRow key={s.id} spell={s} active={prepared.includes(s.id)} onClick={()=>toggle(s.id)}/>)}</div>)}</section>}
function SpellRow({spell,onClick,active,locked}:{spell?:Spell;onClick?:()=>void;active?:boolean;locked?:boolean}){if(!spell)return <p className="muted">Spell data unavailable.</p>;return <button className={`spell ${active?'selected':''}`} disabled={locked} onClick={onClick}><span><b>{spell.name}</b><small>{spell.school} · Level {spell.level}{spell.concentration?' · Concentration':''}</small></span><i>{locked?'Always prepared':active?'Prepared':'Add'}</i></button>}
function Features({c}:{c:Character}){return <section className="card"><h2>Features & Traits</h2>{c.features.map(f=><article className="feature" key={f.id}><b>{f.name}</b><small>{f.source} · Level {f.level}</small><p>{f.description||'Feature details will be populated from the rules dataset.'}</p></article>)}</section>}
function Resources({c}:{c:Character}){return <div className="grid">{c.resources.map(r=><section className="card resource" key={r.id}><h2>{r.name}</h2><strong>{r.current} / {r.max}</strong><small>Recharge: {r.recharge}</small></section>)}</div>}
export default App;
